### ISSUE TITLE
Porndoe Premium Network support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#100]
I'm in the process of tagging my Porndoe Premium Network scenes but i'm stuck with this scene: Porndoe Premium Network - SOAKING WET https://letsdoeit.com/trailer/12793/soaking-wet whatever I do I can't get the agent to find the scene, i've tried:
Porndoe Premium Network - SOAKING WET (and Soaking and wet apart)
Porndoe Premium Network - 12793

Can you help?

**Comment by PAhelper** [comment]
Try "Porndoe Premium - Soaking Wet" or "A Girl Knows - Soaking Wet"

**Comment by insickin** [comment]
Thanks now it finds the scene!
