### ISSUE TITLE
Automatic actors playlist generation

### ISSUE THREAD

**Issue by pahelper3** [PAhelper/PhoenixAdult.bundle#1002]
Hi folks, thanks for your amazing work with this awesome plugin, it's terrific!
I was wondering if it's possible to integrate an automatic playlist generation tool which generates playlist by actor, would it be possible? And if automation won't be possible, why not creating a separated tool to manually generate it?

I mean, sometimes you just want to simply search for a particular actor, and if your database is huge, you can't just simply create a playlist one by one. This idea could also be extended for particular genres, which actually is quite simple to handle.

In my Plex instance I have something like 200 actors, it would be nice to access to their videos with a playlist.

**Comment by pahelper3** [comment]
Hi, thanks for your fast reply! Well if it couldn't be automatic, at least would be interesting to create a post processor script which could be ran from a shell that categorizes each actor one by one. The collection way is also interesting, but could it be viewed the same way as the playlist/movies sections? The final object is to access directly to a set of movies/episodes coming from the actor you are interested in

**Comment by PowerModder** [comment]
Collection was easy to implement to test some things but for this to be possible all site .py must be reviewed which is not good. I couldn't find a way to pass playlist as metadata and tbh i don't know if it is possible. If it was so important to create a playlist for all the actors i would have take one day off and apply smartPlaylists for all my actors at my collection. I am trying to find something faster for you but it would be Plex-related not Agent-related.

**Comment by PowerModder** [comment]
I believe this is what you are looking for @pahelper3 : https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py
As I can see you need to edit the settings and put those variables
```
PLEX_URL = ''
PLEX_TOKEN = ''
TAUTULLI_URL = ''
TAUTULLI_APIKEY = ''
```
Then you can run the script by hitting it to a cmd/powershell/terminal. For example this should create a playlist from XXX library with all Aidra's Fox scenes to the Admin account. I didn't try it myself though. Also I don't know if those playlists will be Smart or Simple. As I can understand those playlists will be simple because it provides you an update function as i can see to the documentation. Smart playlists will automatically updated if you add a new scene of an actor.

`python playlist_manager.py --name "Aidra Fox" --libraries "XXX" --filter actor="Aidra Fox" --action add --self`

**Comment by PowerModder** [comment]
If the above is correct and it works then you can make another .py and by having a 'list' of your actors you can have a for loop that is going to call the above script for every single actor in that list.

**Comment by PowerModder** [comment]
I'm also attaching this that i found just now.
https://python-plexapi.readthedocs.io/en/latest/modules/playlist.html#plexapi.playlist.Playlist.create
Seems that you CAN create a smart playlist by using PlexAPI.

**Comment by PowerModder** [comment]
@pahelper3 Well. I made the script you wanted :P I will PR it as useful scripts and also leave it in here too. Sure there will be a more elegant way to do this but it did the trick you wanted (tested on my library). Bare in mind that this script don't categorize the actor as male or female so it will build playlists for ALL actors at a specific library.
Don't forget to pip install plexapi and then open the .py and edit the fields where i have the comments.
[playlist-generator-based-on-actors.zip](https://github.com/PAhelper/PhoenixAdult.bundle/files/5205367/playlist-generator-based-on-actors.zip)
Have Fun!

**Comment by pahelper3** [comment]
@PowerModder thanks for the library, I developed one on my own and I was going to upload a PR but three days after you wrote this one. Mine was not smart so I had to reload them every time I added a scene.

Many thanks!! I think this could be very useful for the community.

You also mentioned gender, since I mainly perform researches based on actresses instead of male performers, do you think this algorithm could be enhanced in order to create only female playlists? I digged around the code but I think actually PhoenixAdult is not gathering actor's gender.
