### ISSUE TITLE
network1service - Don't return Actor Data (Name & Poster) as metadata

### ISSUE THREAD

**Issue by PowerModder** [PAhelper/PhoenixAdult.bundle#1006]
I refreshed my metadata at my library and all Actor Info were gone from all network1service scenes after the token update.

**Comment by PowerModder** [comment]
Well that was easy. Change line 84 to siteID instead of siteNum. (According to log that where it crashed)

**Comment by DirtyRacer1337** [comment]
Fixed in aafe942177574d1804a79d447f76f786c72d86be
