### ISSUE TITLE
DogHouseDigital no shows any information

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1014]
DogHouseDigital no shows any information, only the title.

**Include**
1. https://www.doghousedigital.com/scene/4383084/incredible-ass-vol-02-scene-5
2. DogHouseDigital - Incredible Ass Vol 02 Scene 5.mp4
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5183858/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Update your plugin
