### ISSUE TITLE
Babes matching not working

### ISSUE THREAD

**Issue by ddragon3** [PAhelper/PhoenixAdult.bundle#102]
Having a few issues with the Babes Network. It looks like the search function is now found under https://www.babes.com/search?q= instead of https://www.babes.com/tour/search/all/keyword/ (which 404's). 

On top of that, the search function doesn't seem to pull anything up once corrected to the right url. I initially thought that it was because the encodedtitle added %20 to the end of the search function, which seems to not work. So https://www.babes.com/search?q=alexis or https://www.babes.com/search?q=alexis% provides results, but https://www.babes.com/search?q=alexis%20 doesn't return any. However, after sorting that out on line 693 of  PAsearchSites.py by erasing the space in between quotes, it still doesn't allow for any matches in plex. I'm in over my head at this point, any suggestions?

**Comment by PAhelper** [comment]
I took a brief look at this, and the new site layout is more complex than a simple code change. I'll have to dig into this one more. Unfortunately for now, Babes (and related sites) simply won't work.

**Comment by ddragon3** [comment]
No worries, thanks for checking into it, also thanks for confirming I'm not crazy/that it isn't just a problem I was having. Keep up the great work, I really appreciate all you've done!

**Comment by SgtBatten** [comment]
I just had a crack at this. same issue im having with #114 
The page source simply doesn't contain any of the info we need. Need to work out how to inject our search into it

**Comment by Duglim** [comment]
Was anyone able to dig deeper into this issue? I'm afraid I can't help myself, but would be very happy to see a solution. I know you can make it happen. :)

**Comment by Duglim** [comment]
Guys, maybe do you already checked https://www.babesnetwork.com for grabbing the metadata and posters? The source code looks simple and all data seems to be there. 

e.g.
`<div class="video-info__container center clearfix">
        <h1>Scandalous</h1>
        <span class="video-info__description">
            <a class="js-description notracking" href="javascript:void(0);" rel="nofollow">Description</a>
        </span>
        <div class="scene-detail">
            <p class="section-detail section-detail--description">
                With a lazy breeze and the warm California sun washing over her, Janice Griffith was happy to spend the afternoon noodling on her guitar. Her boyfriend Bruce had other ideas, however, and cast aside all her plans with a deep French kiss on her mouth. After they made out, Bruce pulled down Janice's panties and pressed his face between her legs from behind, licking at her pussy and crack. After enjoying his skillful tongue, Janice got on her knees and took the entirety of his huge cock in her mouth, pushing the shaft all the way to the back of her throat. Only a strong guy like Bruce could pick her up and fuck her standing up, warming her up for the hot sex to follow. First, Janice rode Bruce sitting down, then they went to the patio-bed and Bruce humped her just the way she likes it: from behind and spooning.<br>
            </p>
            <p class="section-detail section-detail--tags last">
                <span class="scene-detail__label">Categories:</span>
                <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category gonzo - scene id 12521" href="/tour/categories/index/t/3/n/gonzo/" >Gonzo</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category outdoors - scene id 12521" href="/tour/categories/index/t/126/n/outdoors/" >Outdoors</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category sex - scene id 12521" href="/tour/categories/index/t/151/n/sex/" >Sex</a><span class="scene-categories-more"> <a href="#" class="show-more notracking" onclick="$('.scene-categories-more').toggle(); return false;">Show more</a></span><span class="scene-categories-more" style="display:none;">, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category deep throat - scene id 12521" href="/tour/categories/index/t/178/n/deep-throat/" >Deep Throat</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category doggystyle - scene id 12521" href="/tour/categories/index/t/213/n/doggystyle/" >Doggystyle</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category cowgirl - scene id 12521" href="/tour/categories/index/t/215/n/cowgirl/" >Cowgirl</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category reverse cowgirl - scene id 12521" href="/tour/categories/index/t/216/n/reverse-cowgirl/" >Reverse Cowgirl</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category spoon - scene id 12521" href="/tour/categories/index/t/218/n/spoon/" >Spoon</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category pussy licking - scene id 12521" href="/tour/categories/index/t/266/n/pussy-licking/" >Pussy Licking</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category blowjob - scene id 12521" href="/tour/categories/index/t/267/n/blowjob/" >Blowjob</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category stand and carry - scene id 12521" href="/tour/categories/index/t/347/n/stand-and-carry/" >Stand And Carry</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category cum on pussy - scene id 12521" href="/tour/categories/index/t/425/n/cum-on-pussy/" >Cum on Pussy</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category side fuck - scene id 12521" href="/tour/categories/index/t/466/n/side-fuck/" >Side Fuck</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category girlfriend - scene id 12521" href="/tour/categories/index/t/513/n/girlfriend/" >Girlfriend</a>, <a class="notracking" data-trackid="BBN:TOUR:VIDEOS:LINK category couples - scene id 12521" href="/tour/categories/index/t/531/n/couples/" >Couples</a> <a href="#" onclick="$('.scene-categories-more').toggle(); return false;" class="show-more notracking">Show less</a></span>            </p>
        </div>
        <span class="video-info__date">Jun 22, 2014</span>
    </div>`

If you already knew, please ignore me. I'm looking for ways to get babes matching again, since this is missing on my lib.

**Comment by Duglim** [comment]
I was able to test it myself. It's working, you just need to change all babes.com URLs in th PASearchSites.py to babesnetwork.com. Seems to be still the old page with a different URL.

There is one issue: Since the main site relaunched, there seem to be no posters or picuted of the since then released videos on the babesnetwork.com site. All text metadata is there. 
For rebuilding a babes library it should be very helpful nevertheless having all other clips matching.

**Comment by claygoldfinch** [comment]
Have we decided on a way to address this? 

The search functionality of the new site SUCKS (it seems as though it only utilizes one word of any phrase you input??), but it is semi-usable. 

I've written up some code that "works" with the new site layout. Let me know if I should commit, or if we're looking actively looking at another method of resolving this.

**Comment by insickin** [comment]
Maybe it can be a temporary patch? Does this code also work for the other sites that are broken or is it Babes specific?

**Comment by claygoldfinch** [comment]
I've only worked on the code for scraping Babes, but it could probably be updated to work for other sites with similar layouts. 

Just based on a quick look, I'd say Digital Playground and Twistys are possible. Their site layout is similar to that of Babes, plus their search functionality works to some extent. 

MOFOS has a similar site layout, but their search functionality is essentially unusable (seems like the web devs didn't set it up correctly). So MOFOS is out of the question until they fix that.

**Comment by claygoldfinch** [comment]
Resolved via sceneID match in PR #225. Read the PR notes if you're having issues.
