### ISSUE TITLE
straplezz not matching/working

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#1026]
I am trying to match a straplezz scene but the agent comes back with: No Matches found.

Example:
1. Scene URL = https://straplezz.com/updates/Pulse-Shows-She-Wants-Some-Strapon.html
2. File Name = Straplezz - Hot Legs and Strapon Sex also searched with Pulse Shows She Wants Some Strapon 
3. Log File = [Log.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5210657/Log.log)

**Comment by DirtyRacer1337** [comment]
Fixed in 50bd2f9031504f5642400ab01e2e68cfb135d423
