### ISSUE TITLE
ActorSmartPlaylistGenerator does not catch all scenes

### ISSUE THREAD

**Issue by Spanishu** [PAhelper/PhoenixAdult.bundle#1035]
@DirtyRacer1337 

**Describe the bug**
I have tried this script and I love the idea! I have run it on my libraries and I have seen that it catches most of the scenes of the actors. However I have run it and it does not catch all scenes of an actress. I have tried to run it again but it did not change. 
I have Monique Alexander in a library with 88 entries and in another one with 25. It seems that the agent only populates the entries from the first library.
Any suggestion

**Comment by PowerModder** [comment]
This is correct as the script is. It is library driven, so if you have for example XXX - 2D and XXX - VR and the same actor and you run the script for the XXX library then the scenes for THAT library will be in the playlist.

**Comment by Spanishu** [comment]
Ok, thanks for the update. Can the script overwrite the playlist or do you see a chance to have the script being able to combine libraries? The latter would be actually perfect!

**Comment by DirtyRacer1337** [comment]
Check last version, I added working with multiple libraries, but looks like it's imposible to combine smart playlists.

**Comment by Spanishu** [comment]
Thanks!
it creates to playlist entries, not 100% perfect but good enough for the moment. 
Works like a charm
