### ISSUE TITLE
FeatureRequest: Custom Tagging of Actors and Collection

### ISSUE THREAD

**Issue by monkTertman** [PAhelper/PhoenixAdult.bundle#1039]
## Description

So there are a lot of scenes which are from these random websites which are small and may not make it into agent sooner.
For some website its just not possible to add them.
So offer a solution to user, how about adding a custom tagging feature.
User can use a particular string type to invoke custom tagging in a video.

For example: using predefined syntax

`@PACustom % Nicole Aniston % BBC Paradise`

`@PACustom % Nicole Aniston, Lana Rhoades % BWB`

Thoughts?

**Comment by cactuzjak** [comment]
there's already a manual add. https://github.com/PAhelper/PhoenixAdult.bundle/pull/155

example:

add 2020.09.17 Nicole Aniston in Scene Title at BBC Paradise
add 2020.09.17 Nicole Aniston and Lana Rhoades in Scene Title at BWB

**Comment by monkTertman** [comment]
Thanks @cactuzjak . This is really great feature
We should add this readme, syntax on how to add custom scene tagging.
