### ISSUE TITLE
Plug-In not showing or working?

### ISSUE THREAD

**Issue by IntricateTurtle** [PAhelper/PhoenixAdult.bundle#1043]
I'm on the latest version of Plex. Tried installing both manually and via WebTools. The plugin never shows inside the plugins tab of Plex, and when refreshing metadata with a filename that matches the spec, nothing happens.

Followed the instructions exactly. Tried restarting plex and the whole server, no luck either.

**Comment by DirtyRacer1337** [comment]
Check agents

**Comment by IntricateTurtle** [comment]
@DirtyRacer1337 Checked that and think I set it up appropriately. Still no metadata, even after telling plex to refresh the metadata in the whole library not a single one went through, so I'm not really sure what's going wrong. 

Doesn't appear to be any errors in the Plex log either.

**Comment by DirtyRacer1337** [comment]
Send `com.plexapp.agents.phoenixadult.log` file
https://support.plex.tv/articles/200250417-plex-media-server-log-files/

**Comment by agentandroid** [comment]
when I tried installing I couldnt see it either, went into the pms log
heres the log
https://pastebin.com/tvjwjAmw

**Comment by DirtyRacer1337** [comment]
Follow the guide, https://github.com/PAhelper/PhoenixAdult.bundle#installation, that's all I can tell you, problem not in plugin, ask on plex forum
