### ISSUE TITLE
Metart Network Import Issue

### ISSUE THREAD

**Issue by dsrtusr88** [PAhelper/PhoenixAdult.bundle#1052]

**Comment by DirtyRacer1337** [comment]
Same as #1000

**Comment by dsrtusr88** [comment]
@DirtyRacer1337 I see he closed that ticket, what was the resolution?

**Comment by DirtyRacer1337** [comment]
Looks like @cristiano1976pt did nothing. I reported this error to them. Their dev team should fix it.

**Comment by covrdinbeez** [comment]
> @DirtyRacer1337 I see he closed that ticket, what was the resolution?

You could look on their site and realize that the following link to the movie is such:
https://www.vivthomas.com/model/chloe-cherry-and-kendra-spade/movie/20200903/BIRTHDAY_KISSES

And looking at the page, even though it shows in the search and "exists" it goes to a "404 Not Found." So I'm not exactly sure what you expect to get tagged from a page that is a 404.

As @DirtyRacer1337 said, report the errors to the site.

**Comment by DirtyRacer1337** [comment]
@dsrtusr88 Did they fix it?
