### ISSUE TITLE
Fitting Room sometimes missing cast/date info

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#1056]
I am tagging a few Fitting Room scenes, now it strikes me that some scenes do have cast info / photos and others don't. The scenes that have no cast info also don't get date info. (and seem to get another cover photo ( no model name on the photo))

1. Scene URL
https://www.fitting-room.com/videos/249/anastasia-brokelyn-multi-orgasmic/
&
https://www.fitting-room.com/videos/252/anya-krey-secretary-show/
2. File Name
Fitting-Room - Anastasia Brokelyn - Multi Orgasmic
Fitting-Room - Anya Krey - Secretary Show
I change the names of the scene's in the search box to:
FittingRoom - 249
FittingRoom - 252

3. Log File
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5416923/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Try with ed99030412231b3352638f9fb1b8785371adafab

**Comment by insickin** [comment]
Tanks as always for your fast help/solution! The actor info/photo / cover photo are working flawlessly now! Only the agent doesn't pick up the date info, on my older (already tagged before) scenes the agent tags te date info, can you take a look at that and fix it?

**Comment by DirtyRacer1337** [comment]
Date should be added manualy
https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/sitelist.md#fitting-room--matching-type-exact---sceneid-date-add
https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/manualsearch.md#notes

**Comment by insickin** [comment]
Ok, strange that some of the scenes from them get the date automatically tagged, again thanks!
