### ISSUE TITLE
X-Art - Not pulling posters (Error 403)

### ISSUE THREAD

**Issue by MicrobioDigital** [PAhelper/PhoenixAdult.bundle#1062]
Hello, I'm trying to scrap some scenes from X-Art but it's been impossible, log chunk provided (the latest events show the error)

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5442034/com.plexapp.agents.phoenixadult.log)

Thanks!

**Comment by DirtyRacer1337** [comment]
Try to use VPN

**Comment by kkycble** [comment]
Having the same problem. Can successfully get all the metadata, but only one blurry poster.

**Comment by Fallenfederation** [comment]
I have the same issue. I did try to use a vpn in and out of the US with no help. I backed up my old agent before I updated it the old one will find some posters but leaves all the others with a gray generic poster. The updated version will give only standard xart posters that it does not even apply to the video you half to do it manually. Any help would be appreciated.
