### ISSUE TITLE
letsdoeit.com has stopped matching (the white boxxxx)

### ISSUE THREAD

**Issue by thehooziers** [PAhelper/PhoenixAdult.bundle#1063]
White Boxxx files are not being found, either automatically or by following the enhanced search method.

1. https://letsdoeit.com/watch/5595/submissive-ukrainian-blonde-nancy-a-gets-tied-up-and-fucked-deep.en.html

2. TheWhiteBoxxx.16.07.03.Nancy.A.XXX.1080p.MP4

3. [com.plexapp.agents.phoenixadult-2.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5444175/com.plexapp.agents.phoenixadult-2.log)

**Comment by DirtyRacer1337** [comment]
That's should help 3c48bdfdc456f57855661b20ae3f355d75e09ffb

**Comment by thehooziers** [comment]
Many thanks!
