### ISSUE TITLE
Usenet issue

### ISSUE THREAD

**Issue by mturcich24** [PAhelper/PhoenixAdult.bundle#1065]
When pulling down files via usenet a folder get created in the format as such: ProductionCompany.DateofScene.ActorFirstname.ActorLastname.Scenename.Category.Resolution.Videoformat

The file for the video comes out like this 16292acd6e504d9ab2ae582e11739f95.mp4

Is there a way to have the plug-in check the folder name instead of just the file using the format above?

**Comment by chempke** [comment]
The better way would be to rename the files. In your case i would recommend the [advanced renamer](https://www.advancedrenamer.com/download) program. 
This is free for private use and can rename all of your video files at once. 

Set up advanced renamer:
1. Add the folder with the video files that should be renamed > check [x] Add the files in the folders 
2. Delete all non video files from the list
3. Add method > New Name > choose "<DirName> - Name of the directory
4. Batch mode: Move > Output folder: <Name>
5. Start batch

**Comment by DirtyRacer1337** [comment]
Should work now

**Comment by mturcich24** [comment]
> Should work now

What should be working now? @DirtyRacer1337

**Comment by DirtyRacer1337** [comment]
@mturcich24 Using directory name for search.
