### ISSUE TITLE
SexLikeReal not matching as *Enhanced*

### ISSUE THREAD

**Issue by Brak691** [PAhelper/PhoenixAdult.bundle#1078]
SexLikeReal is listed as having *Enhanced* matching on the sitelist doc, but it isn't matching when naming a file that way.

> Ex: SexLikeReal - 16130 - Fun in the Sun // This won't find _any_ matches even when manually searching.

It does match if you use the DirectURL as the file name though.

> Ex: SexLikeReal - fun-in-the-sun-16130 // This matches almost 100% of the time.

**Comment by DirtyRacer1337** [comment]
Works for me, probably that update helped 09842b75b70f2846ad17b325ff5866276c8a2d2d
