### ISSUE TITLE
Manual Add Name Glitch?

### ISSUE THREAD

**Issue by Heraizen** [PAhelper/PhoenixAdult.bundle#1085]
When adding tags with Manual add, words that have 'and' in them split the name. 

For example:

Add Brandi In Epic MILF Caught Cheating At MHBHJ

The Manual Add detects the Actors as two seperate: Br & I Love   (Br _and_ I Love).

Is there a way to fix this, using quotation marks in the search had no result for me.

**Comment by Tscherno** [comment]
Same issue here "Candy Alexa" tries to add two actors.

**Comment by DirtyRacer1337** [comment]
That should help ea180ded35e91646bac94d2a90b06dc44e89161f
