### ISSUE TITLE
Gina Gerson Not working

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1089]
GinaGerson.xxx not working, No Matches found

**Include**
1. https://ginagerson.xxx/scene/6702778/how-i-meet-shrima-part-2
2. GinaGerson - How I Meet Shrima Part 2
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5580606/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed in 8b0ab0e28a195a368607ddf2717ad9f4e6b8df92
