### ISSUE TITLE
Agent broken?

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#1099]
Hi, after updating to the newest version of the agent the agent doesn't work/get recognized/gets started   

I'm running Plex in a docker and getting:
Error starting framework core for /config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle.

Also in the log there is an error about:
searchSites[1065] = ("Mormon Girlz", "Mormon Girlz", "https://mormongirlz.com", "https://mormongirlz.com/?s=")
IndexError: list assignment index out of range

I think it has something to do with the addition of Mormon Girlz in the latest update

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5649117/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed in 47976984764c17f719a019481c6569ac9bbda764

**Comment by insickin** [comment]
Thanks that fixed the issue!
