### ISSUE TITLE
PorndoePremium do not match

### ISSUE THREAD

**Issue by nitschkecm** [PAhelper/PhoenixAdult.bundle#11]
There seems to be issues with the PorndoePremium site. I do not get any match anymore

**Comment by nitschkecm** [comment]
No I think there is different topic. I implemented that and it does not resolve. 
It looks like the site has changed and is actually now called https://letsdoeit.com/ so maybe some more rework is needed?

**Comment by nitschkecm** [comment]
I have made a small trial changing in the url to https://letsdoeit.com
here is the log. it seems like there is something missing. Anybody wants to take a look ? I am happy then to apply to the rest and fork back

[github.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/2680998/github.txt)

**Comment by macr0dev** [comment]
@nitschkecm, I've been reviewing the code this afternoon and it does indeed appear that they've made some decent sized changes.  The URL change doesn't really seem to be affecting things - it's more content changes in the page itself.  Specific tags that it's looking for don't exist anymore so it errors out.

For example, to even be able to update an item I had already matched using this agent, I had to comment out lines 104-107 where it was attempting to find the date.  They don't appear to be displaying the release date for the videos on the page any more.  I did find it down in some json data towards the bottom though.

The search url still works, but the parsing of the search result page as well as the individual item page need to be revamped.  I've run into this a couple of times with my Audiobook agent I maintain.  When the site changes it makes things fun.  :)

I've realized that this is a fork of the original project.  I'm guessing the original author is no longer maintaining things?  I haven't seen the needle move over there in about 3 months.

**Comment by nitschkecm** [comment]
@macr0dev thanks for taking the time to look into this. The original branch of Phoenix seems to be dead and @PAhelper  has done a good job to keep this alive. I am happy to test things out if you have code to check. Have quite a bit of content from that site ;)

**Comment by macr0dev** [comment]
I'll take a stab at it.  I've got some content from there I can load into my test server and do some testing with.  With the holiday's around the corner I'm going to be a little busy - but I'll try to squeeze in some time in the next two weeks.

**Comment by nitschkecm** [comment]
@macr0dev thanks a lot. as said let me know if you want me to test things. Happy holidays!

**Comment by PAhelper** [comment]
I think I have this working, but I only have a couple of files from The White Boxxx to test. @nitschkecm, @macr0dev give it a whirl and let me know?

**Comment by nitschkecm** [comment]
@PAhelper tried it out with several different files (different sub-sites from the Letsdoit) and worked like a charm. One needs to watch carefully which scene it is (the missing date) but otherwise all back to life! 1000Thanks!
