### ISSUE TITLE
url strings with certain words always stripped

### ISSUE THREAD

**Issue by dsrtusr88** [PAhelper/PhoenixAdult.bundle#1107]
**Describe the bug**
Because '4k' is in the string below, searches will always fail.  It would be great if you could do a search string in Plex as, 'newsensations "https://www.newsensations.com/tour_ns/updates/Megan-Marx-Teen-Step-Sister-Tiny-Tits-Step-Brother-Blowjob-Deepthroat-Facial-Cum-In-Mouth-4k.html"' to force the agent to go exactly to that page and parse the data.

**Include**
1. https://www.newsensations.com/tour_ns/updates/Megan-Marx-Teen-Step-Sister-Tiny-Tits-Step-Brother-Blowjob-Deepthroat-Facial-Cum-In-Mouth-4k.html
2. File Name
3. Log File

**Comment by DirtyRacer1337** [comment]
And why do you need it?
It's should be searchable by title 
[SiteList](https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/sitelist.md#newsensations--matching-type-enhanced---date-add)

**Comment by dsrtusr88** [comment]
oh this was substantially better, thanks!
