### ISSUE TITLE
Tushy.com search changed

### ISSUE THREAD

**Issue by plexuniverse** [PAhelper/PhoenixAdult.bundle#111]
It looks like the search changed;  I can no longer see any search results based on the current searchResults.xpath('//article[@class="videolist-item"]') filter.

**Comment by SgtBatten** [comment]
Seems to be using the same code as the blacked beta which is already in the code. At first glance it should be working still.

**Comment by plexuniverse** [comment]
You're right, I apologize; I was using an older version of the plug-in.  Thank you for the help and the fast response!
