### ISSUE TITLE
JulesJordan extra sites added

### ISSUE THREAD

**Issue by yes12397** [PAhelper/PhoenixAdult.bundle#113]
@PAhelper I added  title search for ManuelFerarra - TheAssFactory - SpermSwallowers
in my Fork if u want to merge it with yours.

thanks

**Comment by PAhelper** [comment]
@yes12397 I appreciate your effort, but those sites are already supported. I don't think I understand what you added to the project. Can you please explain?

**Comment by yes12397** [comment]
I will give u an example to clear the issue
try to search the following title :Abella Danger Loves It In Her ASS
if u searched it using manuelferrara : you will get results ( searching it from https://manuelferrara.com/trial/)
if u searched it using julesjordan : no results(searching it from https://www.julesjordan.com/trial/)
 
the reason is Manuel has some content which are considered as a bonus for his site 
so some video aren't available across julesjordan and only found in these niech sites , same goes with the other site.

what made me discover that : I had some julesjordan titles and didn't find any matching results , later I discovered that  i downloaded from manuelferrara ( which was a bonus in the julesjordan subscription)

I hope I explained it well :) and once again thanks for all the effort from everyone and specially ur self for the amazing work. and I will do my best to support everyone working on this project

**Comment by PAhelper** [comment]
I think I understand the confusion now. I didn't understand when you made issue #85 either, but I see now that issue and this one are the same thing.

I understand that JulesJordan.com and ManuelFerrara.com share some content, but other content is exclusive to the subsite. The content they share can be matched to either, while the content that is exclusive to ManuelFerrara.com (like your Abella Danger example above) MUST be matched to ManuelFerrara to find results.

I also think I understand your concern. In \_\_init\_\_.py, ManuelFerrara/TheAssFactory/SpermSwallowers all point to siteJulesJordan.py, so you were thinking that all 3 subsites just searched against www.julesjordan.com/trial, but this is not the case. I wrote the code to know when you are searching one of the subsites and it will use their search instead. When you search for "ManuelFerrera - Abella Danger Loves it in her Ass", it loads siteJulesJordan.py, but the code in there knows to use www.manuelferrara.com/trial when looking for your result.

If you are willing, please make a backup your code changes (just make a copy somewhere outside your Plex directory), and then install the newest version of my code. You should be able to match your Abella Danger example using "Manuel Ferrara - Abella Danger Loves it in the Ass" or something similar.
