### ISSUE TITLE
Manual Add glitching?

### ISSUE THREAD

**Issue by kkycble** [PAhelper/PhoenixAdult.bundle#1138]
It used to work perfectly. Today I tried adding another but the date got fused into actor name. 

I used “Add 20.08.08 Leanne Lace In E151 At POVPerv” and the actor name in cast tab would be “200808 Leanne Lace” and the year 2020 would fail to register after adding.

**Comment by DirtyRacer1337** [comment]
Fixed in 5ecdaad6c596312badddbafc4a2fb7a00f18a4e8
