### ISSUE TITLE
MrPOV vs MisterPOV

### ISSUE THREAD

**Issue by covrdinbeez** [PAhelper/PhoenixAdult.bundle#1184]
**Describe the bug**
Is there any reason that MrPOV (the actual name of the site) isn't used for matching, instead it looks like MisterPOV is?

**Include**
1. Scene URL
2. File Name
3. Log File

**Comment by DirtyRacer1337** [comment]
That should work 89f09180519e3dd1cecfd9f050b62b588ec825ca

**Comment by covrdinbeez** [comment]
Thanks, that fixed the search, but it didn't fix the issue of Mister POV vs MrPOV in the metadata.

The site is Mr POV, so any Mister POV references should really be Mr POV. I have a few previous scenes that were matched with Mr POV as the tagline as well as the collection.

Can we get it changed back?

For reference, https://www.mrpov.com/ refers to everything as Mr POV.

**Comment by DirtyRacer1337** [comment]
They use both variants on their site, it's not big problem. Someone may have some scenes matched as Mister POV, so if I made changes they can have same problems as you. You can fix that few scenes manually.

Also I check first release of this site, it's always was `Mister POV` in tagline.
