### ISSUE TITLE
MyLifeInMiami titles in UPPERCASE

### ISSUE THREAD

**Issue by covrdinbeez** [PAhelper/PhoenixAdult.bundle#1185]
**Describe the bug**
The titles for MyLifeInMiami are returning in all UPPERCASE. Is it possible to get Proper Case applied to the title when matching?

**Include**
1. Scene URL
2. File Name - MyLifeInMiami.20.02.04.Slim.Teen.Takes.Big.Dick.And.Loves.It.XXX.1080p.HEVC.x265-PRT.mp4
3. Log File

**Comment by DirtyRacer1337** [comment]
Fixed
