### ISSUE TITLE
Not finding all scenes for Brazzers

### ISSUE THREAD

**Issue by BeneficialDoor** [PAhelper/PhoenixAdult.bundle#1188]
Not all the scenes can be found using the brazzers api (https://site-api.project1service.com)
They are still available on the old(?) site stage4.brazzers.com

Examples:
https://stage4.brazzers.com/scenes/view/id/7621/pleasure-before-business/
http://stage4.brazzers.com/scenes/view/id/9655/brazzers-live-10-ruffntuff/

**Comment by DirtyRacer1337** [comment]
Ask their support, why scenes not exist on main sitem this is probably error. I've got some scenes what was matched before, but now they not exist.

Old site not supported.

**Comment by bigbadwolfie** [comment]
Both can be matched using Data 18 Content. i suggest using Data18 for older content w.r.t. the project1service sites. Data18 has content up to April 2018 when it died.

File Name/Search
Data18 Content - 1128731 - Pleasure Before Business
Data18 Content - 1165905 - Brazzers Live 10 Ruff'n'tuff

http://www.data18.com/content/1128731
http://www.data18.com/content/1165905
