### ISSUE TITLE
XEmpire/PureTaboo sites not pulling Poster/BG images

### ISSUE THREAD

**Issue by PAhelper** [PAhelper/PhoenixAdult.bundle#12]
Logs indicate a proper image file link, which works in a browser but for some reason the image doesn't get saved to the metadata. Perhaps a different referrer is needed?

**Comment by fritz276** [comment]
Yeah, its strange.
INFO (siteHardX:87) - BG DL: https://images03-openlife.gammacdn.com/movies/73848/73848_01/previews/11/68/top_1_resized/73848_01_01.jpg
But nothing in plex.

**Comment by PAHelper2** [comment]
This is a good read: https://forums.plex.tv/t/https-broken/216635/8

Might have to do something drastic.  I'm seeing the same SSL errors while trying to work on kink.com support.

**Comment by PAhelper** [comment]
Fixed this stupid easy. Turns out the content server that hosts their images also serves them up unsecure (ie. HTTP), so I just changed the URL to http:// and voila!
