### ISSUE TITLE
Issue with PornPros (NannySpy)

### ISSUE THREAD

**Issue by RalfvC** [PAhelper/PhoenixAdult.bundle#1206]
Site Name: NannySpy
Search Term: guilty-webcam-nanny-s-deal

For some reason the google search doesn't find any results.
It seams that the direct url also doesn't work. This is caused by the following code:

if unicode(directURL[-1], 'UTF-8').isdigit() and directURL[-2] == '-':

It seams that PornPros Network direct links don't have any digits in the direct url.

I found a solution by removing some code

So in the networkPornPros.py i removed line: 10 and removed the indent on line 11.

Then the following problem occurred: Requesting GET "https://nannyspy.com/video/guilty-webcam-nanny's-deal"
The apostrophe shouldn't be there so I also removed line 92 from PAsearchSite.py

Now the correct scene is displayed in the search results. I added everything back as this is not a structural solution, but I hope this information can find you a better solution.

Another problem is that the actors are mot imported (this is the case for any NannySpy scenes). I hope you could fix that as well.

**Comment by DirtyRacer1337** [comment]
Fixed
