### ISSUE TITLE
Support for SOCKS4a Proxy?

### ISSUE THREAD

**Issue by quactoo** [PAhelper/PhoenixAdult.bundle#1213]
I would like to get my DNS resolution done at my proxy server with either SOCKS4a or SOCKS5h because of country-wide adult-site block. My proxy service only provide SOCKS4, SOCKS4a, SOCKS5. It does not provide SOCKS5h. Currently PhoenixAdult only supports SOCKS5 and SOCKS5h AFAIK.

It would be great if PhoenixAdult supports SOCKS4a proxy in near future.

**Comment by quactoo** [comment]
I do not need to enter username and password for my proxy server, but some people definitely need to do authentication for their proxy services. If that can be added too, it would be great!

**Comment by DirtyRacer1337** [comment]
Is this help db0f9e6e473862a04b6d31461c6df773299c7ddb?

**Comment by quactoo** [comment]
I am trying to get the proxy work, but I am not technically savvy enough and my government's censorship is too strong.
I might be wrong, but I believe only VPN will be the way in my case.

Thank you so much for your work!
