### ISSUE TITLE
VRLatina

### ISSUE THREAD

**Issue by herbster69** [PAhelper/PhoenixAdult.bundle#1216]
I'm having at issue matching to VRLatina videos.  The video was downloaded from WankzVR but is also available from VRLatina.  I can't get a match using either WankzVR or VR Latina.  Matching using WankzVR does work for non VRLatina videos.   I would prefer to match using WankzVR as there are some slight differences for some movie titles.
match criteria I have tried:

wankzvr - just perfection
wankzvr - just-perfection-5368879
wankzvr - 5368879
vr latina - just-perfection-206.html
vr latina - just perfection

Scene URL:
VRLatina - https://vrlatina.com/video/just-perfection-206.html
WankzVR - https://www.wankzvr.com/vrlatina/just-perfection-5368879

File Name:
WankzVR - vrlatina-just-perfection-180_180x180_3dh_LR.mp4

3. Log File
I'm not sure which log file to use

**Comment by PowerModder** [comment]
The video is from VRLatina. WankzVR just offers their members some access to some content from other sites. If you click the WankzVR link as a free member (not logged in) you get a 404.
A title of:
VRLatina - just-perfection-206
VRLatina - Just Perfection 206
VRLatina - Just Perfection
should work.

**Comment by herbster69** [comment]
Thanks for that - I did need to modify the code to match properly and pull the metadata though
