### ISSUE TITLE
UltraFilms - Incorrect Actors

### ISSUE THREAD

**Issue by Chodbin** [PAhelper/PhoenixAdult.bundle#1217]
Firstly, new here, and thanks for the work on this, amazing stuff!

Some of the actor alias's are not matching up correctly, for example "Vanessa" = Heidi Romanova but is just showing as some much older Vanessa, same with "Clover" (Katya Clover) and some others.

I don't code so I'm only guessing here but is it because there is nothing for UltraFilms in PAdatabaseActors.py?

**Comment by DirtyRacer1337** [comment]
You can add it to `PAdatabaseActors.py`, you don't need to code, just follow the syntax.

**Comment by Chodbin** [comment]
OK,
So in ActorsStudioIndexes I've added 49: ['UltraFilms'], and in ActorsReplaceStudios I've added 49: {  # UltraFilms followed by a bunch of actors. Do i need to add anything into ActorsReplace?

Once I'm finished do i create a fork on GitHub Desktop? drop the file in here?

Thanks in advance

**Comment by DirtyRacer1337** [comment]
> OK,
> So in ActorsStudioIndexes I've added 49: ['UltraFilms'], and in ActorsReplaceStudios I've added 49: { # UltraFilms followed by a > bunch of actors. Do i need to add anything into ActorsReplace?

No if you add it correctly, everything should work

> Once I'm finished do i create a fork on GitHub Desktop? drop the file in here? Do I test it first?
Yes test, then make fork, push changes and create pull request

**Comment by DirtyRacer1337** [comment]
@Chodbin Is this list correct? I can add it if everithing right
```python
'Aleksa Slusarchi': ['Valeria A'],
'Alita Angel': ['Leah Maus'],
'Allegra': ['Alegra'],
'Ally Breelsen': ['Ally'],
'Astrid Herrara': ['Astrid'],
'Bambi Joli': ['Anna Jolie'],
'Barbara Y': ['Jessey'],
'Bysya A': ['Iness'],
'Cayla Lyons': ['Cayla'],
'Clockwork Victoria': ['Victoria C'],
'Connie Carter': ['Connie'],
'Dominic Anna': ['Anna Di'],
'Elin Flame': ['Elin Holm'],
'Elina De Leon': ['Elina De Lion'],
'Elis Gilbert': ['Ester'],
'Emma Brown': ['Ulia'],
'Emylia Argan': ['Nikol'],
'Eveline Neill': ['Eveline'],
'Heidi Romanova': ['Vanessa'],
'Helen H': ['Jackie O'],
'Kattie Gold': ['Janice'],
'Katya Clover': ['Clover'],
'Keira Albina': ['Keira'],
'Kira Zen': ['Kira'],
'Lady Dee': ['Lady D'],
'Leyla Fiore': ['Leila Fiore'],
'Lily Chey': ['Guerlain'],
'Lina Arian Joy': ['Dione'],
'Lolly Small': ['Lika Star'],
'Lovenia Lux': ['Lovenia'],
'Melena Maria Rya': ['Melena Maria', 'Mellena Maria'],
'Merry Pie': ['Maria Pie'],
'Mia Reese': ['Caroline'],
'Nancy Ace': ['Nancy A'],
'Nasty': ['Adele Hotness'],
'Nekane Sweet': ['Nekane'],
'Nelya Smalls': ['Nelya'],
'Noemi Moon': ['Yarina', 'Yarina A'],
'Olivia Devine': ['Olivka'],
'Piper Perri': ['Piper Perry'],
'Red Fox': ['Michelle'],
'Ria Sunn': ['Ria Sun'],
'Sicilia': ['Cecilia'],
'Silvie Deluxe': ['Silvie'],
'Stacy Snake': ['Dasha S'],
'Sybil A': ['Sybil'],
'Taissia Shanti': ['Taisia Shanti'],
'Tetti Dew Korti': ['Hazel'],
'Tyna Gold': ['Tee Nka'],
'Violette Pink': ['Violette'],
```

**Comment by Chodbin** [comment]
Missing
'Haily Sanders': ['Hayli Sanders'],
'Mila Azul': ['Milla Azul'],

but you had a couple i missed :)

**Comment by DirtyRacer1337** [comment]
Added 7474b14476a4ad74634adf2501ebf971a981f9e8
