### ISSUE TITLE
Clips4sale broken?

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#1227]
I am trying to tag this scene: https://www.clips4sale.com/studio/68591/22935891/sensual-desires-4k but I can't get the agent to find it, only getting no matches back.

**Include**
1. Scene URL = https://www.clips4sale.com/studio/68591/22935891/sensual-desires-4k
2. File Name = Clips4Sale - Sensual Desires
3. Log File = [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6129578/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
This should work `Clips4Sale - 68591 - Sensual Desires` or `Clips4Sale - 68591 - 22935891 `

**Comment by insickin** [comment]
Thanks that did the trick!
