### ISSUE TITLE
Crash because of missing ","

### ISSUE THREAD

**Issue by cptn-code** [PAhelper/PhoenixAdult.bundle#1231]
https://github.com/PAhelper/PhoenixAdult.bundle/blob/2c21c63e2751d19b9541f4346d747b5bd7d96f03/Contents/Code/PAsiteList.py#L1591

Since adding the 'hlaf' abbreviation the agent crashes due to the missing "," after the ")"

Thanks for the quick fix! :)

**Comment by DirtyRacer1337** [comment]
Fixed in 4c8a7468adffe556314998597c875b0a1a34d5d7
