### ISSUE TITLE
Strike 3 Network Failing metadata pulls

### ISSUE THREAD

**Issue by dsrtusr88** [PAhelper/PhoenixAdult.bundle#1233]
**Describe the bug**
Some data is coming in like title, date, studio, description.  Actor and artwork aren't working.

**Include**
1. https://www.vixen.com/advantage
2. 'vixen advantage.mp4'
3. Log File
[failedlog.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/6134562/failedlog.txt)

**Comment by v3n0m33526** [comment]
Noticed this as well, seems like the API changed a bit... the cdnUrl in the actor API page is gone
Made a quick fix, not quite sure if this links to the same image it would've done before, don't have an old JSON response on hand, but seems to work fine ;-)

```
for actorLink in actors:
    actorPageURL = PAsearchSites.getSearchSearchURL(siteNum) + '/' + actorLink['slugged']
    actorData = getDatafromAPI(actorPageURL)['model']

    actorName = actorData['name']
    actorPosters = actorData['images']['poster']
    actorPhotoURL = actorPosters[0]['src']
    movieActors.addActor(actorName, actorPhotoURL)
```

**Comment by DirtyRacer1337** [comment]
This should work b9fda4508a357df33f453037c6ecb297f9cbf75f

**Comment by dsrtusr88** [comment]
[failedlog.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/6136706/failedlog.txt)
@DirtyRacer1337  produces this

**Comment by DirtyRacer1337** [comment]
@dsrtusr88 I added check. Try with 9efa8091ec168e3c7fb8660c3d95d5265e5406d9

**Comment by dsrtusr88** [comment]
that did the trick!
