### ISSUE TITLE
PornPros sites not providing cast

### ISSUE THREAD

**Issue by per-plexed** [PAhelper/PhoenixAdult.bundle#1236]
**Describe the bug**
All PornPros scenes, from all sub-sites, are matching but not providing cast. Was working this morning, but now I can't get it to work.

**Include**
1. All pornpros sites
2. [sitename] - [scene-name-with-dashes].mp4
3. [Plex Media Server Logs_2021-03-23_22-04-37.zip](https://github.com/PAhelper/PhoenixAdult.bundle/files/6193836/Plex.Media.Server.Logs_2021-03-23_22-04-37.zip)

**Comment by a18project** [comment]
Works fine for me right now. Btw your logs doesn't have pahelper logs in it.

**Comment by per-plexed** [comment]
Sorry for the delay, attaching real logs now– I'm also having trouble now with Naughty America. Both worked in the past and produce everything except accurate casts. Naughty America will pull in male actors but not female ones, which is especially strange.

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6361179/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Update plugin, it's should be fixed already

**Comment by per-plexed** [comment]
Yup! Thank you!
