### ISSUE TITLE
ATK search does not appear to be working

### ISSUE THREAD

**Issue by mturcich24** [PAhelper/PhoenixAdult.bundle#1237]
I have a few ATK videos on my plex, however when doing a refresh of the metadata nothing gets pulled down even when providing the information about the video on ATK.

When doing a match as well it is not able to find a match of the video.

URL is https://www.atkexotics.com/tour/movie/360041/Esperanza-Del-Horno-rubs-her-clit-to-climax

File Name is ATKExotics.18.05.28.Esperanza.Del.Horno.rubs.her.clit.to.climax.XXX.1080p.MP4.KTR.Pornfuscated.mp4
ATKExotics.20.03.27.Vina.Sky.Masturbation.XXX.1080p.MP4.KTR.mp4
ATKExotics.20.03.27.Vina.Sky.Masturbation.XXX.XviD.iPT.Team.avi
ATKGalleria.14.08.14.Jillian.Janson.And.Lara.Brookes.Lesbian.XXX.1080p.MP4.KTR.mp4
ATKGalleria.17.02.06.Jillian.Janson.Masturbation.XXX.1080p.MP4.KTR.mp4
ATKGalleria.17.02.09.Jillian.Janson.Toys.XXX.1080p.MP4.KTR.mp4
ATKPremium.13.12.23.Jillian.Janson.Amateur.XXX.1080p.MP4.KTR.mp4
ATKHairy.17.12.16.Ariel.Mcgwire.Masturbation.XXX.1080p.MP4.KTR.mp4

**Comment by DirtyRacer1337** [comment]
Not supported site

**Comment by mturcich24** [comment]
According to Issue #1 it says it is:
ATK MEMBERSHIP SITES
ATKingdom.com
ATKHairy.com
ATKGalleria.com
ATKExotics.com
ATKPremium.com
ATKPetites.com
ATKArchives.com

**Comment by DirtyRacer1337** [comment]
It's requests you need [sitelist](https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/sitelist.md)

**Comment by mturcich24** [comment]
Oh I thought that list was sites that were sites that were supported as well. My bad.

**Comment by DirtyRacer1337** [comment]
You can try to use MetadataAPI, if they have that scenes.
Enable using MetadataAPI for unsuccessful search or add MetadataAPI to name

**Comment by mturcich24** [comment]
I have MetadataAPI enabled but it did not pick it up. When you say added MetadataAPI to the name you mean the title name of the video in Plex?

**Comment by DirtyRacer1337** [comment]
I think they don't have that ATK scenes, thats all https://metadataapi.net/sites/atkhairy

`ATKExotics.20.03.27.Vina.Sky.Masturbation.XXX.1080p.MP4.KTR.mp4`
`MetadataAPI ATKExotics.20.03.27.Vina.Sky.Masturbation.XXX.1080p.MP4.KTR.mp4`

boths should work the same, but they don have that scenes

**Comment by mturcich24** [comment]
I was able to get Metadata to pick up some other sites though. I couldn't find how often they update their database.

**Comment by DirtyRacer1337** [comment]
They have discord https://discord.gg/XpSGpaB

**Comment by mturcich24** [comment]
Nice I will join that.
