### ISSUE TITLE
Clips4Sale only returns the first result

### ISSUE THREAD

**Issue by NexPlexSex** [PAhelper/PhoenixAdult.bundle#1239]
Clips4Sale seems to have a TERRIBLE search engine... searching anything that isn't one word sends back results inaccurate results (e.g. searching XYZ takes it in the bum results in all videos with any one of those words in it). Any way to have it so when you do a manual search/fix match in Plex, it returns more than one results? Currently, it only gives me the first result in Plex, which is usually never the correct video, and no other results came back, so I can't pick the correct one.

**Comment by DirtyRacer1337** [comment]
Fixed in 95b4d21ad32b5879a8386cdde0c1b2fb2a6dde82
