### ISSUE TITLE
Don't prefix Milfvr with site name

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#124]
Currently all scenes are named as `MilfVR - Scene Name`. Since they are being put in a collection already, there's no need to prefix each scene name.

**Comment by PAhelper** [comment]
Hopefully this is fixed in 2f4aba5a33ccd585c587a07925598f405513fdec, but I didn't have a chance to test... I just pointed MilfVR searches to the existing WankzVR file, because as far as I can tell they use the same site layout...

**Comment by PAhelper** [comment]
delposible fixed this in the latest updates
