### ISSUE TITLE
Blacked/Deeper/Tushy etc... Matching but not pulling pictures, actors and genre.

### ISSUE THREAD

**Issue by Faerch** [PAhelper/PhoenixAdult.bundle#1252]
When matching a scene from Blacked/Deeper/Tushy etc... it is no longer not pulling pictures, actors and genre.
It still pulls Name, description, date, studio, director and collection.

Is there something wrong with my setup or has the site changed?

I'm using the latest version of the agent and the latest version of the Plex Server.

[com.plexapp.agents.phoenixadult.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/6273860/com.plexapp.agents.phoenixadult.txt)

File: blackedraw.21.03.22.naomi.swann.and.cecilia.lion
Scene: https://www.blackedraw.com/videos/huge-surprise

**Comment by DirtyRacer1337** [comment]
You not on latest, update plugin

**Comment by Faerch** [comment]
Ahh, that did it.

It helped to update the plugin manually.
Apparently the updater in WebTools UAS is not working properly. I had even downloaded the plugin manually before, but I didn't use it, because there were no changes in the Change Log.
