### ISSUE TITLE
bug with vixen blacked and thusy

### ISSUE THREAD

**Issue by romtom70** [PAhelper/PhoenixAdult.bundle#1259]
Hello the videos that come from studio vixen, Blacked, Tushy ect don't look for actors and tags for me. I just have the title and the studio.

**Comment by DirtyRacer1337** [comment]
logs

**Comment by romtom70** [comment]
I do not understand

**Comment by DirtyRacer1337** [comment]
#218, marked as `Please read before submitting an issue`
