### ISSUE TITLE
Expected Behaviour with nested folder structures

### ISSUE THREAD

**Issue by jababda** [PAhelper/PhoenixAdult.bundle#1262]
Not sure if this a bug or a feature but I can't work out the expected behavior.
If I have a folder structure i.e. Brazzers\Brazzers Extra\SceneName.[ext] what should happen?

Playing around with it I think its using the Brazzers Extra as the search term, which seems a bit odd to me.

This is true even if we name the file in the way specifed in the readme. 
So Brazzers Extra\Brazzers Extra - SceneName.[ext] Will still only seems to use Brazzers Extra as the search term/title. Is there a way of either ignoring the parent folder entirely and just using the file name? 

Or could we set it so the Parent folder is always the site name rather then the search term/title?

**Comment by DirtyRacer1337** [comment]
Try with 7b0ee85ef537383aff9a8f478159ae9b5560303f, `Brazzers\Brazzers Extra\SceneName.[ext]` should work
And should be `Exxtra` not `Extra`

**Comment by jababda** [comment]
Applied the update, still no luck. Brazzers\Brazzers Exxtra\SceneName.[ext] is always now matching to Cum Thru 2 on an automatic search regardless on the scene name. On Manual it always return the singular correct one.

**Comment by DirtyRacer1337** [comment]
add logs

**Comment by jababda** [comment]
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6311195/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Are you update plugin, for me `Brazzers\Brazzers Exxtra\SceneName.[ext]` works

**Comment by jababda** [comment]
Yep sorry I must not of overridden the files properly when I applied the update. My Bad :(. Baby Got Boobs\All Grown Up.[ext] is still matching to Teens like it big - All Grown Up on auto search, is that expected?
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6326054/com.plexapp.agents.phoenixadult.log)

**Comment by jababda** [comment]
Similar issue. Sex And Submission\A Warm Gun.[ext] is always matching to Sex And Submission - Sex and Submission.[ext]. Scene is called that as well. 
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6326136/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
I can't reproduce it, but this should help ae283991f69a96267e6f7da2fd5018fd5903be52

**Comment by jababda** [comment]
Still no luck. I've added the logs with both. Could I ask what folder structure your using? Mine are always \studio\site\blah. i.e. Kink\Sex and Submission\scene, or Brazzers\Baby Got boobs\scene. 

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6326422/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
I'm using your example.

For kink it's use correct name right now, just crashed due to site change. Fixed 683bfeb987be7dbfb85dfaefdd97a68b70cc8e9f

I already told you add date for `Baby Got Boobs\All Grown Up.[ext]` or manually choose correct scene

**Comment by jababda** [comment]
Ty. 
And sorry thought that behaviour of matching both was only for the manual search. 
Is this consistant behaviour between limited search sites? Or just Brazzers? Sorry I'm migrating a fairly large collection and just want to identify where I'll need to manually intervene on the imports. 

Would there be broader value in a settings option to filter out results from other sites when a site has been identified? 
If so I'm happy to look at making a PR for it.

In addition I've found any sex and submission\convict rehab 2 is always matching to Sex and Submission\Paige.

**Comment by DirtyRacer1337** [comment]
> In addition I've found any sex and submission\convict rehab 2 is always matching to Sex and Submission\Paige.

Fixed in 39d109d71936522ce6a25bf298fbaca6592d144b, but it have different title, so it's not first.

>And sorry thought that behaviour of matching both was only for the manual search.
Is this consistant behaviour between limited search sites? Or just Brazzers? Sorry I'm migrating a fairly large collection and just want to identify where I'll need to manually intervene on the imports.

Just two different scenes have same title, this rare situation. I improve scoring in 2a6ee194dc7603439d857173d584603d5a38d9c0. Now `Baby Got Boobs\All Grown Up` match correct automatically

**Comment by jababda** [comment]
Yep all seems to be working pretty well now. Still some occasional misses like Hot And Mean\Two-on-One Fun matches to Hands on Hardcore\Two On One Fun, but I think thats more to with dashes rather then the folder structure. 

You might want to check Hot And Mean\The Connor O'Banyon Show as it matches to Hot And Mean\Pot O'Dongs.

You're a champ, keep up the great work!

**Comment by DirtyRacer1337** [comment]
`Hot And Mean\The Connor O'Banyon Show` deleted scene try `Data18Content - 1129375`
`Hot And Mean\Two-on-One` same, date or manual `Hot And Mean - 2013-09-10 - Two-on-One Fun`
