### ISSUE TITLE
Can't install Bundle ?

### ISSUE THREAD

**Issue by NTMP123** [PAhelper/PhoenixAdult.bundle#1263]
Hello all,
I downloaded the plugin and put it on my Windows system with Plex Media Server version 1.22.2 in the plugin folder under : AppData\Local\Plex Media Server\Plug-ins

The folder is called PhoenixAdult.bundle .I first looked to see if the agent can be found in Plex after a reboot unfortunately I can't find Phoenixadult under Agents under PlexMovieLegacy.

If I now download the following clip as an example on NaughtyAmerica and name it according to the following scheme, plex does not find it either: Link : naughtyamerica.com/scene/gia-derza-hates-office-jobs-but-loves-sucking-office-cock-24583

Name of the mp4 file : Naughty America-GIA DERZA HATES...mp4
Now when I click update metadata in plex it finds nothing.

What am I doing wrong what do I need to pay attention to after I put the bundle folder in Plex can someone please help me ?

**Comment by DirtyRacer1337** [comment]
try with `Naughty America - 24583`

**Comment by NTMP123** [comment]
@DirtyRacer1337 Not work I called the file : Naughty America - 24583.mp4 but not work ?
Should i check in plex settings something if the bundle is installed ?

**Comment by DirtyRacer1337** [comment]
Did you set `PhoenixAdult` as agent in library settings?

**Comment by NTMP123** [comment]
@DirtyRacer1337 this is the Problem I don't have the agent available. But I installed it on my plugins folder in windows. Are this bundle available for all windows plex Versions ? Or should I work with another plex Version. 

I have an PhoenixAdult.bundle on my Plug-ins folder the size of the PhoenixAdult folder is 6,89MB

**Comment by NTMP123** [comment]
Fixed. My Problem Sorry. 

Can you please update the README File. Because we need only the Contents Folder in the bundle. Not the other files.

**Comment by DirtyRacer1337** [comment]
@NTMP123 Other files do not affect the plugin work
