### ISSUE TITLE
Metadataapi Requires Account

### ISSUE THREAD

**Issue by extant-squash** [PAhelper/PhoenixAdult.bundle#1268]
Looks like [Metadataapi.net](metadatapi.net) needs an account now. Any help with how to make one?

**Comment by DirtyRacer1337** [comment]
Add token in agent settings

**Comment by insickin** [comment]
They also have a Plex agent now:

https://github.com/ThePornDatabase/ThePornDB.bundle

**Comment by extant-squash** [comment]
Where can I get a token?

**Comment by insickin** [comment]
You log in on https://metadataapi.net an go to https://metadataapi.net/user/api-tokens

**Comment by DirtyRacer1337** [comment]
They not added register button, here it is https://metadataapi.net/register

**Comment by extant-squash** [comment]
Works for me, thanks
