### ISSUE TITLE
jamesdeen.com not pulling all the actors

### ISSUE THREAD

**Issue by Elerako** [PAhelper/PhoenixAdult.bundle#127]
Hi, when matching scene with  fpn network the agent only pull the first two actors that are present on the search page and not those on the scene page.
Thanks for your great work

**Comment by PAhelper** [comment]
Can you post an example of a scene that's not pulling correct actors? Bonus points if you link to the scene's page on jamesdeen.com, and double extra bonus points if you include your log file after trying to match it.

I don't have any scenes from JamesDeen.com specifically, but I have 6 from FPN that all matched just fine, listed the correct actors and found the correct actor photo.

**Comment by Elerako** [comment]
Sure,
The scene is Kate England Incites a Backroom Orgy in Las Vegas Sex Trip Part 2, with this [page](https://jamesdeen.com/trailers/kate-england-incites-a-backroom-orgy-in-las-vegas-sex-trip-part-2.html) and i've put logs in the file attach.
Thanks
[log.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/2950090/log.txt)

**Comment by claygoldfinch** [comment]
Played around with the code for a bit, but was unable to get the plug-in to pull more than two actors for this scene. Added them in manually in PR #219
