### ISSUE TITLE
Adult Empire don't show anything

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1270]
Adult Empire match but don't show anything (actors, Summary, date)

Include

https://www.adultdvdempire.com/553141/best-of-gregory-dark-the-porn-movies.html
Evil Angel - Gregory Dark's Flesh
com.plexapp.agents.phoenixadult.log

**Comment by notme43** [comment]
Still encountering this error on certain films. Tried on latest commit, 6529ec81.

Example:
https://www.adultdvdempire.com/3127417/natural-beauties-vol-14-porn-movies.html

Attached the debug output from the plugin log.
[pa-debug.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6543093/pa-debug.log)

**Comment by DirtyRacer1337** [comment]
Fixed
