### ISSUE TITLE
Nubilefilms not Work ?

### ISSUE THREAD

**Issue by NTMP123** [PAhelper/PhoenixAdult.bundle#1272]
Hello Sir,
I try several times Nubilefilms URL : https://nubilefilms.com/video/watch/126579

I tried : 

Nubilesfilms - 126579.mp4
Nubilefilms - 126579.mp4

Not work any help ?

**Comment by DirtyRacer1337** [comment]
`Nubile Films - 126579` works

**Comment by NTMP123** [comment]
@DirtyRacer1337  fixed thanks
