### ISSUE TITLE
Support for Letsdoeit ?

### ISSUE THREAD

**Issue by NTMP123** [PAhelper/PhoenixAdult.bundle#1273]
Hello Sir,
Are we support : 

https://letsdoeit.com/watch/13242/practice-makes-perfect.en.html ?

**Comment by DirtyRacer1337** [comment]
Yes, it's works `Lets Doe It - Guitar lesson turns into hot sex`
Check [sitelist](https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/sitelist.md)
