### ISSUE TITLE
I didnt understand how to add custom actor

### ISSUE THREAD

**Issue by Dax159** [PAhelper/PhoenixAdult.bundle#1276]
Probably I am dumb (im not an hackorz) but I didnt understand how to add custom actress since I mostly have manyvids videos and its unsupported

**Comment by DirtyRacer1337** [comment]
`Add actorName And actorName2 In Title At Studio`

**Comment by Dax159** [comment]
but where?

**Comment by DirtyRacer1337** [comment]
Filename or Fix Match
