### ISSUE TITLE
21Sextreme not work ?

### ISSUE THREAD

**Issue by NTMP123** [PAhelper/PhoenixAdult.bundle#1277]
Hello Sir,

I try to add : https://www.21sextreme.com/en/video/Lexi--Lucy-/122909 

But this here not work :

21Sextreme - 122909.mp4
21 Sextreme - 22909.mp4

Any help ?

**Comment by DirtyRacer1337** [comment]
It's works, send logs

**Comment by NTMP123** [comment]
I think it worked but i don't get release time and an cover picture.

**Comment by DirtyRacer1337** [comment]
**SEND LOGS**
