### ISSUE TITLE
VIvThomas not work ?

### ISSUE THREAD

**Issue by NTMP123** [PAhelper/PhoenixAdult.bundle#1278]
Hello Sir,

I try the following Video : https://www.vivthomas.com/model/lexi-dona-and-arteya/gallery/20180927/BACKPACKERS

My Sceme  not work ?:

Viv Thomas - BACKPACKERS
VivThomas - BACKPACKERS

**Comment by DirtyRacer1337** [comment]
I cant't open the site, but it's working, your example is gallery

**Comment by NTMP123** [comment]
Solved. I choose gallery instead movie.
