### ISSUE TITLE
Data18-crawler doesn't work

### ISSUE THREAD

**Issue by TheGreatDane2021** [PAhelper/PhoenixAdult.bundle#1279]
I have tried via all documentation to scrape full movies from data18.

I am trying to scrape this movie: http://www.data18.com/movies/137520
And filenames like "Data18 - Boxer - Rocco Siffredi", "Data18 - 137520 - Boxer" and with different compinations of the releasedate of the movie. 
What am I doing wrong?

Is there any way you can update the doc with real world examples of data18-filenaming?

The doc says this now:
Data18 Porn Database | Matching type: Enhanced 
- Content
- Movies

**Comment by DirtyRacer1337** [comment]
Yeah it's should be `Data 18 Content` or `Data 18 Movies`, site list doesn't explain that
