### ISSUE TITLE
Infer Sites from Folder structure

### ISSUE THREAD

**Issue by gollumsluvslave** [PAhelper/PhoenixAdult.bundle#1282]
Not sure if this is an an enhancement, or i've not followed the naming docs properly, but I couldn't see anything where this guy can infer sites from the folder structure?

If i've already got a library in Plex that is structured like Site\SubSite etc, then it would be nice not to have to embed the site in the file name - e.g.

G:\XXXLibrary\Team Skeet\BFFS
G:\XXXLibrary\Team Skeet\Sis Loves Me

Etc etc

If i'm just being dense and have missed this feature then please point me in the right direction!

**Comment by gollumsluvslave** [comment]
> Plex Video Files

Yeah I get the use of the Plex Video Files scanner, the documentation on this metadata agent only mentions FILE naming, there's nothing about folders is all.

Maybe you are saying necause it's the Plex Video Files scanner, it only has the file name to work with and can't infer anything from the folder. If so it's no biggie to script file renames, would just be a nice to have.

**Comment by extant-squash** [comment]
It first checks just the file name to try and figure out the site, if that doesn't work then it looks at the folder it's in ("Sis Loves Me") which should match. You can check the log to see whether it's working
