### ISSUE TITLE
Changing library scanner without messing with matches?

### ISSUE THREAD

**Issue by MrDemous** [PAhelper/PhoenixAdult.bundle#1286]
This is not a bug, it's just a question and I don't know where else to ask it.

I've been using `Plex Video Files Scanner` as my library scanner since PA started ages ago but now I see in the documentation that I should be using `Plex Video Files` for best results.

Is there a way of changing the library scanner without fucking up my old matches and metadata?

**Comment by DirtyRacer1337** [comment]
As I remember, that both works identical, so you probably doesn't need change it, it's only for using directories name in search.

**Comment by MrDemous** [comment]
Cool. Then I don't need to change it since I don't store my videos in separate folders. Thanks @DirtyRacer1337
