### ISSUE TITLE
VirtualRealPorn not matching

### ISSUE THREAD

**Issue by Brak691** [PAhelper/PhoenixAdult.bundle#1296]
**Describe the bug**
Neither auto or manual matching is working for VirtualRealPorn.

It appears they have changed their URL structure. Previously each video could be found at the URL structure:

https://virtualrealporn.com/vr-porn-video/SCENETITLE/
ex: https://virtualrealporn.com/vr-porn-video/best-sex-is-make-up-sex/

but now there is a category in the URL that can't be removed

https://virtualrealporn.com/vr-porn-video/CATEGORY/SCENETITLE/
ex: https://virtualrealporn.com/vr-porn-video/threesome/best-sex-is-make-up-sex/

**Comment by DirtyRacer1337** [comment]
Fixed
