### ISSUE TITLE
JavBus Error

### ISSUE THREAD

**Issue by jababda** [PAhelper/PhoenixAdult.bundle#1300]
There's an update error when using JAVbus.
Scene URL: https://www.javbus.com/en/MIDE-095
File Name: MIDE-095
Logs: [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6564594/com.plexapp.agents.phoenixadult.log)

Also I noticed that its not grabbing the cover art, just all the sample images.

**Comment by DirtyRacer1337** [comment]
can you send `58f8375477ec43edb85225805106ba04.gz` file, it's in `\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.phoenixadult\debug_data`

**Comment by jababda** [comment]
> 
> 
> can you send `58f8375477ec43edb85225805106ba04.gz` file, it's in `\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.phoenixadult\debug_data`

[58f8375477ec43edb85225805106ba04.gz](https://github.com/PAhelper/PhoenixAdult.bundle/files/6565657/58f8375477ec43edb85225805106ba04.gz)

**Comment by DirtyRacer1337** [comment]
Server error in that request, don't know what's wrong. I tested and it's works.

**Comment by jababda** [comment]
Interesting. I'm consistently getting error on any javbus movie. I did notice some connection issues in the logs, but a few IndexError: list index out of range as well. Also it never seems to be pulling the cover art, just the sample images at the bottom of the page. Not sure if thats a bug or not?

I've attached logs for multiple failed updates on MIMK-039, MIDE-095, MIMK-036. Apologies there are some r18 searches in there as well.

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6566410/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Try with db5e77205b2bf5f7e29282576001975951ed0709

**Comment by jababda** [comment]
Legend, Core issue is resolved :) Looking at the logs there's still an odd issue I think with actress images, but thats not a big issue :).
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6573307/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
I don't see any error, everything works

**Comment by jababda** [comment]
Refering to ln 146, 156, 251 and 261. 
I think its a transiant network error?

**Comment by DirtyRacer1337** [comment]
`saveRequest Error`, it's not error, just tried to save unsuccessful requests, it's debug feature.

`Requesting HEAD "/pics/actress/71h_a.jpg"`, this is I missed, fixed now

**Comment by jababda** [comment]
fab, I'll close this one.
