### ISSUE TITLE
Question SceneID Naughtyamerica ?

### ISSUE THREAD

**Issue by NTMP123** [PAhelper/PhoenixAdult.bundle#1304]
Hello,
Unfortunately I have a few scene IDs where I no longer know which video was directly. 

Is there a URL to search for ScenenIDs for example ? As an example I have a failed download scene ID : 26585

Is there a URL to find the video without using the plugin directly ?

**Comment by DirtyRacer1337** [comment]
For you example, `https://www.naughtyamerica.com/scene/026585`
Scene was released today, probably tomorrow it would work

**Comment by NTMP123** [comment]
@DirtyRacer1337  oh very cool you need to add an 0 before the id :) thanks so we can close
