### ISSUE TITLE
Dorcel Vision Errors

### ISSUE THREAD

**Issue by jababda** [PAhelper/PhoenixAdult.bundle#1305]
Dorcel Vision is generating errors and not pulling the studio, actors or cover image correctly.
Oddly it is bring the tagline, studio back as 'x', and adding it the collection 'x' as well as the above issues.

https://www.dorcelvision.com/en/movies/marc-dorcel/russian-institute-lesson-2
"Dorcel Vision\Russian Institute Lesson 02.avi"
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6590126/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Try d67cc9f9831932989bfbce08434db1987950c702

**Comment by jababda** [comment]
still erroring :( 
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6606866/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed

**Comment by jababda** [comment]
Sorry for the late response. Studio is still coming down as 'x'

**Comment by DirtyRacer1337** [comment]
Try on latest

**Comment by jababda** [comment]
Works brilliant :)
