### ISSUE TITLE
 Twisty's Page has changed

### ISSUE THREAD

**Issue by chempke** [PAhelper/PhoenixAdult.bundle#131]
No matching anymore

**Comment by PAhelper** [comment]
Yeah, I noticed this too, but their new search engine doesn't actually work (for me at least). No matter what I search, I get the three Malena Morgan titles + a Tori Black scene, like those results are hardcoded.

I looked into their advanced search too (at the top of https://www.twistys.com/scenes), but that doesn't allow for specific-enough details in the URL to be useful. We're just going to have to wait until they get their stuff together I think...

**Comment by Duglim** [comment]
Hi there, any news on this? The search on twistys.com looks fine from the end user side. Maybe it's possible to bring it to life again? :) 
Thx.

**Comment by claygoldfinch** [comment]
Resolved via sceneID match in PR #225. Read the PR notes if you're having issues.
