### ISSUE TITLE
Fake Female Taxi support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#133]
I see that you don't support Fake Female Taxi (reason: not enough information) But I've found www.femalefaketaxi.com or http://faketaxi1.com (witch seems to have a little bit more info) where info on the scenes is available, can you incorporate this site?

**Comment by claygoldfinch** [comment]
I believe Fake Taxi is part of the FakeHub network (which is currently supported).

**Comment by insickin** [comment]
Yes, Fake Taxi us supported but Fake _**Female**_ Taxi isn't.

**Comment by claygoldfinch** [comment]
Ahh, I gotcha. Site code of www.femalefaketaxi.com seems to be very similar to that of FakeHub, which is promising. I'll take a stab at it.

**Comment by claygoldfinch** [comment]
WIP, moving to Issue #1.
