### ISSUE TITLE
Clips4sale studio search not returning epected results

### ISSUE THREAD

**Issue by jababda** [PAhelper/PhoenixAdult.bundle#1336]
Tricky one here.
it looks like clips4sale doesn't look for exact matches anymore when searching a studio.
When I search 
clips4sale - 51941 - Desperate Maid Gets Blackmailed

I get plenty of results but none that have the scene name. I've repeated test across multiple studios on the clips4sale site as well.
Using a studio filtered advanced search I can at least find it on the bottom with https://www.clips4sale.com/search/clips/studio/51941/n-a/search/desperate%20maid%20gets/sort/best-match/size/48.

the advanced search root is https://www.clips4sale.com/search/clips. 

I'm not sure if this can be fixed given it looks like the c4s search is fundamentally busted it seems but I'd thought I'd log it.

1. Scene URL: https://www.clips4sale.com/studio/51941/12882642/desperate-maid-gets-blackmailed-hd
2. File Name:  Desperate Maid Gets Blackmailed.mp4
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6742024/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
`clips4sale - 51941 - 12882642` will work with f1905355b23cff78f6d852a57409aef7f6a9d6de

**Comment by jababda** [comment]
I'd like to add to the same stripping functionality here as you implemented before.
I can't create a branch or attached the file here, but the code I added to implement the functionality was at ln 17 in siteClips4Sale.py
```
    if Prefs['strip_symbol_reverse'] and Prefs['strip_symbol_reverse'] in sceneTitle:
            sceneTitle = sceneTitle.rsplit(Prefs['strip_symbol_reverse'], 1)[-1]

    parts = sceneTitle.strip().split(' ', 1)
    Log('Parsed sceneTitle: %s' % sceneTitle)
```

**Comment by DirtyRacer1337** [comment]
For what? It's already in

**Comment by jababda** [comment]
To allow for clips4sale - 51941 - SceneName ~ sceneId. 
In my case it allows for studioName ~ clips4Sale - studioId\SceneName ~ sceneId.
Makes everything readable and keeps the folder + file names maintainable.

**Comment by DirtyRacer1337** [comment]
`studioName % clips4Sale - studioId\SceneName % sceneId`?

**Comment by jababda** [comment]
Not sure exactly what the question is. I'm using the Strip Before Symbol ```~```, which is probably where I've confused the point. 
Assuming ```studioName % clips4Sale - studioId\SceneName % sceneId``` is the same as my ``` studioName ~ clips4Sale - studioId\SceneName ~ sceneId``` the current implementation does't handle pulling the scene id from the filename while its in a folder that contains the Strip Before Symbol.

Using ````~``` as the Strip before symbol
```Missa ~ clips4sale - 51941\Desperate Maid Gets Blackmailed (I) ~ 12882642.mp4 ```
Doesn't get the correct match.
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6753848/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
![image](https://user-images.githubusercontent.com/17379553/124261712-4f11b700-db5b-11eb-9524-118a582bd9f7.png)

**Comment by jababda** [comment]
No luck from
For Missa ~ clips4sale - 51941\Desperate Maid Gets Blackmailed (I) ~ 12882642.mp4

Strip After Symbol: ~
Strip Before Symbol: %
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6758214/com.plexapp.agents.phoenixadult.log)

Strip After Symbol: %
Strip Before Symbol: ~
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6758218/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
You not on latest
