### ISSUE TITLE
Hijabhookup not found

### ISSUE THREAD

**Issue by LotusBob** [PAhelper/PhoenixAdult.bundle#1376]
**Describe the bug**
The TeamSkeet site Hijabhookup www.hijabhookup.com does not pull any content or info.

**Include**
1. Scene URL
2. File Name
3. Log File

**Comment by covrdinbeez** [comment]
HijabHookup is not listed as a supported site. It would need to be added as a sub of TeamSkeet to be so. You could try generically using "TeamSkeet" as a site to see if it generically matches. I haven't tried this specifically, but it has worked for me in the past if HijabHookup is one of the sites you can see on the main TeamSkeet page.

Also, if you have the metadataapi fallback search enabled, this will also not work. For some reason, metadataapi has HijabHookup listed as HojabHookups, even though nowhere on the actually site is that trailing "s" listed. I ran into this recently and sent a message to the metadataapi admin to see if it could be changed but haven't heard anything back yet.

**Comment by LotusBob** [comment]
Thank you for this information.  I really appreciate all you are doing
