### ISSUE TITLE
The Life Erotic support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#139]
So I saw that that The Life Erotic was added to the agent, when I was adding my The Life Erotic scenes a few didn't get added right, for example:

https://www.thelifeerotic.com/model/melena-a/movie/20140511/GLISTENING/

The agent finds the scene but doesn't populate the scene page with info.

I've included a log:
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/2984503/com.plexapp.agents.phoenixadult.log)

PS: I saw that you don't update the Change Log/Updates anymore, is there a reason behind that? I found it handy to look what had changed over the last releases.

**Comment by delposibl** [comment]
This should be fixed in the latest version.

**Comment by insickin** [comment]
Jep, all my The Life Erotic scenes are/can be tagged now, thanks!
