### ISSUE TITLE
Missing Pure Taboo art

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#14]
I'm missing the Art of Pure Taboo video's, can thuis be forced?

**Comment by PAhelper** [comment]
I'll look into it, but in the meantime let me suggest vipregirls.to for all your poster/bg image needs

**Comment by PAhelper** [comment]
Turns out this is another site by the same guys as XEmpire / EvilAngel, and they all suffer from the same bug. I have another Issue open for that; I'll add PureTaboo to it.
