### ISSUE TITLE
mypervyfamily not working

### ISSUE THREAD

**Issue by boivinx7** [PAhelper/PhoenixAdult.bundle#1402]
**Describe the bug**
Seems that the search query: https://www.mypervyfamily.com/MemberSceneSearch?q=Leana%20Lovings
Is not getting anything
I would imagine that the site was updated.

**Include**
1. https://www.mypervyfamily.com/en/video/mypervyfamily/But-I-Have-A-Girlfriend-Now/196649
2. MyPervyFamily - 2021.10.28 - Leana Lovings
3. Log File
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/7487563/com.plexapp.agents.phoenixadult.log)

**Comment by stevef9432203** [comment]
Does not work for all tried

**Comment by drraymond27** [comment]
Same here
