### ISSUE TITLE
Jules Jordan not working

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1405]
Jules Jordan no match

**Include**
1. https://www.julesjordan.com/trial/scenes/abella-anderson-the-latin-anal-queen_vids.html
2. Jules Jordan - Abella Anderson The Latin Anal Queen.mp4
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/7504436/com.plexapp.agents.phoenixadult.log)

**Comment by chempke** [comment]
Same over here

**Comment by Dranzer94** [comment]
same

**Comment by stevef9432203** [comment]
Same here

**Comment by a18project** [comment]
#1408

This should fix it.
