### ISSUE TITLE
XConfessions update

### ISSUE THREAD

**Issue by GithubUser538** [PAhelper/PhoenixAdult.bundle#1422]
Hello! It seems it has happened again,the site is not working.
They moved their api to api.xconfessions.com, but are also doing POST requests instead of get
Example:

```bash
curl 'https://api.xconfessions.com/api/search' \
  -H 'authority: api.xconfessions.com' \
  -H 'pragma: no-cache' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'authorization: Bearer TOKENOBFUSCATED' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'sec-gpc: 1' \
  -H 'origin: https://xconfessions.com' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://xconfessions.com/' \
  -H 'accept-language: fr-FR,fr;q=0.9' \
  --data-raw '{"query":"the cooking show"}' \
  --compressed
```

_Originally posted by @GithubUser538 in https://github.com/PAhelper/PhoenixAdult.bundle/issues/857#issuecomment-988276328_ for @DirtyRacer1337

**Comment by DirtyRacer1337** [comment]
Try this 9e1c1b2ed860488cfae7ae6c76d13f6e9a20d37d

**Comment by dunderwood201** [comment]
Unfortunately this doesn't seem to be working correctly with the change? I may try giving a wild stab at figuring out how to change it from a GET to a POST, but I figured I'd report this as well in case someone here can address it better than I can.
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/7794740/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
It's already make `POST` requests, try this 18e032049cf242e201e8aaaa6d6c328c2ae0dc09

**Comment by dunderwood201** [comment]
That looks like it works! Thank you!
