### ISSUE TITLE
Data18.com new version no match

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1423]
Data18.com have new version that not match

**Include**
1. [Scene URL](https://www.data18.com/scenes/3115847)
2. HotWifeXXX - Maya Is The Gift That Keeps On Giving.mp4
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/7724518/com.plexapp.agents.phoenixadult.log)

**Comment by Dranzer94** [comment]
same

**Comment by Spanishu** [comment]
would be really awesome to get this back to work !
