### ISSUE TITLE
Cannot match JulesJordan Scene

### ISSUE THREAD

**Issue by Dranzer94** [PAhelper/PhoenixAdult.bundle#1431]
Hi,

I'm trying to match a particular scene: https://www.julesjordan.com/trial/scenes/Gianna-Nicole-Anal-Big-Dick_vids.html 

None of the main search terms work on JulesJordan's website either so I think that's the problem

Does anyone know how I could match this scene?

Thanks

**Comment by covrdinbeez** [comment]
Without a clipping from your log, there's not much anyone's going to be able to help you with, as to whether it's something you're doing or on the site's side.

If you can't find it on the site's search, then yeah, that might be the problem and no one here can help with that. You might want to contact the site.

If you don't want to go that route, I see the scene exists at metadataapi.net (ThePornDB): https://metadataapi.net/scenes/jules-jordan-gianna-nicole-takes-a-big-cock-in-her-ass

If you have metadataapi set for backup searches, you should be able to match it there.

**Comment by Dranzer94** [comment]
How do I set metadata api for backup searches?

**Comment by Dranzer94** [comment]
sorted it, thanks for your help!
