### ISSUE TITLE
NaughtyAmerica not returning any results

### ISSUE THREAD

**Issue by Brak691** [PAhelper/PhoenixAdult.bundle#1455]
**Describe the bug**
NaughtyAmerica no longer seems to be matching. Auto as well as manual matching do not return any results. It appears that the algolia api is not returning any results. Seems like this started happening around the first week of 2022

**Include**
1. All scenes appear to not be matching
2. The attached log was trying to match the file named: nam-30802
3. Log File: [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/7830446/com.plexapp.agents.phoenixadult.log)

**Comment by pedrolara-boop** [comment]
Same here

**Comment by ConstrictM** [comment]
It looks like the indexName for results may have changed? I'm having issues identifying the new index name. Hope this helps to solve issue.

I find results with nacms_scenes_match_production instead of nacms_scenes_production, but the results do not return anything newer than 2018.

**Comment by ConstrictM** [comment]
Found the right index: nacms_combined_production
