### ISSUE TITLE
Update for networkKink.py - Fix Genre Tags

### ISSUE THREAD

**Issue by macr0dev** [PAhelper/PhoenixAdult.bundle#146]
Please update line 109 in networkKink.py to the following for genre tags to populate properly.  Looks like they changed the site code a little bit

` genres = detailsPageElements.xpath('//p[@class="tag-list" and contains(text(),"categories:")]/a')`

**Comment by PAhelper** [comment]
Updated in 24cc32f752dbb98fcabfe83febb2bf2de2b4b753
