### ISSUE TITLE
Black posters after metadata refresh

### ISSUE THREAD

**Issue by woodbridgesub** [PAhelper/PhoenixAdult.bundle#148]
This may not be an issue specific to this agent, so apologies in advance for that.

I have often noticed that after posters are downloaded, they will work for a few hours, but after that time period, if a new poster is selected for a scene, it updates with a completely black poster. I don't use any other 3rd party agents, so I've only noticed it with PA.

I updated to your recent build where you worked on Blacked/Vixen/Tushy/etc sites and this morning set those collections to refresh all metadata. After a few hours, I confirmed that all metadata was refreshed as it did download the expected additional images for each scene. I changed the posters for a few scenes just as a test, and it worked perfectly. Several hours later I tried to change the posters for a few more scenes, but each of them now shows a black poster even though the additional images that were downloaded earlier are still visible in the poster and background images sections. I then tried to change the posters for the same scenes I had changed earlier, and they're showing up as black posters now as well.

The thing is, I noticed this behavior several months ago as well, when I first began using this plugin - but at that time, I assumed it was either an end-user issue or the host website itself was doing something funny. One thing that I did notice is that this seems to be an issue only with the Lansky sites - JulesJordan, DarkX, etc are all able to load the posters that were downloaded prior to today's refresh.

I've searched for this issue online and the only similar issue was resolved when a user disabled MoviePosterDB from their Agents list, which doesn't seem to apply here.

So the questions is: Could the code for the Lansky sites have something that might be causing this issue?

Thanks for your help!

**Comment by PAhelper** [comment]
Yes. I have two thoughts on what might be happening. One: if you had the file matched before the recent site redesigns (and thus had the art from the old site) that could be messing with the new art. Two: there's code in that file, and a few others, that I believe is meant to clear the artwork and start over on each refresh, but I'm not sure it works the way we think.

You can test/fix scenario one by doing a Fix Match instead of a Refresh Metadata. I'll have to make some changes to the code for scenario two.

**Comment by woodbridgesub** [comment]
Thanks for the quick reply. I tried Fix Match as you suggested, but the results are the same - several hours later, any poster (except for usually the first two) that was not used previously returns as a black poster.

One thing I did not do is the Plex dance followed by what you suggested. Do you think that might make a difference?

**Comment by PAhelper** [comment]
It might. I don't know enough about how artwork is stored/referenced in the database to say for sure. Can't hurt to try one or two though!

**Comment by woodbridgesub** [comment]
Unfortunately no luck with that either. Please take your time, I'll wait for option 2 as you suggested above, hopefully that will resolve this issue.

Two side questions:
1)Is this bug/issue happening for you (or other users) as well?
2)Is anyone aware of any plugins that might allow me to move the downloaded metadata locally so that it doesn't need to be refreshed multiple times?

Thanks!

**Comment by c1ockwork** [comment]
This was an issue for me with Lansky sites too.  A Metadata refresh didn't seem to help, nor did doing any of the various Plex dances (optimize database, etc.).  Yesterday evening I decided to refresh metadata on the effected entries (pretty much all of them) and it now seems to be good (and staying good).  There have been some Plex server updates in the mix, plus a few updates to PABundle (thanks for your great work PAHelper!) - not sure if that has anything to do with it now working.  Woodbridgesub, perhaps give it another try now....

**Comment by woodbridgesub** [comment]
@c1ockwork Thanks for the tip! I did do a refresh metadata on one scene yesterday, for a few hours I was able to change the posters around, but I checked this morning and now a black poster appears for most posters. I'm using the latest revision of the agent and my server is updated as well, so I'm not sure what I might be doing wrong. Can I ask specifically how you refreshed your metadata? Did you refresh the entire library, or did you refresh just the scene, or did you go into the scene and then refresh from there? I doubt this makes a difference, however since you've had success I'd love to figure out what's causing this.
As a side note, I recently re-installed my Plex server (after a full reinstall of Windows) hoping it might fix something, but no such luck there either. But at least it rules out cached data as the cause.

**Comment by c1ockwork** [comment]
Sorry for the delay in responding @woodbridgesub, it seems I spoke too soon.  I got longer out of this metadata refresh than I had before so I was psyched at the thought of the issue having resolved itself, but I'm back to black squares again for Lansky sites.  It was a scene by scene refresh.  At the very least I'm pleased to confirm you not alone with the issue (and vise-versa), and good work with ruling out the Plex reinstall.  I'm happy to assist with the troubleshooting if the dev's have any suggestions - there's the 2 of us now so something's going on.  :-)

**Comment by woodbridgesub** [comment]
@c1ockwork No problem at all, I'm glad you replied! Sorry for the continuing troubles, but it's nice to not be alone :D 
@PAhelper is pretty clever, I'm sure he's got something brewing to resolve this issue. It's just a matter of time.

**Comment by woodbridgesub** [comment]
@PAhelper @claygoldfinch wanted to just check back to see if you (or anyone else) had any further insight into this problem?

**Comment by claygoldfinch** [comment]
Haven't experienced this, or had a chance to look into it yet. It's on the to-do list, though.

**Comment by d2dyno** [comment]
This seems to be a Plex issue FYI. I experience this often, unfortunately. If you restart PMS, it will no longer do this when changing art. The downside is, you have to flush cache, change image for scenes with black poster, then change back to the poster you wanted. For this reason, it's usually best to restart PMS before working on metadata for matched scenes.

**Comment by d2dyno** [comment]
```
Jul 25, 2019 21:05:01.650 [0x153cee1f2700] ERROR - Error issuing curl_easy_perform(handle): 28
Jul 25, 2019 21:05:03.162 [0x153ced554700] ERROR - Unknown metadata type: 
Jul 25, 2019 21:05:11.895 [0x153cb25f2700] ERROR - Error resizing an image, we don't trust what we cached [/config/Library/Application Support/Plex Media Server/Cache/PhotoTranscoder/1f/1fdf697657c3d871dd5e028b166dc9081bb8cc4c.jpg]
Jul 25, 2019 21:05:20.386 [0x153cb23f1700] ERROR - Error bringing media local (metadata://posters/com.plexapp.agents.phoenixadult_df422e8ca3075846e17929ce2634aa5bf6a837f6).
Jul 25, 2019 21:05:26.730 [0x153cb03e1700] ERROR - Error issuing curl_easy_perform(handle): 28
Jul 25, 2019 21:05:39.839 [0x153cb03e1700] ERROR - Error bringing media local (metadata://posters/com.plexapp.agents.phoenixadult_b338eb9addb3545127dd88d5c9a5193a1888b6a8).
Jul 25, 2019 21:05:42.882 [0x153ceebf7700] WARN - JobManager: Could not find job for handle 517
Jul 25, 2019 21:05:54.541 [0x153c83dfe700] ERROR - Error bringing media local (metadata://posters/com.plexapp.agents.phoenixadult_6f5e85fce9580fae549b057bde23d5a12090aca9).
Jul 25, 2019 21:05:54.631 [0x153cb1bed700] ERROR - Error bringing media local (metadata://art/com.plexapp.agents.phoenixadult_bf34a7ef8e0d649cecd3c661c2dcb4c0b3c9e015).
Jul 25, 2019 21:06:07.831 [0x153ceebf7700] WARN - JobManager: Could not find job for handle 443
```

This just happened to me and I thought to grab logs from the main `Plex Media Server.log`
