### ISSUE TITLE
Merge Actress

### ISSUE THREAD

**Issue by claygoldfinch** [PAhelper/PhoenixAdult.bundle#149]
I've noticed that PornPros sites (specifically POVD and Tiny4k) list actress "Rebel Lynn" as "Rebel Lynn (Contract Star)". Was wondering if there was any way these could be merged.

**Comment by PAhelper** [comment]
Yes. I built a system for exactly this situation. I'll get this added (probably) today. Stay tuned!

**Comment by PAhelper** [comment]
Added in 26d4ea8

**Comment by claygoldfinch** [comment]
Thanks for the quick reply! Issue doesn't seem to be resolved, however.

1. Updated agent
2. Metadata Refresh
3. Unmatch/Re-match
4. Plex Server reboot, followed by steps 2&3 once more.

Plex is still displaying "Rebel Lynn (Contract Star)" instead of "Rebel Lynn."

**Comment by PAhelper** [comment]
Alright, I'm downloading both of these scenes to test...
