### ISSUE TITLE
NetworkR18 Not Retrieving Result

### ISSUE THREAD

**Issue by ZwarMachine** [PAhelper/PhoenixAdult.bundle#1497]
NetworkR18 is not retrieving search result since 3 days ago. Can you please check if there is any issue connecting to R18.com?

E.g. JAV KATU 094

From log it says response 200 but there is nothing retrieve back

**Comment by monkTertman** [comment]
Yea, looks like some kind of URL parsing is set up by R18.

The agent is hitting URL `https://www.r18.com/common/search/searchword=Ebod%2B113` which results in a 404 page.
But adding a forward slash seems to open the search correctly `https://www.r18.com/common/search/searchword=Ebod%2B113/`
Looks like an easy fix, if anyone wants to take this issue up.

**Comment by ZwarMachine** [comment]
thanks! I have created a pull request under #1498
