### ISSUE TITLE
Data18 no Actors

### ISSUE THREAD

**Issue by chempke** [PAhelper/PhoenixAdult.bundle#1523]
**Data18 no Actors**
no more actor information will be added 

**e.g.**
1. Gracie Glam in My Stepfather Made Me 3
2. data18scenes - 4167112
3. [Log File](https://github.com/PAhelper/PhoenixAdult.bundle/files/8186221/com.plexapp.agents.phoenixadult.log)

**Comment by pibi73** [comment]
Same problem here.... :(
