### ISSUE TITLE
Net Video Girls not matching with anything

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1541]
Net Video Girls not matching with anything. Try Scene ID, Name Actors, Date, nothing work

**Include**
1. The site not shows URL until you pay, I searched the info on Google
2. Net Video Girls 749 - Bella, Mara
    Net Video Girls 2161 -  Angelina 
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/8350703/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Mine fault, try with this 1280aeccefacd965d686d91c763e3b8c3417cdf7

**Comment by ConstrictM** [comment]
@drraymond27 When adding multiple actors put "AND" between them

**Comment by drraymond27** [comment]
OK, now work with Scene ID (in IAFD You can search they ID) but now, don't show actors
