### ISSUE TITLE
All Anal no show actors yet

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1556]
**Describe the bug**
The actors still not shows

**Include**
[Scene URL](https://tour.allanal.com/scenes/up-the-ass-for-bailey-lana)
AllAnal - Up The Ass For Bailey & Lana
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/8554696/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Mine fault, should help 5cc6031c9818c2f16762236abfb93ee17ed1124b
