### ISSUE TITLE
Google Search not picking up results

### ISSUE THREAD

**Issue by durmonator** [PAhelper/PhoenixAdult.bundle#1559]
When I try and match with google search (I have tried two different servers, one local, one in the "cloud") they don't seem to work when trying to get matches from google, I have tried multiple sites and none are working
[com.plexapp.agents.phoenixadult-site1.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/8604880/com.plexapp.agents.phoenixadult-site1.txt)
[com.plexapp.agents.phoenixadult-site2.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/8604881/com.plexapp.agents.phoenixadult-site2.txt)

**Comment by durmonator** [comment]
I fixed this issue, on line 228 of PAutils I added the fixed_useragent call inside of getUserAgent and this has now fixed the issue for me and google search is working again

**Comment by DirtyRacer1337** [comment]
Added ac9549ee26c88b22dbfa57b1d937187b0fd4d719
