### ISSUE TITLE
Data 18 not working since update

### ISSUE THREAD

**Issue by Dranzer94** [PAhelper/PhoenixAdult.bundle#1583]
Did a few tests with it and it appears since Data 18 got updated, Phoenix no longer works with it

Could someone implement a patch please to get it working again?

**Comment by chempke** [comment]
What exactly doesn't work for you? 

For me the plugin works without any problems. Only issue posters and fanarts are sometimes loaded from wrong scenes.

**Comment by LotusBob** [comment]
for me Data18 has not worked since they did a update.  I put in the scene id and get nothing found

**Comment by LotusBob** [comment]
what version of the plug in are you using?
