### ISSUE TITLE
Titles/files with '4K' will not match

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#162]
Any title or file with 4k at the end of the name, will not match. For example, "Analized 17 12 15 Daphne Klyde and Kristy Black Tag Team a Huge Cock 4k" will immediately return no results. But removing '4k' will return the exact result.

**Comment by woodbridgesub** [comment]
I believe the issue is not with the '4K' text rather the problem is with the multiple artists in the filename. To correct it, try removing 'and Kristy Black' and see if it matches.

**Comment by d2dyno** [comment]
@woodbridgesub thanks for the tip in your edit :) Added that in my local instance and it resolves the issue, so I made a PR with it :)
