### ISSUE TITLE
Teamskeet wouldn't match using scene name, and no metadata returned after matching with video api id

### ISSUE THREAD

**Issue by kkycble** [PAhelper/PhoenixAdult.bundle#1628]
Video URL: https://www.teamskeet.com/movies/gamer-girl-skills-tested

I can only match the video with the string "Teamskeet - 15353"

![螢幕截圖 2022-10-08 23 05 16](https://user-images.githubusercontent.com/21995214/194714107-376d633d-155d-435c-9a39-c03e43bcc833.png)

However, the metadata update would fail.

**Comment by NedVargar** [comment]
I've noticed problems with that as well.  I don't know a fix.  Sometimes it will match if I manually try it 3 or 4 times.  Same with the MetaData if I choose Refresh MetaData a few times.

**Comment by diamondpete** [comment]
The site sometimes presents http request with a captcha when rapidly querying their site. There are multiple web queries in the TeamSkeet update and all of these have to succeed for the match to complete.

As @NedVargar stated refreshing multiple times should match eventually.
