### ISSUE TITLE
ThatSitcomShow not matching

### ISSUE THREAD

**Issue by chempke** [PAhelper/PhoenixAdult.bundle#167]
Tryed to match this scene https://thatsitcomshow.com/video/watch/64188 with id 64188 with no results. The Log file shows Requesting 'https://thatsitcomporn.com/video/watch/64188' and gives Index Error.

Maybe requesting thatsitcom**show**.com instead of porn should fix this.

**Comment by claygoldfinch** [comment]
@chempke Just tested out your fix with several files and it seems to be working for me. You run into any issues on your fork?

**Comment by chempke** [comment]
It works for me too, but please ignore my fork. I accidentally put it on and have no idea about it. Feel free to commit a fix for this, because i have no clue how to do it.
