### ISSUE TITLE
Naughty America seems to be broken

### ISSUE THREAD

**Issue by OGustavo29** [PAhelper/PhoenixAdult.bundle#168]
I add a couple of new videos from Naughty America and even tough the results are correct in the search, poster, banner and synopsis are still blank after the match.

Like this Elena Koshka & Alex Legend in Neighbor Affair [NA] 2018-01-30

**Comment by claygoldfinch** [comment]
Looks to be a minor site change and an easy fix. Just submitted a pull request.

**Comment by OGustavo29** [comment]
Thx for quick fix
