### ISSUE TITLE
Vixen Network Broken (Vixen, Tushy, TushyRaw, Blacked, BlackedRaw, Deeper, Slayed)

### ISSUE THREAD

**Issue by r3arsh** [PAhelper/PhoenixAdult.bundle#1689]
Entire Vixen Network (Vixen, Tushy, TushyRaw, Blacked, BlackedRaw, Deeper, Slayed) is now broken as of 1/27/2023. Nothing matches anymore for these sites.

**Comment by wuyuzheyan** [comment]
yes，the Vixen Network broken ，i could not match anyting

**Comment by drraymond27** [comment]
https://www.blacked.com/videos/give-it-all
BLACKED - Give It All.mp4
[Plex Media Server.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/10542999/Plex.Media.Server.log)

**Comment by r3arsh** [comment]
seems to be taking a different search call now... maybe '/search?q=' instead of '/graphql?query='

when using '/search?q=' it works with actors and scene name but doesn't work with scene id

**Comment by kkycble** [comment]
sad to report that I've been having this problem as well :( No results were returned for both vixen and tushy.

**Comment by captaincoitus** [comment]
Broken for me as well. Can't search Blacked, BlackedRaw, Tushy, TushyRaw

**Comment by captaincoitus** [comment]
> seems to be taking a different search call now... maybe '/search?q=' instead of '/graphql?query='
> 
> when using '/search?q=' it works with actors and scene name but doesn't work with scene id

How do you chance the search URL to '/search?q=' from '/graphql?query='?

**Comment by diamondpete** [comment]
Needs to be rewritten. The current scraper attempts to query their GraphQL, but now non-whitelisted IPs are being blocked from running queries. Could be rewritten to do xpaths instead of json. Someone just needs to take the time to do it.

**Comment by diamondpete** [comment]
The best I could do was use the '/search?q='. Categories and High Res Images may no populate

**Comment by r3arsh** [comment]
Slayed is still calling the old search API. Please fix to use '/search?q='.
Thx.

1357: ('Slayed', 'https://www.slayed.com', '/api'),

**Comment by captaincoitus** [comment]
Do I have to redownload the PAHelper the plugin for the change or it will auto-update?
