### ISSUE TITLE
NewSensations posters not propagating correctly

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#172]
Currently, newsensations has an issue where preview images are added correctly to the metadata.art, but not metadata.posters. I thought the issue might be with syntax on https://github.com/PAhelper/PhoenixAdult.bundle/blob/41071dc0157b2a28e0abb0349f75a2d1eb39f0a7/Contents/Code/siteNewSensations.py#L125 but even after correcting that images in background don't show up in poster.

**Comment by claygoldfinch** [comment]
I'm going to close this and combine it with #104. NewSensations has never worked for me, I think it's past time for an overhaul.
