### ISSUE TITLE
Manual Add with Date is adding the date to the scene name

### ISSUE THREAD

**Issue by Leinaria** [PAhelper/PhoenixAdult.bundle#1726]
Using the following code:
`Add Date Actress And Actress In Scene`
results in the title being set to "Scene [] Date"

For example:
`Add 2023-01-16 Emma Sirus and Kimmy Kimm in My Best Friends Crush`
results in a the title set to "My Best Friends Crush [] 2023-01-16" instead of adding the date to the date field.

**Comment by diamondpete** [comment]
You're not using the latest plugin code. #1704 Fixed this issue.

**Comment by Leinaria** [comment]
I was using the plugin code from Feb 9th, which is the day after #1704 was added. But I'll download the latest and test again.
