### ISSUE TITLE
Little Caprice matches but don't show any Info

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1737]
**Describe the bug**
Little Caprice matches but don't show any Info

**Include**
1. [Scene URL](https://www.littlecaprice-dreams.com/project/nasstyx-convincing-friend-to-cheat/)
2. LittleCaprice - Sky Pierce And Little Caprice Nasstyx
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/10834416/com.plexapp.agents.phoenixadult.log)

**Comment by freeloaderfreddie** [comment]
This should be fixed in #1745
