### ISSUE TITLE
Change BadonikVR - Title behavior

### ISSUE THREAD

**Issue by ferengi82** [PAhelper/PhoenixAdult.bundle#174]
hi,

didn't no if someone ready comments in closed issues ...
=>

if i open the link https://badoinkvr.com/vrpornvideo/break_up_sex/ in my browser, i get forwarded to https://badoinkvr.com/vrpornvideo/break_up_sex-323633/.
Is there any chance to implement this forwarding in the code?
Otherwise i have to rename all of my files from hand.

_Originally posted by @ferengi82 in https://github.com/PAhelper/PhoenixAdult.bundle/issues/75#issuecomment-487405271_

**Comment by SgtBatten** [comment]
Does every scene do this?

For sites where you need an exact url and some scenes do this you just need to add the number to your media title.

**Comment by ferengi82** [comment]
almost, without de exact url 90-95% don't work

**Comment by ferengi82** [comment]
i looked into this a litte bit more, Badoinkvr (and the other network sites) changed their search urls.
Im trying to fix it my self in a few days

**Comment by ferengi82** [comment]
to late, delpoibl fixed it in https://github.com/PAhelper/PhoenixAdult.bundle/pull/239, thanks
