### ISSUE TITLE
anyone with problems with Data18

### ISSUE THREAD

**Issue by pibi73** [PAhelper/PhoenixAdult.bundle#1751]
hi guys...

Has anyone encountered problems using the agent with data18 in the last 2 weeks?
with Data19scenes - xxxxx i don't find nothing and everything worked perfectly until 15 days ago.

Thanks.

**Comment by freeloaderfreddie** [comment]
Its working fine for me. There was an issue with Data18 (#1583) which I fixed a few days ago, did you update recently?

**Comment by pibi73** [comment]
yeah..with the last version it's all ok.

thanks a lot !
