### ISSUE TITLE
X-Art matching sets no Collection Tag

### ISSUE THREAD

**Issue by Duglim** [PAhelper/PhoenixAdult.bundle#179]
When matching X-Art Clips, no Collection Tag is set. Can you tell me, how to fix this?

Many clips also dont have a proper Cover Artwork, just a black image. I looked at x-art.com and found that for many scenes there are also photo galleries, which have a much nicer Artwork. Does the agent look for both?

Thx, Duglim

**Comment by Duglim** [comment]
Should I add something like:

```
metadata.collections.clear()
metadata.collections.add("X-Art")
```

into the x-art code?

**Comment by claygoldfinch** [comment]
Just submitted a Pull Request for the Collections issue.

**Comment by Sinjin69** [comment]
I'm going to close this because #181 was merged.
