### ISSUE TITLE
Bangbros not working

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1804]
**Describe the bug**
Bangbros not match at all

**Include**
1. [Scene URL](https://bangbros.com/video/8843611/hot-neighbor-obsession)
2. Bangbros - Hot Neighbor Obsession.mp4
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/11957589/com.plexapp.agents.phoenixadult.log)

**Comment by stevef9432203** [comment]
I can confirm Bangbros and  subsites non-functional as of july 4 pst

**Comment by stevef9432203** [comment]
Thanks now if one could figure out how Score Group broke thier web site(s)
