### ISSUE TITLE
Culioneros not working

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#1813]
**Describe the bug**
Culioneros not working

**Include**
1. https://culioneros.com/
2. Culioneros - standing rump and ready
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/12032578/com.plexapp.agents.phoenixadult.log)

**Comment by diamondpete** [comment]
Looks like an update has made the site no longer scrapable. There is no scene information.
