### ISSUE TITLE
Analvids new site structure

### ISSUE THREAD

**Issue by Kep-sensei** [PAhelper/PhoenixAdult.bundle#1825]
**Describe the bug**
No Result bug.

The web site structure is changed, now is:
https://www.analvids.com/watch/476830/3_hours_non_stop_roasting_a_skinny_teen_sasha_paige_bukkake_ending

File name:
Analvids - 2023-08-01 - 476830.mp4

**Comment by a18project** [comment]
Submitted: #1827
