### ISSUE TITLE
PervMom not pulling metadata

### ISSUE THREAD

**Issue by xmxier** [PAhelper/PhoenixAdult.bundle#184]
PervMom not pulling metadata???

**Comment by xmxier** [comment]
PervMom - Courtney Taylor - Laid After The Panty Raid
PervMom - Brooke Beretta - Titty Fucking Talent

**Comment by claygoldfinch** [comment]
PervMom is direct url match only.

To get Laid After The Panty Raid to match, you'll have to search for:
Pervmom - /1007/laid-after-the-panty-raid/courtney-taylor-part-1

To get Titty Fucking Talent to match, you'll have to search for:
Pervmom - /1013/titty-fucking-talent/brooke-beretta-part-1
