### ISSUE TITLE
DDFNetwork support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#185]
I'm trying to match a few DDFNetwork scenes but can't get the agent to find them, it keeps coming back with: No results found. I've tried scene names and actress name, am I doing something wrong or is it something with the agent (DDFNetwork is supported)

2 examples:
Sinnsational Discovery - Sinn Sage
https://ddfnetwork.com/videos/sinnsational+discovery/18696
I've tried:
DDFNetwork - Sinnsational Discovery
DDFNetwork - Sinn Sage

Simply Sinnful - Sinn Sage
https://ddfnetwork.com/videos/simply+sinnful/18697
DDFNetwork - Simply Sinnful
DDFNetwork - Sinn Sage
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3167254/com.plexapp.agents.phoenixadult.log)

**Comment by claygoldfinch** [comment]
Looks like the search page has changed (so the code pulling title, date, etc, plus poster art no longer works). Can probably fix this over the weekend.

**Comment by dxm2891** [comment]
Until the next release I made changes to file networkDDFNetwork.py

From line 4 to 25:
`def search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate,searchSiteID):
    if searchSiteID != 9999:
        siteNum = searchSiteID
    searchResults = HTML.ElementFromURL(PAsearchSites.getSearchSearchURL(siteNum) + encodedTitle)
    i = 0
    for searchResult in searchResults.xpath('//div[@class="card text-white bg-dark m-1"]/a'):
        Log('Url : ' + str(searchResult.get('href')))
        titleNoFormatting = searchResult.get("title")
        Log('Titre ' + str(titleNoFormatting))
        releaseDate = parse(searchResult.xpath('//div[@class="d-flex p-0 m-0 lh-1 pb-1"]//small')[i].text_content().strip()).strftime('%Y-%m-%d')
        #coverURL = searchResults.xpath('//div[@class="card m-1"]/a/img')[i].get('data-src')
        #Log('CoverUrl : ' + str(coverURL) )
        curID = searchResult.get('href').replace('/','_').replace('?','!')
        Log('CurID : ' + curID )
        if searchDate:
            score = 100 - Util.LevenshteinDistance(searchDate, releaseDate)
        else:
            score = 100 - Util.LevenshteinDistance(searchTitle.lower(), titleNoFormatting.lower())

        results.Append(MetadataSearchResult(id = curID + "|" + str(siteNum) + "|" + str(i) + "|" + str(encodedTitle) , name = titleNoFormatting + " [DDFNetwork] " + releaseDate , score = score, lang = lang ))
        i = i + 1
    return results`

Line 38-39:
`    for searchcover in searchcovers.xpath('//div[@class="card text-white bg-dark m-1"]/a') :
        coverURL = searchcover.xpath('//div[@class="card text-white bg-dark m-1"]/a/img')[k].get('data-src')`

**Comment by claygoldfinch** [comment]
Nice work, @dxm2891! Tested out your code with several scenes, and it appears search is fixed!

I added a bit of code myself, as I was running into issues with the client pulling Simply Sinnful's summary. It appears as though that page, in particular, is set up differently than the majority of their pages. This should fix it:

    try:
        summaryp1 = detailsPageElements.xpath('//div[@id="descriptionBox"]/p[2]')[0].text_content().strip()
        summaryp2 = detailsPageElements.xpath('//div[@id="descriptionBox"]/p[3]')[0].text_content().strip()
        summaryp3 = detailsPageElements.xpath('//div[@id="descriptionBox"]/p[3]')[0].text_content().strip()
        summary = summaryp1 + '\n' + summaryp2 + '\n' + summaryp3
    except:
        summary = detailsPageElements.xpath('//p[@class="box-container"]')[0].text_content().strip()
    metadata.summary = summary


It looks as though scene posters still aren't being pulled, as well.

**Comment by dxm2891** [comment]
@insickin this issue was fixed with PR #194

**Comment by r0x0r316** [comment]
could we please agree that either dxm or clagoldfinch do developing in there repos but both atleast in one so we can have both your fixes? :D kinda hard to decide whom to pick ;)

**Comment by claygoldfinch** [comment]
> could we please agree that either dxm or clagoldfinch do developing in there repos but both atleast in one so we can have both your fixes? :D kinda hard to decide whom to pick ;)

@dxm2891 incorporated my code into his fix, so should feel free to download his repo if you're having issues with this site! Both of us have active pull requests to merge our updates into this repo, just waiting on @PAhelper to approve them! More discussion about that here: #195

**Comment by r0x0r316** [comment]
Yeah but you have a genre fix which is not in dxms repo aswell as some other fixes ;) so its kinda hard to decide which one to take. i like both your commits :)

**Comment by dxm2891** [comment]
@claygoldfinch would you like to merge your build into mine so we create only one version to download as long as @PAhelper approve all?

**Comment by claygoldfinch** [comment]
@dxm2891 works for me! PR submitted.

**Comment by dxm2891** [comment]
Thanks @claygoldfinch !! PR merged

**Comment by Sinjin69** [comment]
@dxm2891 we should probably get this one and your fork back in sync. Maybe do a PR with all the changes. So we can get these issues closed out.

**Comment by Sinjin69** [comment]
@dxm2891 Was this fixed in #194? Can we close this issue?

**Comment by claygoldfinch** [comment]
> @dxm2891 Was this fixed in #194? Can we close this issue?

Yep, this was resolved in #194. 

I believe the rest of the differences between this and @dxm2891's fork are a few commits of mine, I'll submit a PR.
