### ISSUE TITLE
Futanari.XXX does not match despite being listed as supported

### ISSUE THREAD

**Issue by SekiAD** [PAhelper/PhoenixAdult.bundle#1879]
**Describe the bug**
Futanari.xxx is listed alongside its network like Hentaied and Parasited. Those two sites will match correctly and pull metadata. Futanari.XXX does not.

I have tried doing a manual match using

`Futanari XXX - Trapped` 

to no success and with website spelled out entirely. Same for all other videos for from that site. In the `PASiteList.py` it lists the website as ` ('Futanari XXX', 'https://futanari.xxx', '/?s='),` for its shorthand. Yet it does not work.

**Include**
1. https://futanari.xxx/trapped/
2. Futanari XXX - Trapped
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/14134930/com.plexapp.agents.phoenixadult.log)

**Comment by diamondpete** [comment]
Has to be FutanariXXX - Trapped to work. 'XXX' is filtered out from filenames if it is on its own.

**Comment by SekiAD** [comment]
> Has to be 'FutanariXXX - Trapped' to work. 'XXX' is filtered out from filenames if it is on its own.

This worked.
