### ISSUE TITLE
UpskirtJerk not working

### ISSUE THREAD

**Issue by LotusBob** [PAhelper/PhoenixAdult.bundle#1888]
UpkirtJerk used to work, but for quite some time now it does not. 

Thanks for your support.

**Comment by LotusBob** [comment]
Thanks for the response.  I'm not sure I am applying or using the fix
correctly.
I downloaded the latest version of the phoenixadult.bundle.  I do see
the same failure.
Do I need to download something different, or apply it in a different way?
In the past fixes have been recognized on my system by following the
procedure above.
Much appreciate your efforts.

**Comment by diamondpete** [comment]
Sometimes plex doesn't run the new plugin code. Make sure to fully stop the application and restart it. Also, if you are trying to refresh any matches you will need to rematch them as the rework changes the match ID.

If restarting doesn't work generally when this happens, I update a random file (adding a single space saving then removing and saving again). This seems to help plex figure out that the plugin code has changed.

**Comment by LotusBob** [comment]
Thanks. I'll give that a try
