### ISSUE TITLE
TeamSkeet sites broken

### ISSUE THREAD

**Issue by TexasSTX** [PAhelper/PhoenixAdult.bundle#1905]
TeamSkeet recently updated their site and it looks like all related sites lost search functionality with the plugin.  I attempted to recheck old videos that had already populated with metadata and it was unable to resolve those as well.  All other sites I checked that are not related to TeamSkeet, i.e., Brazzers, WebYoung, AdultTime, appear to function fine.

**Comment by diamondpete** [comment]
Please provide an example scene. Both the direct URL and google search are working.

**Comment by TexasSTX** [comment]
This is for a video that once resolved:
Direct link: https://app.teamskeet.com/movies/23722?r=

Log entry showing no match found:
`Mar 19, 2024 14:26:02.321 [12844] DEBUG - [Req#f696] [com.plexapp.system] HTTP reply status 200, with 130 bytes of content.
Mar 19, 2024 14:26:02.321 [10296] DEBUG - Completed: [127.0.0.1:59225] 200 GET /system/agents/search?mediaType=1&id=19076&identifier=com.plexapp.agents.phoenixadult&duration=2432153&filename=F%253A%255CPrivate%255CWeb%2520Vids%255CTeam%2520Skeet%255CFamily%2520Strokes%255CFamilyStrokes%2520-%2520Sophias%2520Test%252Emp4&lang=en&openSubtitlesHash=24d312a356b650ff&plexHash=7c365e65991f479173aa42568b892c725370a49d&name=Familystrokes%20Sophias%20Test&manual=1 (7 live) #f696 GZIP 36817ms 437 bytes (pipelined: 2)
Mar 19, 2024 14:26:02.321 [13484] DEBUG - [HttpClient/HCl#4e8] HTTP/1.1 (36.8s) 200 response from GET http://127.0.0.1:32400/system/agents/search?mediaType=1&id=19076&identifier=com.plexapp.agents.phoenixadult&duration=2432153&filename=F%253A%255CPrivate%255CWeb%2520Vids%255CTeam%2520Skeet%255CFamily%2520Strokes%255CFamilyStrokes%2520-%2520Sophias%2520Test%252Emp4&lang=en&openSubtitlesHash=24d312a356b650ff&plexHash=7c365e65991f479173aa42568b892c725370a49d&name=Familystrokes%20Sophias%20Test&manual=1 (reused)
Mar 19, 2024 14:26:02.321 [9640] WARN - [Req#f6a2] No matches for search.
`

This is a new video that brought the problem to my attention:

Direct link: https://app.teamskeet.com/movies/23722?r=

Log entry showing no match:

`Mar 19, 2024 14:34:56.736 [10012] DEBUG - Completed: [127.0.0.1:59403] 200 GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgplMDYzYjAzNTI1NTZhZDE5czE3Cm9wZW5TdWJ0aXRsZXNIYXNoczMxClNpc2xvdmVzbWUgR2l2aW5nIEF1YnJleSBhIEhhbmRzNApuYW1lczExMwpGJTNBJTVDUHJpdmF0ZSU1Q1dlYiUyMFZpZHMlNUNUZWFtJTIwU2tlZXQlNUNTaXMlMjBMb3ZlcyUyME1lJTVDU2lzTG92ZXNNZSUyMC0lMjBHaXZpbmclMjBBdWJyZXklMjBhJTIwSGFuZCUyRW1wNHM4CmZpbGVuYW1lczQwCjUyYTdkYzVjNGE3YTMzMTBlY2ZkZWVmOTQxM2Y4MDM2NmIwZGJkMTFzOApwbGV4SGFzaHM3CjM5NjUwMjdzOApkdXJhdGlvbnM1CjE5MTg3czIKaWRyMAo_ (7 live) #f6f5 GZIP 24787ms 666 bytes
Mar 19, 2024 14:34:56.739 [13484] DEBUG - [HttpClient/HCl#4f3] HTTP/1.1 (24.8s) 200 response from GET http://127.0.0.1:50608/system/agents/search?mediaType=1&id=19187&identifier=com.plexapp.agents.phoenixadult&duration=3965027&filename=F%253A%255CPrivate%255CWeb%2520Vids%255CTeam%2520Skeet%255CSis%2520Loves%2520Me%255CSisLovesMe%2520-%2520Giving%2520Aubrey%2520a%2520Hand%252Emp4&lang=en&openSubtitlesHash=e063b0352556ad19&plexHash=52a7dc5c4a7a3310ecfdeef9413f80366b0dbd11&name=Sislovesme%20Giving%20Aubrey%20a%20Hand&manual=1
Mar 19, 2024 14:34:56.739 [3752] DEBUG - [Req#f6f2] [com.plexapp.system] HTTP reply status 200, with 130 bytes of content.
Mar 19, 2024 14:34:56.739 [10012] DEBUG - Completed: [127.0.0.1:59400] 200 GET /system/agents/search?mediaType=1&id=19187&identifier=com.plexapp.agents.phoenixadult&duration=3965027&filename=F%253A%255CPrivate%255CWeb%2520Vids%255CTeam%2520Skeet%255CSis%2520Loves%2520Me%255CSisLovesMe%2520-%2520Giving%2520Aubrey%2520a%2520Hand%252Emp4&lang=en&openSubtitlesHash=e063b0352556ad19&plexHash=52a7dc5c4a7a3310ecfdeef9413f80366b0dbd11&name=Sislovesme%20Giving%20Aubrey%20a%20Hand&manual=1 (6 live) #f6f2 GZIP 24798ms 437 bytes (pipelined: 1)
Mar 19, 2024 14:34:56.740 [13484] DEBUG - [HttpClient/HCl#4f2] HTTP/1.1 (24.8s) 200 response from GET http://127.0.0.1:32400/system/agents/search?mediaType=1&id=19187&identifier=com.plexapp.agents.phoenixadult&duration=3965027&filename=F%253A%255CPrivate%255CWeb%2520Vids%255CTeam%2520Skeet%255CSis%2520Loves%2520Me%255CSisLovesMe%2520-%2520Giving%2520Aubrey%2520a%2520Hand%252Emp4&lang=en&openSubtitlesHash=e063b0352556ad19&plexHash=52a7dc5c4a7a3310ecfdeef9413f80366b0dbd11&name=Sislovesme%20Giving%20Aubrey%20a%20Hand&manual=1
Mar 19, 2024 14:34:56.740 [9640] WARN - [Req#f6f3] No matches for search.`

**Comment by diamondpete** [comment]
Please make sure you are using the latest code.

The direct links you are referring to are for the members site.

The scraper pulls from public sites
https://www.teamskeet.com/movies/sophias-test
https://www.sislovesme.com/movies/giving-aubry-a-hand

The following search strings work

familystrokes - sophias test
![image](https://github.com/PAhelper/PhoenixAdult.bundle/assets/87245367/58f72664-a1d0-46a6-99c0-b8d6b1fe9933)

sislovesme - giving aubry a hand
![image](https://github.com/PAhelper/PhoenixAdult.bundle/assets/87245367/624d3e00-48a6-437b-b290-97513368ed79)

**Comment by TexasSTX** [comment]
yeah, those search strings fail for me too (actually, aside from capitalization those were my original search strings).  It may be a regional thing.  Texas apparently passed a law that requires age verification, site got revamped right before that, maybe it's preventing the scraper from accessing data.
