### ISSUE TITLE
mylf not pulling actress name or genre

### ISSUE THREAD

**Issue by xmxier** [PAhelper/PhoenixAdult.bundle#191]
mylf not pulling actress name and also genre

specifically: Momdrips

**Comment by xmxier** [comment]
also genre

**Comment by claygoldfinch** [comment]
@xmxier are you still experiencing issues with this? I believe several bugfixes have been submitted addressing the Mylf network. If you are, please let us know what scenes you're having trouble with (plus logs, if you can).

**Comment by xmxier** [comment]
no it's working only mylfdom because the site was removed from mylf to http://mylfdom.com/

**Comment by claygoldfinch** [comment]
Resolved in PR #264
