### ISSUE TITLE
No matches for: FirstClassPOV, SinfulXXX, Watch4Beauty, TheWhiteBoxxx, MyDirtyHobby

### ISSUE THREAD

**Issue by shwnblnk** [PAhelper/PhoenixAdult.bundle#1945]
**Describe the bug**
Tried to match a couple of Videos manually in various variations (date - actor - title, actor - title, date - actor, date - title, actor, title)
but nothing works, even if it should based on the sitelist.

Samples below:

**FirstClassPOV**
1. Can't pass the Censorship
2. FirstClassPOV - Rika Fane Welcomes A Delightful Creampie [2023.08.17 - Rika Fane]

**SinfulXXX**
1. Can't pass the Paywall
2. SinfulXXX - 2023.06.09 - Rika Fane - Best Birthday Ever 2 [1080p]

1. Can't pass the Paywall
2. SinfulXXX - 2023.08.04 - Rika Fane And Isabella De Laa - Tales of a Taxi Ride 1 [1080p.HEVC.x265]

**Watch4Beauty**
1. https://www.watch4beauty.com/updates/nobody-came
2. Watch4Beauty - Nobody Came [2023.11.23 - Rika Fane][1080p.HEVC.x265]

1. https://www.watch4beauty.com/updates/chess-or-masturbating
2. Watch4Beauty - Chess Or Masturbating [2023.12.21 - Rika Fane][1080p.HEVC.x265]

1. https://www.watch4beauty.com/updates/orgasm-by-the-pool
2. Watch4Beauty - Orgasm By The Pool [2023.11.07 - Rika Fane][1080p.HEVC.x265]

1. https://www.watch4beauty.com/updates/movie-star
2. Watch4Beauty - movie-star [2023.10.13 - Rika Fane][1080p.HEVC.x265]

1. https://www.watch4beauty.com/updates/sexy-while-exercise
2. Watch4Beauty - Sexy While Exercise [2023.08.03 - Rika Fane]

**X-Angels**
1. https://x-angels.com/trailers/Cunnilingus-as-a-morning-routine.html
2. X-Angels 2023.03.17 - Cunnilingus as a morning routine [Rika.Fane][1080p.HEVC.x265]

**TheWhiteBoxxx**
1. https://www.letsdoeit.com/scene/10154061/taped
2. TheWhiteBoxxx - 2024.04.07 - Rika Fane - Taped

**4. Log File:**
[com.plexapp.agents.phoenixadult.log.txt](https://github.com/user-attachments/files/16609850/com.plexapp.agents.phoenixadult.log.txt)

**Comment by shwnblnk** [comment]
MyDirtyHobby is also broken.

Can't even enter https://www.mydirtyhobby**.com**

1. https://www.mydirtyhobby.de/profil/81698722-Fiona-Fuchs/videos/9694982-Mein-geheimes-Tagebuch-Sexfantasie-wird-Realitaet
2. MyDirtyHobby - 2023.03.04 - Fiona Fuchs - 9694982-Mein-geheimes-Tagebuch-Sexfantasie-wird-Realitaet [1080p]

[com.plexapp.agents.phoenixadult.log.txt](https://github.com/user-attachments/files/16617338/com.plexapp.agents.phoenixadult.log.txt)

**Comment by diamondpete** [comment]
SinfulXXX
SinfulXXX - 2023.06.09 - Rika Fane - Best Birthday Ever 2
SinfulXXX - 2023.08.04 - Rika Fane And Isabella De Laa - Tales of a Taxi Ride 1

These searches won't work with the sites search. I fixed the title, but the above won't resolve.
Try
SinfulXXX - 2023.06.09 - Rika Fane
SinfulXXX - 2023.08.04 - Rika Fane
