### ISSUE TITLE
List of sites with new interface

### ISSUE THREAD

**Issue by dxm2891** [PAhelper/PhoenixAdult.bundle#197]
This is a list with sites with new interface like DigitalPlyground.com which contain problems in searching for content.

- Babes (#102)
- DigitalPlyground.com (#136)
- Mofos.com (#189)
- Twistys.com (#131)

Write here if there are other sites like that and if someone can find a solution.

**Comment by claygoldfinch** [comment]
Looks like New Sensations is no longer working.

**Comment by claygoldfinch** [comment]
Having some luck getting Babes back up and running.

**Comment by insickin** [comment]
> 
> 
> Looks like New Sensations is no longer working.

I don't know if this helps you: 
https://github.com/PAhelper/PhoenixAdult.bundle/issues/104#issuecomment-473073506

**Comment by claygoldfinch** [comment]
Perhaps we should sticky a post similar to this - a list of "broken" sites, and a link to the wiki for all supported sites (which I'm currently working on getting up to date).
