### ISSUE TITLE
only a few sites work on plex linux

### ISSUE THREAD

**Issue by AbuSayidAlIslam** [PAhelper/PhoenixAdult.bundle#198]
Ok this might just be an issue with my setup, idk, im on linux and only 5 or 6 sites seem to work: Bangbros, RK, Brazzers, girlsway and a couple others

blacked/tushy/vixen etc all give "no matches found" when using search\
those are the ones i need the most. help?

**Comment by SgtBatten** [comment]
#64 pinned issue. Sounds like the same thing

**Comment by Sinjin69** [comment]
You need to provide more information. Can you tell us what your exact search phrase is?

Even better is if you can provide the log for the failed result. Follow this web page to find the directory they are stored for your os: https://support.plex.tv/articles/200250417-plex-media-server-log-files/

Once you find that directory, you will need to go into `PMS Plugin Logs` and get the file called `com.plexapp.agents.phoenixadult.log`.

**Comment by Sinjin69** [comment]
Maybe a dup of #64

**Comment by r0x0r316** [comment]
I am on Linux and can confirm Tushy main site working. Tushy Raw doesnt give matches with the usual Sitename - Date - Actor or Title
Vixen works like a charm.
Havent testet Blacked yet but i guess it works also on linux.

**Comment by claygoldfinch** [comment]
> I am on Linux and can confirm Tushy main site working. Tushy Raw doesnt give matches with the usual Sitename - Date - Actor or Title
> Vixen works like a charm.
> Havent testet Blacked yet but i guess it works also on linux.

IIRC, TushyRaw is direct URL match only.

**Comment by r0x0r316** [comment]
thx again  @claygoldfinch :)

**Comment by Sinjin69** [comment]
> I am on Linux and can confirm Tushy main site working. Tushy Raw doesnt give matches with the usual Sitename - Date - Actor or Title
> Vixen works like a charm.
> Havent testet Blacked yet but i guess it works also on linux.

I'm guessing OP is actually on a NAS. Those seem to have more issues.

**Comment by AbuSayidAlIslam** [comment]
> I'm guessing OP is actually on a NAS. Those seem to have more issues.

I'm running Arch Linux

**Comment by AbuSayidAlIslam** [comment]
> #64 pinned issue. Sounds like the same thing.
It is.
