### ISSUE TITLE
Teenfidelity no cast info/photo's

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#199]
Like the title say's, i'm trying to tag a Teenfidelity scene everything loads except the cast info/photo's, maybe they changed something on the site?

**Comment by claygoldfinch** [comment]
What's the filename or search term?

**Comment by insickin** [comment]
It's about "Mom Wouldn't Like That - Teenfidelity #297" everything loads but the cast photo's.

**Comment by claygoldfinch** [comment]
Any chance you can upload a log file? I've tested with that scene and several others, not running into any issues on my side.

**Comment by insickin** [comment]
Oke, strange... I thought I would try to add the scene one more time and if it still didn't work, I'd post a log file, now it loads fine with the cast members!... :confused: the only ting that I did to my server is install the latest update of the agent....
