### ISSUE TITLE
Mylf.com no date, actors

### ISSUE THREAD

**Issue by kamuk90** [PAhelper/PhoenixAdult.bundle#200]
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3237454/com.plexapp.agents.phoenixadult.log)

After updating meta, didn't added actors and date :(

**Comment by claygoldfinch** [comment]
PR #201.

The site doesn't have any release date data, so the code pulls it from the filename/search term itself. For example, to import a release date of 2019.01.01, search for:

Mylf - 2019.01.01 - 1663/hammering-the-hair-salon-don

**Comment by kamuk90** [comment]
> PR #201.
> 
> The site doesn't have any release date data, so the code pulls it from the filename/search term itself. For example, to import a release date of 2019.01.01, search for:
> 
> Mylf - 2019.01.01 - 1663/hammering-the-hair-salon-don

About the date ok, I understand
Can we do something with the cast/actors?

**Comment by claygoldfinch** [comment]
Mylf changed their site code, which resulted in the client erroring out while trying to pull a poster that no longer existed. This, in turn, caused the rest of the code to not be run (including the code that pulled the actors). PR #201 fixes that.

**Comment by kamuk90** [comment]
> Mylf changed their site code, which resulted in the client erroring out while trying to pull a poster that no longer existed. This, in turn, caused the rest of the code to not be run (including the code that pulled the actors). PR #201 fixes that.

Thx a lot
