### ISSUE TITLE
XEmpire not pulling actor name / picture

### ISSUE THREAD

**Issue by nitschkecm** [PAhelper/PhoenixAdult.bundle#21]
Hi 

nice to see that we have a scanner now for XEmpirel. Would you be able to add as well that the actor gets pulled as well as the actor image?

Many thanks!

**Comment by PAhelper** [comment]
@nitschkecm Could you give me an example? I just tested a Darkx scene and a Hardx scene, both pulled actors and their pictures...

**Comment by nitschkecm** [comment]
@PAhelper sure I have Paige Owens' 1st Blowbang and there is nothing from Paige pulled. I can happily share my log if you have an address. Thanks!

**Comment by PAhelper** [comment]
I downloading those scenes, you know for research, and I just loaded Paige's into Plex and it definitely added her as the Actor, complete with picture. Guess I'll need to get your logs...

**Comment by nitschkecm** [comment]
@PAhelper reloaded the git package and that resolved it Can close the topic!
