### ISSUE TITLE
VPN tunnel for PhoenixAdult plugin

### ISSUE THREAD

**Issue by kamuk90** [PAhelper/PhoenixAdult.bundle#216]
My IPS blocked more sites from list.
Is it possible to add vpn settings to the plugin for requests to sites from the black list of my internet provider

**Comment by r0x0r316** [comment]
Isn’t that a bit out of scope ? Just policy route via Pfsense or iptables

**Comment by kamuk90** [comment]
unfortunately, the iptables configuration is difficult to configure for me.
if I connect vpn on my nas, then the server becomes unavailable from the outside.
I'm trying to redirect requests from the plugin to the VPN, and not from the server.
I will be grateful if you tell me some documentation

**Comment by r0x0r316** [comment]
a good resource for router software OpenWRT
https://forum.openwrt.org/t/vpn-policy-based-routing-web-ui-discussion/10389
Pfsense official Doc
https://docs.netgate.com/pfsense/en/latest/routing/directing-traffic-with-policy-routing.html
older tutorial for pfsense
https://blog.monstermuffin.org/tunneling-specific-traffic-over-a-vpn-with-pfsense/

same should work with linux firewalls but for the grasping of the concept those guides should help you a lot. if you google iptables route specific traffic through vpn or policy based routing linux iptables it will give you plenty results and starting points. try first in your motherlanguage ;)

**Comment by r0x0r316** [comment]
this might help your case aswell 
https://hub.docker.com/r/linuxserver/openvpn-as/

**Comment by kamuk90** [comment]
Holy shit.
thanks a lot!
Before I start studying the documentation, I wanted to clarify whether it is possible to do it all? I mean, configure the plugin routing via vpn, and the plex itself without vpn
Plex installed on Synology NAS, router is Tplink archer c7

**Comment by r0x0r316** [comment]
Yeah definitely doable u just have to tell your router that every packet
destined for banned site should be routed via vpn vps ssh or whatever u
want.check if the archer c7 ist Ddwrt or openwrt compatible
Might be easier or just setup pfsense on a virtual machine

**Comment by Sinjin69** [comment]
I'm going to close this since this is outside of the scope of this plugin.
