### ISSUE TITLE
[site request] kink.com sites, especially The Upper Floor and Sex & Submission

### ISSUE THREAD

**Issue by PAHelper2** [PAhelper/PhoenixAdult.bundle#22]
Would love to have kink.com supported.  Doing some investigation now, and it seems like actress searches work pretty well, as long as you quote the actress names:

TheUpperFloor.18.05.04.Aiden.Starr.Karlee.Grey.And.Vanessa.Sky.XXX.720p.MP4-KTR =>
https://www.kink.com/search?q=%22Aiden+Starr%22+%22Karlee+Grey%22+%22Vanessa+Sky%22

TheUpperFloor.17.02.21.Kacie.Castle.And.Sadie.Santana.XXX.MP4-SDXXX =>
https://www.kink.com/search?q=%22Kacie+Castle%22+%22Sadie+Santana%22

Trying to see if I can make a date + actress search with "Abella Danger".  She has a bunch of videos, but so far I can't find the correct url scheme to find it nicely.

**Comment by PAHelper2** [comment]
My python sucks and all, but here's a possible start to siteKink.py:

```
import PAsearchSites
import PAgenres
def search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchAll, searchsiteID):
    searchResults = HTML.ElementFromURL(PAsearchSites.getSearchSearchURL(siteNum) + encodedTitle)
    for searchResult in searchResults.xpath('//div[contains(@class,"shoot")]'):
        titleNoFormatting = searchResult.xpath('.//div[contains(@class,"shoot-thumb-info")]//div[contains(@class,"shoot-thumb-title")]//a)
```
Let me know if I'm on the right track.  I have no idea how to test this stuff, as I think HTML.ElementFromURL is part of the Plex stuff?  I'm struggling to find a way get this into a small script to work on.

**Comment by PAHelper2** [comment]
Interesting!  I found another kink.com specific bundle, which somehow downloads posters without any SSL issues: https://github.com/macr0dev/Kink.bundle

**Comment by PAHelper2** [comment]
Since there's a dedicated kink.com agent, we probably can close this out.

**Comment by PAhelper** [comment]
I'm leaving it because the other dedicated agent may have the answer to that SSL problem you ran into, and I'm seeing that pop up in some of the other sites. Plus eventually I'll merge kink.com into this Agent. Thanks for the legwork though, makes it easier...

**Comment by fritz276** [comment]
@PAhelper I dont see how the macr0dev bundle can help with the SSL issue, since that agent doesnt use "https" at all (see the code). So it seems that you cant access kink.com without SSL, so it does not help, I guess (I dont care for kink.com at all, but I am intersted in the SSL issue)

**Comment by yes12397** [comment]
is sitekink working? and hows the search method?

**Comment by Tharic99** [comment]
Following up with a request for this one in the main bundle as well.

**Comment by PAhelper** [comment]
I coded this today, but have 0 testing available since I'm at work. Fingers crossed I didn't break the whole agent again, bonus points if the Kink sites actually work :P

**Comment by PAhelper** [comment]
Alright, I think I got all the kinks worked out (pun intended). Give it a shot and let me know if it's working better now.

**Comment by PAHelper2** [comment]
I can confirm, with testing sample size of 1, that it works now.  Thanks! 

Now I need to figure out my organizational strategy for these.  Before I had a separate library for Kink, with that other agent.

**Comment by PAhelper** [comment]
Has anybody else tested this? I think the kink network support is solid, but would like to confirm before we close this issue...

**Comment by ColonelPud** [comment]
295 kink videos were successfully processed in multiple sites. I did have
scene ID for most. I still have to validate Training of O, but it looks
great.

**Comment by PAhelper** [comment]
Thanks for testing. I'm going to call this one a win and close it. Just open a new issue if you find something isn't working...
