### ISSUE TITLE
what code do i need to not get redirected by an image url.

### ISSUE THREAD

**Issue by SgtBatten** [PAhelper/PhoenixAdult.bundle#220]
I am working on some more PAextras improvements and adding more sites.

I can successfully grab a url to an image from a bunch of sites but often they fail to actually be downloaded into plex. 

One common issue is the image url that loads for me in a browser is not the one that the code ends up trying to get plex to download and its a redirected url which doesn't work.

For example:
We can all load this url in a browser NSFW https://stream.imagepost.com/videos/kyler-quinn-on-lubed-in-soaking-creampie/kyler-quinn-on-lubed-in-soaking-creampie-001.jpg

But when i pass this url to the code in any network (PornPros in this case) it ens ups being a scrambled CDN looking URL which doesn't work.

Is there a way to avoid this redirecting and force it to get the image at the specified URL?

**Comment by claygoldfinch** [comment]
It works if I replace "stream" with "www". Just tested using this code:

```
    try:
        art.append("https://www.imagepost.com/videos/kyler-quinn-on-lubed-in-soaking-creampie/kyler-quinn-on-lubed-in-soaking-creampie-001.jpg")
    except:
        pass
```

**Comment by SgtBatten** [comment]
Cheers mate, works nicely
