### ISSUE TITLE
Exact URL Matches

### ISSUE THREAD

**Issue by r0x0r316** [PAhelper/PhoenixAdult.bundle#221]
I have a feature proposal. How about we join efforts of direct url matching of every user of this plugin by makin the plugin send the direct match to a db ? this db could be parsed first in search for sites with direct url match. This way only one user would to match a Date-Actor/SceneTitle and every user afterwords would be able to get the result without having to manually pull. just needs a host for the db and some scripting. 

It would even be possible to build a fusker on the database to scrape all tour urls.

**Comment by SgtBatten** [comment]
Exact url doesn't mean you need to go find the full url of the scene. Often it just means you need to have the full exact name of the scene which in my experience is rarely different from what the name is from the download.

I might be missing what you are intending here.

**Comment by r0x0r316** [comment]
Not everyone gets the download directly from the sites. and  i would like to see a central point to scrape data from independent from site changes once someone matches everyone can match.

**Comment by d2dyno** [comment]
This sounds like an idea for a branch-out project. Personally, I don't want any details of my server going to a scraper's database.

**Comment by claygoldfinch** [comment]
I agree with @d2dyno, I don't think it's a good idea to save any user data to a public DB. I'm going to close this issue.
