### ISSUE TITLE
Not pulling posters from X-art

### ISSUE THREAD

**Issue by eiberger** [PAhelper/PhoenixAdult.bundle#223]
All metadata is coming from the X-art site, but not the poster. Or occasionally it manages to get the posters as well.
I use this file name policy as recommended "X-art - Title.mov" (or what the file format is). Earlier it worked as a charm but now I have to add posters manually.

**Comment by claygoldfinch** [comment]
Yep, I have a large X-Art library and the vast majority pull either a grey poster or no poster at all. It's on the to-do list, I just haven't gotten around to it yet. Much more fun adding new sites than troubleshooting existing ones, haha.

**Comment by SgtBatten** [comment]
X art was my inspiration for PAextras. I have a large X-Art collection also. 

The X-Art website present a few issues. Some videos have no image sets. 
Some videos have an associated image set but the name is different. 

This is why  the code scrapes 3 external sites looking for the same scenes to get the posters from. 

The 3rd of these sights. X-Art beauties finds images but the images don't download properly yet. The other two do. 

I'm guessing most of your scenes are being added to Plex while reasonably new, in this case the external sites have not hosted any images yet but they might later.

**Comment by SgtBatten** [comment]
Can you give me 2 or 3 examples and I'll look specifically

**Comment by claygoldfinch** [comment]
Yep, exactly the same issues I ran into when I looked into fixing the issue. Been doing so testing so I currently only have older scenes available.

Here's one that pulls a grey poster:
https://www.x-art.com/videos/awesome_threesome/

And one that doesn't pull any posters:
https://www.x-art.com/videos/wet_orgasm/

**Comment by SgtBatten** [comment]
Okay the Grey poster one is being caused in our code I assume. It pulls two posters from xart.com and then gets the fanart ones.

http://content1.x-art.com/videos/awesome_threesome/x-art_faye_leila_awesome_threesome_1.jpg
http://content2.x-art.com/videos/awesome_threesome/x-art_faye_leila_aw2.jpg

first works, second is grey. Changing it to http://content1.x-art.com/videos/awesome_threesome/x-art_faye_leila_awesome_threesome_2.jpg is what works and what is used to do. looking into that shortly.

**Comment by SgtBatten** [comment]
Ahh okay, easy fix.

I remember doing this a while ago

posterURL = poster[:-21] + "2.jpg"

but xart must do it differently now. Fix coming

**Comment by SgtBatten** [comment]
I tested it on a few scenes and all seem to work using -5 now instead of -21.

I committed straight to master as it was so minor. Please keep an eye out for any unexpected issues.

Looking at the no posters one now

**Comment by SgtBatten** [comment]
I've also fixed the no poster pull issue but am trying to make it pull the thumbnails also if theres no fansite matches. wont be too long

**Comment by SgtBatten** [comment]
Should be fixed in #224

**Comment by eiberger** [comment]
Wow, quick response :) Here is a screenshot from my Plex with movies from 2011 that I added recently. As you see some are OK with poster, some have another image, and some have light grey image and one in the top left corner appear to have nothing at all.

I also see that even if I do the same with naming of my files (X-art - filname etc), some of the films have "X-art" before the filename in Plex.

As mentioned above, X-art must have done something recently because earlier importing poster atomatically worked like a charm.

<img width="1023" alt="Skjermbilde 2019-06-16 kl  10 28 24" src="https://user-images.githubusercontent.com/50551366/59561512-946cf580-9021-11e9-8767-68318a0623dd.png">

**Comment by SgtBatten** [comment]
I just tried about half of those grey ones with the new code and all worked. Also the rich girl part 2 was also fine in terms of name and posters. There's nothing I can do if it doesn't auto select the right poster though. usually its a cache problem with having already chosen a bad one previously. I'll merge the PR now.

@eiberger

**Comment by claygoldfinch** [comment]
Thanks again, @SgtBatten! I'll test this out later today.

**Comment by eiberger** [comment]
I tried adding the 2010 X-art videos into a new library. When clicking on the pencil on the cover art - and then poster I see a lot mor media files - several versions of the cover/poster - some is fan art I guess? The grey cover is still there and is the default poster, so I have to go an change poster manually for each movie. Maybe there is a setting I am missing.

But still - a great improvement. Thumbs up!

**Comment by SgtBatten** [comment]
The grey one as far as I have tested is not or should not be being added as new. 

I'll check this title when I get home.

**Comment by SgtBatten** [comment]
I just tested She Cums in Colors and it worked fine. No grey image and the poster was defaulted to correctly. The fansite posters failed because I have not resolved one of the sites yet and it was the only hit so that was expected. The fact you dont have the fanart blank ones showing indicates you are not using the PAextras code which has been implemented for a few months.

![image](https://user-images.githubusercontent.com/24822223/59579696-564eff00-9111-11e9-8832-874cdf389582.png)

**Comment by eiberger** [comment]
I am quite new to Github - I really thought I downloaded the latest/correct version with the bug fix...

**Comment by claygoldfinch** [comment]
@SgtBatten just re-scanned 940 scenes, released between 2010 and 2018, and only had one instance of the "grey poster" - [Angelica~Hotter Than Ever](https://www.x-art.com/videos/angelicahotter_than_ever/)

@eiberger try doing the [Plex Dance](https://forums.plex.tv/t/the-plex-dance/197064), best way to clear an existing metadata cache.

**Comment by eiberger** [comment]
I don't mean to ask newbie questions or for general Plex support. Let me know if I am asking things that don't belong here. But I have downloaded the software from [here](https://github.com/PAhelper/PhoenixAdult.bundle/tree/7f31544318e23409087ec5541b323ef0f03f9cb3) (The green download-button).
<img width="991" alt="Skjermbilde 2019-06-17 kl  23 27 54" src="https://user-images.githubusercontent.com/50551366/59638102-c3858300-9157-11e9-9b14-778700948797.png">

And I have checked that the downloaded files "PAextras.py" (2 months) and "sdtexart-py" (2 days) are similar to the files in the contents/code-folder. 
Tried the Plex Dance - still no luck. Maybe there are som settings that I have not set correctly.
I do get all the posters, which I did not before. But I get three images, a grey poster, the correct poster and a another image form the movie - and the grey poster is default. An example. 
<img width="557" alt="Skjermbilde 2019-06-17 kl  23 33 25" src="https://user-images.githubusercontent.com/50551366/59638387-92598280-9158-11e9-8b53-6ab6c356a17b.png">

Again, if this is off topic - sorry...

**Comment by SgtBatten** [comment]
@eiberger please provide the log for one of these items after refreshing metadata.

**Comment by eiberger** [comment]
I found  In the Logs/PMS Plugin Logs-folder the following log-file named com.plexapp.agents.phoenixadult.log. It was created 23.07 yesterday local time, and was when I did my last try. It is quite long so I copied it into my Public Dropbox folder:

https://www.dropbox.com/s/s6uksp6o7p5u8r3/com.plexapp.agents.phoenixadult.log?dl=0

**Comment by eiberger** [comment]
I found In the Logs/PMS Plugin Logs-folder the following log-file named com.plexapp.agents.phoenixadult.log. I did a metadata refresh and verified that the time of the log-file is created as a result of the refresh. The library contains X-art movies from 2010 and 2011.

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3299938/com.plexapp.agents.phoenixadult.log)

**Comment by SgtBatten** [comment]
@eiberger Here's part of your log for She Cums in Colors.
![image](https://user-images.githubusercontent.com/24822223/59657067-e7da7180-91e2-11e9-936c-42777d5d59ce.png)

It only attempts to download two images and both of them are valid. One poster and one background which it seems is in fact working for you. 

1. Try just refreshing one item and focus on solving it for one. 
2. Try manually unmatching it and then match it again. 
3. And finally try unmatching, then hit analyse, then match again.

**Comment by SgtBatten** [comment]
@claygoldfinch 
Just published a fix for the one grey poster you had left.

**Comment by eiberger** [comment]
Well, that did the trick. The grey posters are gone and Plex is choosing the correct posters.
Thanks for all help!

**Comment by SgtBatten** [comment]
Sweet. No worries
