### ISSUE TITLE
PervMom fix

### ISSUE THREAD

**Issue by kamuk90** [PAhelper/PhoenixAdult.bundle#228]
fixed wrong posters and actorUrl
[sitePervMom.py.zip](https://github.com/PAhelper/PhoenixAdult.bundle/files/3310367/sitePervMom.py.zip)

**Comment by d2dyno** [comment]
Please close this and file a pull request: https://github.com/PAhelper/PhoenixAdult.bundle/pulls

**Comment by claygoldfinch** [comment]
This breaks #158 again. I'll look into this, but will not be merging it as-is.

**Comment by claygoldfinch** [comment]
Should be finally resolved in PR #238
