### ISSUE TITLE
Proposal - Removal of Supported Sites List from Readme

### ISSUE THREAD

**Issue by claygoldfinch** [PAhelper/PhoenixAdult.bundle#233]
I think this would simplify things for a few reasons:

- Only one location (the Wiki) has to be updated every time a site is updated or added. Over the past couple weeks I've added 50+ sites/subsites to the Wiki. These sites have been supported for quite a while, but either the Readme or Wiki were never reflected to show these changes. Kinda useless to add support for sites if no one knows they are supported, at least without going through the commit history.
- The Readme is severely truncated. The agent supports almost 750 sites/subsites, the Readme lists ~100 sites.

Any input?

**Comment by insickin** [comment]
I think that that's a good idea! The readme is a bit outdated anyway! Maybe a rework of the readme?

**Comment by PAhelper** [comment]
Originally the README was the full list of sites, but as the list got so expansive, I thought it better to just list each supported network in the README, and use the Wiki to list each and every individual site under all the networks. I obviously failed at keeping both lists maintained the way I should have...

I agree that having a single location for all supported sites would be ideal.

**Comment by d2dyno** [comment]
Perhaps we can have move the wiki document to a doc/readme (either .md or .rst), and properly rewrite things. One of the main things I want to re-write things to, is having a 'level of search' number, and each site has a level assigned to it (and sub-level where necessary, see below). This would remove the '*** scene id' or '*** exact url only' next to each site on the wiki. I think a doc also helps, to show changes between versions. I can write this up if everyone thinks it's a good idea.

We would define what each level is capable of, for example:

All searches require site name prefix, such as `SiteName` `xyz` `123`
1: Multi-search available. This includes, searching by actor, by scene name, or by date (or all of the above).

2: Limited-search available. This is broken down into 2 sub-levels, which likely can not be used together:
   - actor-only
   - date-only

3: Exact matching only. Again broken down into 2 levels:
   - Scene ID only
   - exact url only

**Comment by claygoldfinch** [comment]
@PAhelper No worries, until recently I've been pretty lax about it myself, haha. 

@d2dyno That sounds perfect! I've been meaning to address the "Level of Search" for quite a while now.

A few things I've been wanting to clarify for users that I think the Wiki/Readme struggles with:

**SceneID Search vs SceneID Match vs SceneID Only**
- SceneID Search: Scene ID can be entered as the ONLY search term and the agent will locate results
  - Example: Though EvilAngel has a full-fledged title/actor search function, you can also just search by Scene ID and find results
- SceneID Match: SceneID can be entered as a search term alongside other search terms (Title, Actor) to increase the possibility for a match, but cannot be entered as a standalone search term.
  - Example: Though Kink has a full-fledged title/actor search function, you cannot enter just a SceneID and find results. However, if a SceneID is entered alongside a title/actor, it will increase the possibility of locating the correct scene
- SceneID Only: Search relies solely on SceneID. You may add additional terms to your search (Title, Actor, Date), but if a SceneID is not entered you will not receive any results
  - Example: Babes/PropertySex/etc. The agent strips the SceneID from your search term and plugs it into a URL. I've implemented some code so that adding a title to your search term increases the "score" you see, without a SceneID your search will return no results

**Date Search vs Date Match vs Date Add**
- Date Search: Date can be entered as the only search term and results will be found (not sure if this is implemented anywhere)
- Date Match: Date can be entered alongside other search terms to improve search results
- Date Add: If Date is entered as a search term and the site doesn't provide a publish date, the agent will strip the search date and attach it to the scene

**Comment by d2dyno** [comment]
Alright, glad I had the right thought! I will get to work on this tonight. Any sites I am not sure the search level, I will indicate as such in the document. Thanks for the above clarifications, and I will use those in the document as well :p

**Comment by r0x0r316** [comment]
Make that list scrapeable for the rename script or postprocesssing so one
could determine actor title search and rename on that basis

**Comment by claygoldfinch** [comment]
I'm gonna close this, all convo/input should probably be done at the drafted PR.
