### ISSUE TITLE
ultrafilms

### ISSUE THREAD

**Issue by ferengi82** [PAhelper/PhoenixAdult.bundle#242]
hi,

i tried my luck on ultrafilms.com / .xxx / .org. But im not sure how to get the best out of this site/s.

ultrafilms.com - no search, no video gallery, nothing
ultrafilms.xxx - search (title and actor), previews, genres, etc, **but no description**
ultrafilms.org - search (title and actor), genres, description, no images, **not all scenes aviable**

+ Releasedates from .xxx and .org dont match

is there an easy way to combine the data from .xxx and .org? or any sugestions on this site?

**Comment by claygoldfinch** [comment]
If org is missing scenes, I'd just use xxx as the primary search. 

Personally, I wouldn't bother with trying to pull summaries. However, if that's something you're interested in trying out, it appears as though you can scrape the title from xxx and plug it into org (ie "Ally - American Guest" --> "https://www.ultrafilms.org/Ally-American-Guest/").

It seems as though both xxx and org list scenes and galleries separately ([example](https://www.ultrafilms.xxx/?s=american+guest)), so try to incorporate that into your code.
