### ISSUE TITLE
VogoV.com Linux error

### ISSUE THREAD

**Issue by kamuk90** [PAhelper/PhoenixAdult.bundle#249]
I writing code for VogoV.com and have error like this #64 

URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>

**Comment by ferengi82** [comment]
same problem here with ultrafilms.xxx. im trying to copy the pornpros code. but at the moment im getting only more errors (pornpros is working). maybe you have more luck / knowledge

**Comment by kamuk90** [comment]
> @ferengi82 
try use code siteVogoV.py file from #246
I was able to correct my mistake

**Comment by ferengi82** [comment]
ssl works great, thanks.
but i hand no luck with your xpahts => please look over my suggestions they work for for me
