### ISSUE TITLE
Latest site added with date  to be viewed in Wiki after the Full Supported list

### ISSUE THREAD

**Issue by yes12397** [PAhelper/PhoenixAdult.bundle#250]
rather than entering  the full list and search line by line if these is something new added.
we create in the wiki a log with latest site with date . it will be much clear than Read.ME

thanks

Label : Enhancement

**Comment by d2dyno** [comment]
This sounds like something that https://github.com/PAhelper/PhoenixAdult.bundle/pull/234 will resolve. We are moving to a CHANGELOG.md file for all changes.

**Comment by yes12397** [comment]
thanks
