### ISSUE TITLE
Expand rename script to move and create folders.

### ISSUE THREAD

**Issue by CuddleBear92** [PAhelper/PhoenixAdult.bundle#251]
Would love to see the rename script get expanded on with additional features like folder creation of sites and networks.

This thing: https://github.com/PAhelper/PhoenixAdult.bundle/tree/master/postprocessing/windows

I think the additions to file moving and folder creations could help people setup their collection more automatically. Even if the files need to be renamed manually in the end to fit the common search params of the agent. (adding scene ID and such)

To be able to let it create folders like \network\site\videotitle.mp4 to a set directory would make sense.

Different parameters would be network, site, series, year, month?
Building on that, pulling metadata from the video file like res (simplified like 720p, 1080p, 4K) and framerate (if 60 or 59.94, write framerate for example)

In general users find more use with a clean filename than the original, but you loose much of the info from that.
Since there is no FileBot for Porn, this is the closest thing and should be expanded on.

- [x] Move files to set directory after rename.
- [ ] Create folders after found paramaters like site, year and so on.
- [x] Have a list of network and site relations to be able to make network sites (basepath\network\site)
- [x] Read MediaInfo for Res, codec & framerate to add to the filename.
- [x] Cleanup trash files like .txt and .nfo in the folders. (user created deletion list?(should handle .nfo files with the same name as the media))

**Comment by SgtBatten** [comment]
#270

**Comment by SgtBatten** [comment]
@CuddleBear92 let me know how you go

**Comment by SgtBatten** [comment]
Actually managed to successfully rename DaneJones scenes based on the release date. This was a trial site and I will be expanding on this with more sites for sure.

Had to add a dependency though.

` pip install lxml`

**Comment by SgtBatten** [comment]
Added a couple more sites now. this things gonna make my setup almost entirely automated now

**Comment by CuddleBear92** [comment]
Sounds good, will have to take a look at these changes. Still need a bit of manual handling on my part so far since i am crushing the files with hevc.

I could have this pretty much all automated if i had res and framerate exportable in the folder names so i can sort into individual folders for certain quality releases.

Do find that much of the older renamer needed much manual touchup for Plex matching cause of part of the url or id is needed for a match. 
Automating the encoding would be a huge help for sure with the user of mediainfo or something to pull that.

Find i need different bitrates and presets for the different framerates and sizes. CQ encoding does sadly not keep as much quality across all moments compared to a variable bitrate.

**Comment by SgtBatten** [comment]
@CuddleBear92 It was surprisingly easy to implement.

Current commit as of this post adds Resolution and fps to the file and to the folder name. So you dont need to specify he resolution in the siteList section it will append it to the end of whatever root folder structure you have created.

so if you have `siteList[0] = ["Babes", "New", "New\Babes"]`
you will end up with folders like 
`New\Babes 1080p 24fps`
`New\Babes 720p 24fps`
