### ISSUE TITLE
VivThomas search result url needs updating

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#253]
Currently, a search within the agent, will yield a result of something like `https://www.vivthomas.com/search/squirt%20surprise/relevance~0~68~-~-~-~-~-~-/2`, checking this on the website, will show there are 29 items found, but will not actually display them. So, I tried changing the url simply to `https://www.vivthomas.com/search/squirt%20surprise/relevance` and this shows the results correctly via the website. But a quick change in the code did not show any results within the Plex agent, so not sure what else needs to be changed.

**Comment by claygoldfinch** [comment]
This is the same issue as #243, as MetArt, MetArtX, SexArt, and VivThomas are all related.
