### ISSUE TITLE
Wowgirls cant find a scene

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#255]
Ok, I'm trying to add my Wowgirls scenes but it can't find 1.

Namely: WowGirls - Skin Care.

After looking in the logs I see that the agent tries to find the scene on: https://www.wowgirls.xxx but there its not listed! I found the scene on https://wowgirls.tv (https://wowgirls.tv/videos/lauren/skin-care/) maybe this site (which has a search function) can be integrated in the agent?

**Comment by claygoldfinch** [comment]
Is WowGirls.tv missing any scenes that are on WowGirls.xxx?

**Comment by ferengi82** [comment]
yes, these sites are a mess
https://www.wowgirls.xxx/?s=nekane
https://wowgirls.tv//?s=nekane&x=0&y=0

i even found a scene on ultrafilms that belongs on wowgirls ...

for the optimal results i think we ned to change from sites to network for wowgirl, ultrafilms, wowporn, (any other?) an check on any of them for the scene

**Comment by raedwulf83** [comment]
could www.wowgirlsblog.com be an possible option?
it has a search, scenes looks most complete, but misses the scenes discriptions

**Comment by ferengi82** [comment]
im working at the moment on
if scene on .xxx => take infos from there
else look at .tv

if there scenes that are on either of them then we could expande the search to wowgirlsblog

**Comment by ferengi82** [comment]
please try it when my pullrequest is merged

https://github.com/PAhelper/PhoenixAdult.bundle/pull/280

**Comment by claygoldfinch** [comment]
Just tested this out and was getting some errors while trying to scrape artwork. Submitted PR #364
