### ISSUE TITLE
Viv Thomas Support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#257]
I'm trying to add: "Viv Thomas - Mature Attraction Episode 1 - Blissful" to my server but I cat get it to match! I've tried all sorts of combos but to no avail... 

"Viv Thomas - Mature Attraction Episode 1 - Blissful"
"VivThomas - Mature Attraction Episode 1 - Blissful"
"Viv Thomas - Mature Attraction Blissful"
"Viv Thomas - Blissful"

Can someone show/tell me if i'm doing something wrong or that its the agent? I've looked in the logs and can see that it finds a search page where (when I copy the link to my browser) the searched scene is listed.
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3369998/com.plexapp.agents.phoenixadult.log)

**Comment by claygoldfinch** [comment]
Same issue as #243.
