### ISSUE TITLE
How to know if a Site needs "studio - title" or "studio - date - models" ?

### ISSUE THREAD

**Issue by PAHelper2** [PAhelper/PhoenixAdult.bundle#26]
As this agent is pretty picky about file naming structure (title vs model searches), is there an easy way I can check which studio search requires which sort of name?

For background, I have a post processing script that renames downloaded media into something that PA should be able to process better, however, I need to account for the different naming conventions.  Is there a master list I can reference that's up to date?

Thanks!

**Comment by PAhelper** [comment]
There isn't currently such a list, but I'm starting at add these to the Known Issues section of the readme. I almost never search by date though, and only use it as confirmation that I've found the right scene is it happens to be in the filename. So for my own purposes, it will usually be a choice between "studio - title" or "studio - actress"

**Comment by PAHelper2** [comment]
Okay, thanks.  That helps.  So that means I will need to figure out how to do name extraction from a file that's named like 'StudioName.18.20.05.Mary.Jane.And.Foo.Bar.Going.To.Town.mp4'.

**Comment by fritz276** [comment]
@PAHelper2 - care to share your postprocessing script?

**Comment by PAHelper2** [comment]
Sure.  It's pretty rough, and relies on a file I manage which has the site, plus their common abbreviations on a line.  

Here are the 3 files currently in use by sabnzbd:

[collections.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/2727624/collections.txt)

[pa_renamer_post.py.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/2727625/pa_renamer_post.py.txt)

[patools.py.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/2727626/patools.py.txt)

You need to rename the .py.txt to .py, obviously.

**Comment by PAHelper2** [comment]
Currently I drop the date from my filename, and only rename as "Studio - Rest of non date text.mp4"  The date is still in the directory name, and I can refer to it if necessary.

**Comment by fritz276** [comment]
Cool, will try it out later with sabnzbd, and report back to you :-) !!!

**Comment by PAhelper** [comment]
I believe I have added all the conditions to the README file now.

**Comment by SgtBatten** [comment]
@PAHelper2 hey mate trying to use your sabnzbd postprocessing on my windows server.

I originally got an error about the log file, realised the location was hard coded for linux so i changed that.

Now i see this error:
```
INFO:pa_renamer:Starting to process: P:\Plex\Videos\Travis\Porn\New\Passion-HD 19 03 02 Megan Marx The Sex Artist XXX 1080p MP4-KTR-Pornfuscated
CRITICAL:patools:Failed to match directory string: P:\Plex\Videos\Travis\Porn\New\Passion-HD 19 03 02 Megan Marx The Sex Artist XXX 1080p MP4-KTR-Pornfuscated
CRITICAL:pa_renamer:No match found for dir: P:\Plex\Videos\Travis\Porn\New\Passion-HD 19 03 02 Megan Marx The Sex Artist XXX 1080p MP4-KTR-Pornfuscated
```

So its trying to run pa_parse_dir(dir) but not working on windows. any idea what i should change?
