### ISSUE TITLE
Private

### ISSUE THREAD

**Issue by RafalHo** [PAhelper/PhoenixAdult.bundle#261]
Could someone tell me how to get a description to the movie?
File name: Private - Sexy Teenagers 2
https://www.private.com/movie/3902-sexy-teenagers-2/

**Comment by claygoldfinch** [comment]
Looks as though the agent only supports Private scenes, not movies.

**Comment by RafalHo** [comment]
Is there a chance that he also supports movies ;)

**Comment by blackibanez** [comment]
Hi

You can use my plugin , specially made for Private Movies :
https://github.com/blackibanez/Privatemovies.git

**Comment by RafalHo** [comment]
> Hi
> 
> You can use my plugin , specially made for Private Movies :
> https://github.com/blackibanez/Privatemovies.git

Super, works, thank you.  Is there any chance to add a cast of the movie in the future?

**Comment by blackibanez** [comment]
Hi, 
Normally cast is supported, I’ll see if site change. TY
