### ISSUE TITLE
Gangbang Creampie Search Issues

### ISSUE THREAD

**Issue by claygoldfinch** [PAhelper/PhoenixAdult.bundle#263]
Search seems broken on their site, using the scene number is the only way to find a match.

_Originally posted by @d2dyno in https://github.com/PAhelper/PhoenixAdult.bundle/pull/260_

**Comment by claygoldfinch** [comment]
What exactly appears to be the issue?

Search is somewhat limited, just due to how the site names their scenes. However, it does seem to work as expected. For example:

**Search Term: "Charlotte"**
Search Results:
- GangBang Creampie 222 (a scene she is in, confirming actor search works)
- Behind The Scenes with Charlotte (again, confirming actor search works)

**Search Term: "Behind The Scenes with Charlotte"**
Search Results:
- Behind The Scenes with Charlotte (confirming title search works)

**Comment by d2dyno** [comment]
Thanks for all the work today!

Hmm, I was trying actor names (first and last name, maybe I should try just first name), date, and ID. Using date at all would break the search, and as I said first and last name wouldn't work either. I can test some more.

**Comment by claygoldfinch** [comment]
Yeah, it looks like the site only uses first names for actresses. Adding the date would only help confirm a match, the site doesn't have a native date search.

**Comment by b0nensfw** [comment]
@claygoldfinch is this issues still open? Ganbang Creapie seem to work for me
