### ISSUE TITLE
FakeHub Site Change

### ISSUE THREAD

**Issue by calibear20** [PAhelper/PhoenixAdult.bundle#265]
Hello,

It looks like FakeHub have changed their whole website. This has broke the Scene search that was implemented. FakeHub videos are now based on IDs.

Based on the previous implementation I would have passed something along the lines of this:

https://www.faketaxi.com/search/videos/fuck%20me%20baby%20one%20more%20time

Now we can use the link below to get to the same scene:

https://www.faketaxi.com/scene/4360278 - Example

Not much an issue more of a notice.

Thanks,

Calibear20

**Comment by claygoldfinch** [comment]
Thanks for the heads-up.

Search is still available, but they've switched over to the same layout as Babes/MOFOS/etc. So it's essentially useless. 

I'll take a look at converting this over.

**Comment by SgtBatten** [comment]
I think we might need to consider a python 3 compatibility check/rewrite so that we can use requests-html which can do javascript. The more i try to solve #114 the more issues i run into

**Comment by d2dyno** [comment]
Looking forward to this being updated as well.

**Comment by SgtBatten** [comment]
#317 Please review/test
