### ISSUE TITLE
Mofos broken

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#269]
I am trying to tag "Mofos - Study Break Squirter" but all I get back is "no matches". I think that the site has changed somewhere, yesterday I could get scenes to be tagged.
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3379150/com.plexapp.agents.phoenixadult.log)

**Comment by claygoldfinch** [comment]
Try a server reboot. Sites with this new layout can be a bit buggy sometimes.

**Comment by insickin** [comment]
Oke, I looked after posting if I had the latest version of the Agent which was not the case, updated an now it finds the scene!
