### ISSUE TITLE
Pornfidelity/Teenfidelity support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#27]
I am trying to get: Pornfidelity - Swollen and Teenfidelity - Devil's Creampie tagged but without success, all I get is: No matches found.

I came across this problem before with Pornfidelity/Teenfidelity scene's but got the scene's tagged wit the combo of: Pornfidelity - name of the actress but with this scene's that does not work either.

**Comment by PAhelper** [comment]
I have Devil's Creampie to test. I made some changes and the search function seems to work much better now. Please download the latest push and give this another try.

**Comment by insickin** [comment]
Thanks now both scenes are found and tagged!
