### ISSUE TITLE
Assistance matching old AnalBeauty scenes

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#275]
I am trying to match scenes on Anal Beauty from before they started using full titles (They started using titles November of 2014). Before that, they just used actor first or first and last name. For these scenes, I cannot get the agent to match them. For example this scene, [Iva](http://anal-beauty.com/trailers/Iva-12934.html)

Search terms tried:
`analbeauty 14 03 24 Iva`, `analbeauty Iva`, `analbeauty 14 03 24` and `analbeauty Iva-12934` (from url)

**Comment by claygoldfinch** [comment]
Agent was set up to scrape actors from the search page. One of the scenes on the search page didn't have any actors listed, and was causing the agent to error out.

Resolved in PR #264.
