### ISSUE TITLE
Mylf support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#277]
I am trying to add Mylf scenes but with all the scenes I try to add I get back: No matches, I have the latest agent.

For example:
"Pink From the Shrink Milf Seduces Younger Girl" [https://www.mylf.com/movies/1525/pink-from-the-shrink](url)
If I'm right I must search with: Mylfed - 1525/pink-from-the-shrink

I've rebooted my Plex server multiple times.
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3388943/com.plexapp.agents.phoenixadult.log)

**Comment by claygoldfinch** [comment]
Fixed in my latest PR, I'll merge it in.

**Comment by insickin** [comment]
Thanks it works now!
