### ISSUE TITLE
Mylf support 2

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#278]
After the last update from @claygoldfinch most scenes tag perfectly but there are 3 pesky scenes that won't tag:

Mylf - When Her Man Is Away, This Milf Will Play https://www.mylf.com/movies/1713/when-her-man-is-away,-this-milf-will-play

Milfty When It Rains, She Whores! Milf Jerking Cock 

https://www.mylf.com/movies/1693/when-it-rains,-she-whores!

Milfbody Do You Even Lift, Hoe Thick Thighs and Ass https://www.mylf.com/movies/1691/do-you-even-lift,-hoe? (This scene is apparently broken on the site or something...

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3389012/com.plexapp.agents.phoenixadult.log)

**Comment by SgtBatten** [comment]
Would most likely be due to the punctuation. Remove the commas and question marks and try

**Comment by insickin** [comment]
Still no dice.... Without the comma's and the question marks IT still doesn't match.

**Comment by d2dyno** [comment]
Almost definitely due to commas. I am having issues on this scene as well: https://www.mylf.com/movies/1677/suck-it-dry,-blue-eyes

Commas are not standardized urls, I am honestly curious how they are working for mylf.com

**Comment by insickin** [comment]
Is there any progress with this?

**Comment by insickin** [comment]
Can this be fixed?

**Comment by insickin** [comment]
This is still a problem, when trying to tag for example: https://www.mylf.com/movies/2049/cheater,-cheater-milf-dick-teaser the agent finds nothing, I've tried it with and without the comma.

**Comment by claygoldfinch** [comment]
Nothing I can do about scene 1691, but the rest of em should be fixed with my latest PR.

**Comment by insickin** [comment]
Thanks now the agent finds/tags them right away!
