### ISSUE TITLE
Sweet Sinner/Sweetheart Video/Girlfriends Films support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#28]
Hey, first of all many, many, many thanks for adding these 2 sites!

But can you make it so the search can also find the full movie's? The agent searches in/for scene's (those I get back as results)

The scene's are tagged with: Studio XEmpire, can this be changed to Sweet Sinner/Sweetheart Video?

I'm testing with a few scene's/ movies but for example: Sweet Sinner - Father Figure 10 - Wet Watercolors isn't found ( I've also tried Sweet Sinner - Wet Watercolors) on there site it is found but on page 5 of the search results. I first thought that the search results were shown in the order they were on the site but that is incorrect...

**Comment by insickin** [comment]
@PAhelper I don't want to sound/be needy but are you working on/ do you have a solution for this problem?

**Comment by PAhelper** [comment]
I've had a similar problem with Hardx search results... From a programming standpoint, the problem is that they include all the search terms with logical OR instead of AND. In your example, it searches their database of scenes for all scenes including the word "wet" (which is likely a LOT of scenes), then also includes all scenes that include the word "watercolor" (which is only one scene). How it sorts them after that, I have no idea, but it's not closest match. I'll test and see if their search engine allows for operators similar to Google where you can use + to force inclusion of a word, or "quotes around" to force the words to match in that certain order. That could help create more accurate search results.

I was able to find your example above by searching "sweetsinner - watercolors". Basically the less words (and more distinct words) you use, the better.

As for the Studio, I'm having some struggle figuring out how I want to label those logically. "Gamma Productions Inc." is the parent studio behind Hardx, Lesbianx, etc. as well as EvilAngel, Girlsway, FantasyMassage (and it's sibling sites), PureTaboo, Throated, 21Naturals/21Sextury/21Sextreme and many more. "XEmpire" is the term for Hardx+Darkx+Lesbianx+Eroticax, and if you subscribe to one of those you get access to the others. They have another "studio" named Blowpass, which includes Throated, OnlyTeenBlowjobs, MommyBlowsBest, 1000 Facials, and a few other sites. I'm pretty sure PureTaboo is a completely standalone site though, not grouped with any others, but definitely part of this larger family. Do I just make the studio for PureTaboo be "PureTaboo"?

Actually I just checked and it looks like Sweet Sinner is part of the "Mile High Network", along with biempire.com, Sweetheart Video, Doghouse Digital, and RealityJunkies. So should I put that as the "Studio"? This is my dilemma...

**Comment by PAhelper** [comment]
Do you have files where you have the entire movie "Father Figure 10" for example in a single file? Obviously in the example you provided above, it appears you have split scenes, and can match each scene individually. But do you have some where you need to match the whole movie together, and return results for "Father Figure 10", and all the actors/actresses that are in the entire movie, and the DVD cover art, etc.?

**Comment by insickin** [comment]
> sweetsinner - watercolors

Now I can find the scene (with your instructions), I will try other searches (if they turn out with nothing found) with lesser words.

For the naming of the studio's, my take on it is that you have a (for example) Girlsway scene so it is tagged with studio Girlsway not the all-encompassing parent studio. Because if you go via your route you get instead of 10 Girlsway scene's and 5 EvilAngel scene's 15 Gamma Productions Inc. scene's, What I personally do not find specific enough, if you know what I mean.

**Comment by insickin** [comment]
> 
> 
> Do you have files where you have the entire movie "Father Figure 10" for example in a single file? Obviously in the example you provided above, it appears you have split scenes, and can match each scene individually. But do you have some where you need to match the whole movie together, and return results for "Father Figure 10", and all the actors/actresses that are in the entire movie, and the DVD cover art, etc.?

Indeed, for (for example) Father Figure 10 I've got 4 separate files/scenes but for (for example) Father Figure 1 I've got 1 file. (the whole movie)

If you search on their website for Father Figure 1 you have to select DVDS it shows default scenes.
[https://www.sweetsinner.com/en/search/Father-Figure-1/1](url) Scene's view
[https://www.sweetsinner.com/en/search/Father-Figure-1/1/0/0/0/dvd](url) DVD's view

I don't know if you've started on support for Girlfriends Films but the same applies for them.

PS: Have you seen that I've added a simple website for you to add [https://github.com/PAhelper/PhoenixAdult.bundle/issues/1](url)?

**Comment by insickin** [comment]
Another problem is this: https://www.sweetsinner.com/en/dvd/Father-Figure-09/31199 The scene's have no own name, maybe searching on a combo of the names of the actors can give the requested scene?

**Comment by PAhelper** [comment]
> Another problem is this: https://www.sweetsinner.com/en/dvd/Father-Figure-09/31199 The scene's have no own name, maybe searching on a combo of the names of the actors can give the requested scene?

So I will share a secret that I believe will work, but it is not a proper solution, just a workaround to their poor site search. If you go to the DVD page you linked, then copy the page link to each scene, you should end up something like "https://www.sweetsinner.com/en/scene/Father-Figure-09/81353" for Scene 1. If you match Scene 1 in Plex to "sweetsinner - 81353" it should find that scene and pull metadata.

Obviously this "Scene ID" isn't included in the filename when we download it, so it's no good for automatic matching, but it does allow you to match each scene very precisely with a little manual effort.

Hope this helps. Same trick works on other Gamma sites as well; all xempire, evilangel, burningangel, etc.

**Comment by insickin** [comment]
>> 
> I see. I have been using the metadata a little differently. If I want all the XEmpire scenes, I would search the Studio "XEmpire". If I just want the scenes from the EroticaX site, I would search the Collection "EroticaX". In the same way, I could search for all of Studio "Brazzers", or specifically for the collection "Real Wife Stories" or "Big Tits at Work", etc.

I've noticed the "collection" option that can indeed be a replacement! Hmm, I have to think about what is easy for me... 

> 
> Regarding full DVDs vs split scenes, I think I got a pretty successful system for Digital Playground where you can either match split scenes individually (and it makes a collection with the movie title to put them all together), or match the movie as a whole (and it grabs metadata for the whole movie). I will see what I can do for these sites as well, because Hardx, EvilAngel, etc. do the same thing as SweetSinner. One minor problem is that the scenes here do not link to their DVD release, but from the DVD release you can link to the individual scenes. This will make some difficulty in the programming.

Indeed, all those studio's that bring scene's and also DVD's tend to do this, if you can make this happen...

**Comment by insickin** [comment]
> 
> 
> > Another problem is this: https://www.sweetsinner.com/en/dvd/Father-Figure-09/31199 The scene's have no own name, maybe searching on a combo of the names of the actors can give the requested scene?
> 
> So I will share a secret that I believe will work, but it is not a proper solution, just a workaround to their poor site search. If you go to the DVD page you linked, then copy the page link to each scene, you should end up something like "https://www.sweetsinner.com/en/scene/Father-Figure-09/81353" for Scene 1. If you match Scene 1 in Plex to "sweetsinner - 81353" it should find that scene and pull metadata.
> 
> Obviously this "Scene ID" isn't included in the filename when we download it, so it's no good for automatic matching, but it does allow you to match each scene very precisely with a little manual effort.
> 
> Hope this helps. Same trick works on other Gamma sites as well; all xempire, evilangel, burningangel, etc.

This trick also worked in the older versions of this agent or his predecessors, it sounds familiar! So if I rename the file: "SweetSinner - Father Figure 9 - scene 1" to "SweetSinner - 81353 it should work?

**Comment by PAhelper** [comment]
In the search page the scene is named "Father Figure #09, Scene #1" as you listed there. However, on the details page for that scene, it is simply named "Father Figure #09". This is something I can programmatically check for and hopefully add the appropriate Scene # when it's missing.

**Comment by insickin** [comment]
If you can program it that way it would save me so mutch time! Maby you also make it so that the final tag name stats: "Father Figure 9 - Scene 1"? Without the #.

**Comment by insickin** [comment]
Have you made progress with this? I've tagged almost all separate scenes but now have those "Father Figure #9, Scene #1" scenes and full movies to tag.

**Comment by PAhelper** [comment]
Now that I've combined all Gamme Entertainment sites into a single file, this is next on my list...

**Comment by insickin** [comment]
Are you going to add Girlfriends Films at the same time?

**Comment by PAhelper** [comment]
Support for DVD releases? Yeah, if I add it for one, it should basically work for them all...

**Comment by insickin** [comment]
Yes but also support for "normal" scenes from Girlfriends Films? Because they cant be tagged at the moment.

**Comment by PAhelper** [comment]
I made a little progress with this issue. I've now set it up so if the scene title is the same as the DVD name, it will scrape the scene number from elsewhere in the page and append it to the scene title.

Using the earlier example, if you match Father Figure 9, scene 1, the title of the scene on the individual scene page is just "Father Figure #09" as noted above. Now, the agent will (hopefully) recognize that and locate which scene number it is from somewhere else in the page and the title in Plex will be "Father Figure #09 - Scene #01".

But I also set it to strip off the # sign and leading 0, so you should end up with "Father Figure 9 - Scene 1"

It will also create a Collection named "Father Figure 9", so as you add more scenes from that movie, they will all gather in a collection together. You can set the cover art for that Collection to the DVD cover art (there's no way for the metadata agent to affect the Collection directly to my knowledge).

I wrote the code and tested it on a single scene from Devil's Film. Hopefully it applies well to these other sites. Next up is allowing full DVD metadata searches...

**Comment by insickin** [comment]
Ok, I will test this this afternoon. Do you have tips on how to name the scenes for fast/easy recognition?
Should I go with:
"SweetSinner - Father Figure 9 - scene 1" or
"SweetSinner - scene 1" or
"SweetSinner - names of actors" or
"SweetSinner - 81353"

**Comment by insickin** [comment]
The agent finds the scene now but doesn't populate the "info page" I think something is broken in the Mile High Network/..... code. I've tried/tested with Sweet Sinner and Sweetheart scene's, can you fix this?

**Comment by PAHelper2** [comment]
I'm seeing the same behavior, on the video: GirlsWays - 144099

It matches, but doesn't download any of the metadata.

**Comment by PAhelper** [comment]
Alright, I've added code to support full movie (DVD) matches in Evil Angel and Sweet Sinner specifically, because those were the ones I had downloaded to test. Full DVD support may work on other sites. I tested with Girlfriends Films and it didn't work at all (scenes or DVDs). I'll look into that.

**Comment by insickin** [comment]
Ok, thanks I will test this!

**Comment by insickin** [comment]
Ok, I first tried a scene but this problem persists (the same what was happening with the Joymii scenes:
> The agent finds the scene now but doesn't populate the "info page" (no nice name, no synopsis and no cast photo's) I think something is broken in the Mile High Network/..... code. I've tried/tested with Sweet Sinner and Sweetheart scene's, can you fix this?

**Comment by PAhelper** [comment]
SweetSinner is working for me, so I'm definitely going to need some logs to help resolve your issue...

**Comment by insickin** [comment]
Is this the log that you need?
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/2850717/com.plexapp.agents.phoenixadult.log)

**Comment by PAhelper** [comment]
That's exactly what I needed, thank you. I've pushed a bugfix that will hopefully fix the issue. Let me know if you find more that don't work...

**Comment by insickin** [comment]
Yes, now its working perfectly! Thanks for the work!
Hopefully you can get Girlfriends Films support fast/soon!

**Comment by insickin** [comment]
I can't seem to find Women Seeking Women 161 on www.girlfriendsfilms.com after a bit of googling I found this site www.girlfriendsfilms.net where all DVD releases are posted, maybe/hopefully you can incorporate this site in the Girlfriends Films search?

**Comment by insickin** [comment]
@PAhelper How far is the support of Girlfriends Films studio? I'm trying to add movies/scenes but getting no result! (Also see my comment above)

**Comment by insickin** [comment]
I've included a log:
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/2977808/com.plexapp.agents.phoenixadult.log)

**Comment by insickin** [comment]
Is there any progress with this issue?

**Comment by insickin** [comment]
Is there any progress with this issue?

**Comment by insickin** [comment]
Can you take a look at this: @claygoldfinch @SgtBatten @dxm2891 @PAhelper

**Comment by b0nensfw** [comment]
@insickin is it still a bug? Can you reconfirm whats working/ not working

**Comment by insickin** [comment]
Yes @b0nensfw this is still a bug! I had a look and tested a few things for you:

Sweetheart Video:

For example tried with "sweetheartvideo - Girls Of Wrestling" whole DVD release, doesn't work
and "sweetheartvideo - A Helping Hand" a scene from Girls Of Wrestling also doesn't work

whole DVD release:
I tried searching with combo's like:
"sweetheartvideo - Girls Of Wrestling"
"sweetheartvideo - 76324"
"sweetheartvideo - Kenna James" (even though it is stated on the sitelist.md that you have to search with Limited (Title / Actor))

The same I did with the separate scene:
"sweetheartvideo - A Helping Hand"
"sweetheartvideo - 149285"
"sweetheartvideo - Kenna James"

I did the same for a Sweet Sinner release:

whole DVD release:
"Sweetsinner - the Voyeur 3"
"Sweetsinner - 76063"
"Sweetsinner - Avi Love"

Loose scene:
"Sweetsinner - the Voyeur 3"
"Sweetsinner - 148229"
"Sweetsinner - Avi Love"

Girlfriends Films the same deal, nothing works!

**Comment by b0nensfw** [comment]
@insickin Could you provide you log file, I will look it up today or this weekend

**Comment by b0nensfw** [comment]
@insickin I just did a Test with SweetSinner scene without problem

Is the problems only linked to Movie release?

**Comment by insickin** [comment]
I think I see whats the problem, I'm running my plex server on a Linux box and the last sentence from the log is the "famous" 

URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)> 

Error... I hope something can be done for us on Linux servers...

2019-09-20 15:52:52,593 (708fe460) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2019-09-20 15:52:52,595 (708fe460) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
2019-09-20 15:52:58,375 (708fe460) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1CjE1NDY5czIKaWRzMjYKU3dlZXRzaW5uZXIgLSB0aGUgVm95ZXVyIDNzNApuYW1lczQKMjAxOXM0CnllYXJyMAo_
2019-09-20 15:52:58,383 (708fe460) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2019-09-20 15:52:58,393 (708fe460) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1CjE1NDY5czIKaWRzMjYKU3dlZXRzaW5uZXIgLSB0aGUgVm95ZXVyIDNzNApuYW1lczQKMjAxOXM0CnllYXJyMAo_
2019-09-20 15:52:58,397 (708fe460) :  INFO (agentkit:957) - Searching for matches for {'year': '2019', 'id': '15469', 'name': 'Sweetsinner - the Voyeur 3'}
2019-09-20 15:52:58,406 (708fe460) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/library/metadata/15469/tree'
2019-09-20 15:52:58,460 (708fe460) :  INFO (__init__:46) - *******MEDIA TITLE****** Sweetsinner - the Voyeur 3
2019-09-20 15:52:58,463 (708fe460) :  INFO (__init__:53) - Getting Search Settings for: Sweetsinner - the Voyeur 3
2019-09-20 15:52:58,466 (708fe460) :  INFO (PAsearchSites:900) - mediaTitle w/ possible abbrieviation: Sweetsinner the Voyeur 3
2019-09-20 15:52:58,557 (708fe460) :  INFO (PAsearchSites:1084) - mediaTitle w/ possible abbrieviation fixed: Sweetsinner the Voyeur 3
2019-09-20 15:52:58,566 (708fe460) :  INFO (PAsearchSites:1099) - ^^^^^^^ siteID: 332
2019-09-20 15:52:58,569 (708fe460) :  INFO (PAsearchSites:1101) - ^^^^^^^ Shortening Title
2019-09-20 15:52:58,570 (708fe460) :  INFO (PAsearchSites:1102) - sweetsinner vs sweetsinner
2019-09-20 15:52:58,572 (708fe460) :  INFO (PAsearchSites:1106) - 1
2019-09-20 15:52:58,574 (708fe460) :  INFO (PAsearchSites:1161) - 7
2019-09-20 15:52:58,575 (708fe460) :  INFO (PAsearchSites:1161) - searchTitle (before date processing): the Voyeur 3
2019-09-20 15:52:58,576 (708fe460) :  INFO (__init__:63) - Search Title: the Voyeur 3
2019-09-20 15:52:58,578 (708fe460) :  INFO (__init__:72) - the%20Voyeur%203
2019-09-20 15:52:58,598 (708fe460) :  DEBUG (networking:166) - Requesting 'http://www.milehighmedia.com/en/search/the%20Voyeur%203/scene'
2019-09-20 15:52:59,397 (708fe460) :  CRITICAL (agentkit:1014) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': '2019', 'id': '15469', 'name': 'Sweetsinner - the Voyeur 3'} (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1007, in _search
    agent.search(*f_args, **f_kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 210, in search
    results = PAsearchSites.networkGammaEnt.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkGammaEnt.py", line 107, in search
    searchResults = HTML.ElementFromURL(PAsearchSites.getSearchSearchURL(siteNum) + network_sep_scene_prev + encodedTitle + network_sep_scene)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 482, in ElementFromURL
    method=method,
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, *args, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 370, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 141, in __init__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 444, in open
    response = meth(req, response)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 557, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 476, in error
    result = self._call_chain(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 96, in http_error_301
    result = urllib2.HTTPRedirectHandler.http_error_301(self, req, fp, code, msg, headers)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 652, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 438, in open
    response = self._open(req, data)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 456, in _open
    '_open', req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1225, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b9d49bdb7/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 1192, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>

**Comment by b0nensfw** [comment]
Its a Linux issues #64

**Comment by insickin** [comment]
And the Girlfriends Films issue?

**Comment by b0nensfw** [comment]
Could you provide log, I don't have any girlfriend video in my library. If not I will try to get one and test it. But is you got the:
 URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)> 

Its a Linux issues and you will have to wait for the issues to be resolved

If all three website are from the same network then its really possible that its the same issues for all three website.

**Comment by insickin** [comment]
I know that Girlfriends Films is not the same network, I am currently having Plex database issues so I can't get you a log instantly.

**Comment by b0nensfw** [comment]
Ok test it when you can (I don't have Girlfriends Film or Linux Plex so I won't be able to test it for the moment, but I will try to setup something to test it). 

If its not a problem related to Linux then please open another Issue (or look if its no already open) for Girlfirends Film only it will be easier to follow that way.

**Comment by insickin** [comment]
Ok, database problem solved! Looking at the log I think that its no problem with Linux, I will post a log in the Girlfriends Films topic #347

**Comment by innersix** [comment]
I have a question/case for this please, I am referring to the four scenes that are "released" in this movie:  (NSFW, apparently) https://www.sweetheartvideo.com/movie/4430471/the-seductive-art-of-massage

I have them in a folder 
* `SweetheartVideo - 4430471 - The Seductive Art of Massage (2021)`
  * `SweetheartVideo - 4430341 - Aiden Ashley Evelyn Claire.mp4`
  * `SweetheartVideo - 4430371 - Jane Wilde Lacy Lennon.mp4`
  * `SweetheartVideo - 4430441 - Aidra Fox Naomi Swan.mp4`
  * `SweetheartVideo - 4430491 - Kenna James Kylie Rocket.mp4`

When analyzing, three of them became merged! Is that the doing of the PhoeAdult agent or did the Plex merge that perhaps on their own? 

![image](https://user-images.githubusercontent.com/77846526/117820929-53aca400-b26b-11eb-8377-4c551934fb9f.png)

What is the intended behavior?

**Comment by DirtyRacer1337** [comment]
@innersix Plugin only provides metadata, they just was not found.
So I can suggest you rename your files to like `SweetheartVideo - 4430341 ~ Aiden Ashley Evelyn Claire.mp4` (put after after id `~`) and enable `Enable FileName Strip` in agent settings or delete actors from it
