### ISSUE TITLE
AssTraffic titles have extra spaces

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#282]
Matched scenes from 'AssTraffic' have extra spaces or tabs in the title field of Plex. This is particularly annoying because Plex sorts spaces above letters when viewing the library alphabetically. Example title:

![AwesomeScreenshot-Plex-2019-07-14-20-07-40](https://user-images.githubusercontent.com/2421939/61191755-943d3580-a673-11e9-8f66-3a3093f66804.png)

**Comment by claygoldfinch** [comment]
Resolved.
