### ISSUE TITLE
Trim 'trailer' from SML titles

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#284]
Currently, due to improper naming on Babes' website, some StepMomLessons scenes include 'trailer' at the end of the scene title. So something like [Yoga Cockfight Trailer](https://www.babes.com/scene/3111531/yoga-cockfight-trailer). I am hoping there is a way to detect and remove this from the scenes where it exists.

**Comment by d2dyno** [comment]
There is also, on rare occasion, 'SML- ' that prefixes a title. An example of that is here: [SML- Stepmommy Dearest
](https://www.babes.com/scene/4359451/sml-stepmommy-dearest)

**Comment by claygoldfinch** [comment]
Resolved.
