### ISSUE TITLE
MassageRooms seems to be title search only now

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#285]
Tried multiple times to find scene by actor, with no results returned. Title search returns result right away. Assuming this isn't a bug, the sitelist should be updated to limited

**Comment by claygoldfinch** [comment]
Looks like all of the SexyHub subsites were listed under X-Art on the sitelist. SexyHub was already listed as "Limited - Title Only" so I just moved em over. Resolved.
