### ISSUE TITLE
DDFNetwork support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#287]
I'm tying to tag "Ddfnetwork - X-Rated After Work Oral" but the agent gives "No matches"

I've tried:
Ddfnetwork - X-Rated After Work Oral
Ddfnetwork - X Rated After Work Oral
Ddfnetwork - Ella Hughes

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3391725/com.plexapp.agents.phoenixadult.log)

**Comment by blackibanez** [comment]
site change, there is no release date in search page. To fix it, we must comment the line 13 and redefine "id" (line 23) whithout "releasedate"

**Comment by claygoldfinch** [comment]
Resolved.
