### ISSUE TITLE
Get images for DadCrush

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#299]
Currently, DadCrush scraping does not grab any available images for scenes. There are 4 images we can potentially make use of:

3 - main screen 'scroll images'. These use `01-03` on a url, that contains just the actor name, which is after scene ID. for example:
`https://images.psmcdn.net/design/tour/dc/tour/pics/emma_starletto_and_mazzy_grace/hovers/01.jpg`
for the scene: 
`https://www.dadcrush.com/955/sleepover-study-and-fuck/emma-starletto-and-mazzy-grace`
Perhaps it's possible to make use of the last url part of the scene to grab images?

1 - player 'background' image on scene page. Same as the above, url uses scene actor, but in this case I can only see 1 image 'med.jpg':
`https://images.psmcdn.net/teamskeet/dc/emma_starletto_and_mazzy_grace/shared/med.jpg`

**Comment by claygoldfinch** [comment]
Closing due to site overhaul.
