### ISSUE TITLE
Clips4Sale cast/actors

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#301]
I'm adding a Clips4Sale scene, it works but it takes the name of the studio as actors instead of the real actors, can this be changed or is this fixed? 

Thanks for all the hard work!

**Comment by SgtBatten** [comment]
Just took a quick look at this.

A manual database would need to be created of all possible actors. 

The site does not list actors names from the few scenes i checked out, so pretty much not going to be done except by people who want to do their own pull requests to correct the scenes they want to match.

Someone has done a part of one already. but there must be hundreds missing. You can use it as a template and add your own.

**Comment by insickin** [comment]
Ah thanks, Coincidentally my scene has actor info but I see that it is impossible to check this for the entire site!

**Comment by SgtBatten** [comment]
@insickin if there is actor info we can make some code changes to help with those scenes. I just didn't find any so didn't think there was.
