### ISSUE TITLE
Improve HouseofTaboo search

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#302]
Currently, date is not supported, though date is listed on the search results page. In addition, many scenes will fail in the agent, such as `Houseoftaboo The Dark Room Dominator` for https://houseoftaboo.com/videos/the+dark+room+dominator/21974

**Comment by kamuk90** [comment]
Please attach the log file

**Comment by d2dyno** [comment]
Excellent work! Is the score being increased when the date matches date of search? For example, a scene with the exact date of my search, has a score of 81. Just a nitpick.

Also, it seems that the search only uses the first date, for all results. For example in this search, the second scene is actually [2018-06-31](https://houseoftaboo.com/videos/early+morning+bondage+desires/21842)
![AwesomeScreenshot-Plex-2019-07-23-21-07-77](https://user-images.githubusercontent.com/2421939/61759767-df9bc600-ad8e-11e9-8f02-861f37dc9c6a.png)

**Comment by kamuk90** [comment]
my bad, please can u update last fork and try again pls
