### ISSUE TITLE
Blacked search not working

### ISSUE THREAD

**Issue by tanman1987** [PAhelper/PhoenixAdult.bundle#308]
It seems that the plugin is getting an HTTP 403 error when processing a video for Blacked

[log.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/3428541/log.txt)

**Comment by claygoldfinch** [comment]
Can you access this on the machine your plex server is running on?

https://www.blacked.com/my-day-with-mr-m

**Comment by tanman1987** [comment]
Yes, but first I have to click through a Captcha. I tried on another machine, and I do not have to click through a Captcha. The machine running plex is behind a VPN, so that's probably why that's happening. I think it's fair to say that this is my problem and not the plugin's. Thanks.
