### ISSUE TITLE
Refreshing Metadata Not Working

### ISSUE THREAD

**Issue by PAQuestions** [PAhelper/PhoenixAdult.bundle#309]
A couple hours ago I started having this problem. I tried searching around but couldn’t find anything like it.

I’ve been adding content for my adult collection using the PhoenixAdult agent, and all was working great. Now however my Refresh Metadata button doesn’t seem to be working. Like working at all, when I click the button no spinning circle starts, nothing changes in my logs, it’s almost like the button doesn’t do anything.

I’ve tried using it in a different library and it seems to be working there.
I’ve also tried removing the content and readding it, creating a brand new library, removing and readding the agent, and clearing the cache, but none of those seem to work.

When I go to manually match the film, it allows me to find the release, but it doesn’t pull information from that.
The logs for the agent show that the information is being grabbed, but nothing after that.

Does anyone know why this is happening and if there are any solutions?

**Comment by claygoldfinch** [comment]
Can you upload or post a log file after you manually match a film?

**Comment by PAQuestions** [comment]
Sure, here are the log for the plugin and media scanner. Let me know if you need anything else.
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3428801/com.plexapp.agents.phoenixadult.log)
[Plex Media Scanner.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3428802/Plex.Media.Scanner.log)

**Comment by tanman1987** [comment]
I think I may be experiencing something similar. After I click through to fix the match, it seems that all that happens is a change to the title.
[log.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/3428901/log.txt)

**Comment by SgtBatten** [comment]
@PAQuestions your auto match example is a case of bad filename

Exxxtra small 2017-05-11 Throw Me Around Baby

should be Exxxtra small 2017-05-11 Throw Me Around Baby hence your manual matching works.

Ill look into teamskeet today Someone already has an issue open for Teamskeet #300

**Comment by claygoldfinch** [comment]
Agree with both things @SgtBatten posted:
@PAQuestions - Naming Issue
@tanman1987 - Duplicate Issue

Closing with my latest PR.
