### ISSUE TITLE
teamskeet No actress info

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#313]
After seeing that the latest update fixed Teamskeet I got to tag a scene from them, all fills except the photo/name of the actress.

The scene is: teamskeet - Dirty Hours In The Shower
[https://www.teamskeet.com/t1/trailer/view/dirty_hours_in_the_shower/lena_paul2?type=low_res&trailer=b](url)

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3432054/com.plexapp.agents.phoenixadult.log)

**Comment by SgtBatten** [comment]
Hmm works for me. Ill compare my code to the master

**Comment by claygoldfinch** [comment]
Looks to be an issue with PAExtras

**Comment by SgtBatten** [comment]
fixed that just now.
