### ISSUE TITLE
Odd behavior on automatch of some spizoo scenes

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#316]
I am not even sure if this is an 'agent' bug, but on some spizoo scenes I had scanned in recently, there were all lowercase titles, with a description that just says 'this video is about xyz'. None of them are actually matched (as Plex shows 'match' instead of 'fix match'), so I am not sure where they are pulling this information from. Attaching a screenshot (blurred to make sfw), and xml of one of the scenes in question.

![AwesomeScreenshot-Plex-2019-07-25-20-07-83](https://user-images.githubusercontent.com/2421939/61919364-f4a56000-af1a-11e9-9b41-397e6b7f42ad.png)

[XML](https://0bin.net/paste/SzXiohbAtsyqCohN#XImRRAtHaAmrFw5QoO6apTbVWsPQwIJew0tGWh6OfAf)

**Comment by SgtBatten** [comment]
depending on how you order the agents in your plex server its coming from the metadata in the file itself or from the folder/file name

**Comment by d2dyno** [comment]
Do I need to disable local altogether?
![AwesomeScreenshot-Plex-2019-07-25-20-07-93](https://user-images.githubusercontent.com/2421939/61919780-bb6def80-af1c-11e9-88d6-05d9fdfd85c4.png)

**Comment by SgtBatten** [comment]
I think that may result in the file or folder name being used. But i'm not 100%

**Comment by claygoldfinch** [comment]
https://support.plex.tv/articles/200220677-local-media-assets-movies/

My guess is that all that info is being pulled from metadata. I occassionally get weird file names and even actors added to unmatched files due to file metadata. Disabling Local Media Assets should prevent that from happening.
