### ISSUE TITLE
SisLovesMe has 6 duplicate images for posters

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#323]
As said in title, matching SisLovesMe has 6 of the same images in main poster selection screen.

**Comment by SgtBatten** [comment]
Only for some scenes. It depends on two things.

If we cannot find any fanart image sets it will try to add any bio pics on sislovesme as a backup. 

For some actresses that have more scenes there is variety in these 6 images. For actresses with only 1 or two scenes there will definitely be some repetition. I can investigate if there is any that will always give a duplicate and set them to only get it if the first one fails but i think for the most part they are all useful for some actresses making it hard to pick and choose.

**Comment by SgtBatten** [comment]
Fixed
