### ISSUE TITLE
ManyVids support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#325]
I'm trying to tag a ManyVids scene but it fails.
The scene that I'm trying to tag is: ManyVids - Tuesday Night Orgy (https://www.manyvids.com/Video/851036/tuesday-night-orgy/)

I'm using the search term: 
ManyVids - 851036

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3439065/com.plexapp.agents.phoenixadult.log)

In the log I'm seeing:
URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>

Is this because I'm running Plex on a Linux server or is it (hopefully) something else?

**Comment by raedwulf83** [comment]
Should be a Linux issue 
works for me on a Windows Plex Server, not on my Synology

**Comment by insickin** [comment]
Ah, thanks for the info, that's too bad...

**Comment by claygoldfinch** [comment]
Yep, appears to be a Linux issue. I'll tag it and close this issue.

Issue #64
