### ISSUE TITLE
Karups support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#331]
I'm trying to tag: Karups - Sinn Sage Amber Rayne
https://www.karups.com/video/sinn-sage-amber-rayne-53297.html

But it returns with: Nothing found whatever combo i do.

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3456515/com.plexapp.agents.phoenixadult.log)

**Comment by d2dyno** [comment]
You need to search with the correct subsite. In this case, that is `karupsha`. Additionally, you should only put 1 actor name into the search, so as not to confuse the search. I successfully searched using `karupsha amber rayne` for example.

**Comment by insickin** [comment]
Aha, that helped! I tried it with 1 actor but it didn't work (Karups - Amber Rayne) than I tried it with karupsha - Amber Rayne and it worked.

I thought that because there is only Karups in the list (https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/sitelist.md) I had to use "karups -", ​​learned something again!
