### ISSUE TITLE
RealityKings has updated it's site layout

### ISSUE THREAD

**Issue by d2dyno** [PAhelper/PhoenixAdult.bundle#335]
Using same layout as Mofos/Babes/etc. Needs to be converted to SceneID only.

**Comment by claygoldfinch** [comment]
Both are under the Reality Kings portfolio, so going to close this and leave the Reality Kings issue open.

**Comment by d2dyno** [comment]
@claygoldfinch did you close the correct one? Did I not see another reality Kings issue?

**Comment by claygoldfinch** [comment]
Oops, wrong one haha. Reopening and closing #333.

**Comment by SgtBatten** [comment]
#338
