### ISSUE TITLE
Twistys Support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#337]
I am trying to tag: Twistys - Fix Her, Up Her but the agent can't find the scene.
I've tried searching with:
Twistys - Fix Her, Up Her
Twistys - 3406841

I've restarted my Plex server.

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3457604/com.plexapp.agents.phoenixadult.log)

**Comment by d2dyno** [comment]
remove the dash. Tested just now and it worked as `Twistys 3406841`

**Comment by insickin** [comment]
I tried it with Twistys - 3406841 but it still finds nothing!

**Comment by claygoldfinch** [comment]
Tried it myself and was still running into issues after multiple server restarts. My latest PR creates an exception for that one scene, give it a shot.
