### ISSUE TITLE
Girlfriends Films Broken

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#347]
I am trying to add my Girlfriends Films collection but the agent finds nothing.

I have tried searching with:
GirlfriendsFilms - sceneID 
GirlfriendsFilms - Actor name
GirlfriendsFilms - Scene/DVD name

Nothing works!

Example:
GirlfriendsFilms - Newswomen 4 - scene 1 tried with:
GirlfriendsFilms - 134608
GirlfriendsFilms - Prinzzess or Penny Pax
GirlfriendsFilms - Newswomen 4

Many films / scenes are also missing on www.girlfriendsfilms.com where if I see correctly in the logs the agent searches, whole films can be found on www.girlfriendsfilms.net 

For example; A FANtasy can't be found on girlfriendsfilms.__**com**__ but on girlfriendsfilms.__**net**__ you can find it (https://www.girlfriendsfilms.net/1746426/fantasy-a-porn-videos.html) (ok the whole film, not the loose scenes but its more than nothing!)

I have included a log:
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3473071/com.plexapp.agents.phoenixadult.log)

**Comment by insickin** [comment]
Nobody who can help me with this?

@claygoldfinch
@SgtBatten
@PAhelper

**Comment by claygoldfinch** [comment]
Part of the Gamma Entertainment network. So likely broken just like EvilAngel, Nuru Massage, etc.

**Comment by insickin** [comment]
Thanks for picking this one up! Hopefully it will be resolved soon!

**Comment by pedrolara-boop** [comment]
Any news about a fix?

**Comment by insickin** [comment]
@b0nensfw 

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3637938/com.plexapp.agents.phoenixadult.log)

See also the first post of this topic

**Comment by pedrolara-boop** [comment]
The first error is on
https://github.com/PAhelper/PhoenixAdult.bundle/blob/70d50a705923315d21079f4872e956e7460faa27/Contents/Code/networkGammaEnt.py#L74

Changing from "&tab=movies" to "?query=&pscenes=0&tab=movies" will fix the search error.

However, the site is relatively different than other gamma network sites.

[@class="tlcDetails"] might be [@class="itemInfo  from-girlfriendsfilms"]
[@class="tlcTitle"]  to [@class="itemTitle"]
[@class="tlcActors"] to [@class=""itemActors"]

Is there a quick way to run a prototype of these changes without breaking networkGammaEnt.py?

Here is the log:

> 
2019-10-06 13:14:57,595 (7fe490f3b700) :  ERROR (networking:219) - Error opening URL 'http://www.girlfriendsfilms.com/en/search/Jade%20Nile%20Lola%20Fae%20Bad%20Lesbian%2010&tab=movies'

**Comment by insickin** [comment]
Can you make a pull request from/with your fix to fix this problem?

**Comment by pedrolara-boop** [comment]
I haven't fixed it. I once I have some free time I will try to make a siteGirlfriends.py and redirect the search to the file for testing.
Someone with more codding experience could probably add directly to the networkGammaEnt.py.

**Comment by pedrolara-boop** [comment]
I don't think I'm going to be able to fix the scrapping part, hopefully some of the devs could help us out it's been almost 3 months.

However, I believe I was able to fix the search terms on line 71 to 73:

https://github.com/PAhelper/PhoenixAdult.bundle/blob/70d50a705923315d21079f4872e956e7460faa27/Contents/Code/networkGammaEnt.py#L71

        network_sep_scene = "?query=" + encodedTitle + "&tab=scenes"
        network_sep_scene_pages = "?query=" + encodedTitle + "&pscenes="
        network_sep_scene_pages_next = "&tab=scenes"
        network_sep_dvd = "?query=" + encodedTitle + "&tab=movies"

**Comment by claygoldfinch** [comment]
It's on the to-do list. Tough to make changes to networkGammaEnt without the possibility of breaking another site.

**Comment by pedrolara-boop** [comment]
That's great to hear. I found especially hard to help because I end up messing with the other sites.

**Comment by insickin** [comment]
You can't make it "stand alone"?

**Comment by claygoldfinch** [comment]
That's the ultimate goal - seperate it into individual sites, or at least smaller networks. I could do a quick fix for one site, but that would leave it a bigger mess for the next person to touch it (probably me).

**Comment by insickin** [comment]
Is someone still working on this one?

**Comment by insickin** [comment]
Has someone booked progress with this problem? @claygoldfinch maby?

**Comment by insickin** [comment]
So with the latest pull request from @claygoldfinch #550 some problems are relatively solved, girlfriendsfilms.com is searchable and taggable but (as mentioned by me in response of the pull request) for much whole DVD releases there sill remains a problem namely: or the release can't be found on the .com site and or the description +  release date is incorrect on the .com site.

There is the site https://www.girlfriendsfilms.net that has all of the full DVD releases + correct description/release date info (but lacks cast info)

Is there anyone who can integrate the .net site for searches for Girlfriends Films?

**Comment by claygoldfinch** [comment]
Merged into Issue #1
