### ISSUE TITLE
PassionHD and FantasyHD not working

### ISSUE THREAD

**Issue by pahelper3** [PAhelper/PhoenixAdult.bundle#35]
Hi,
if you add a clip from PassionHD or FantasyHD and you name this way:
`PassionHD - <name of the clip>` or `Passion-HD - <name of the clip>` the agent searches the clip for all of the networks without results. You need to remove the dash in the PAsearchSites.py to make it work with its plugin.

Secondly, when you do that, an SSL handshake error occurs, which is the same faced with EmpireX websites, as reported here: #13

**Comment by PAhelper** [comment]
I will remove the dash, and try explicitly loading those sites in http. They are part of the PornPros network is sites which actually cover a bunch of sites I use regularly...

**Comment by PAhelper** [comment]
I've made the change you suggested, but can't test right now.

**Comment by PAhelper** [comment]
Dang, so they must redirect to HTTPS in the webserver software, and not in the page itself. Alright, Looks like we'll have to go with Plan B on this one... find another Python function to pull the https data with that's ok with ssl v3.

**Comment by mutluerol** [comment]
additioanl PornPros same error

**Comment by PAhelper** [comment]
Merging this into #13
