### ISSUE TITLE
litte xpath help

### ISSUE THREAD

**Issue by ferengi82** [PAhelper/PhoenixAdult.bundle#351]
i'm adding clubseventeen, the metadata is working, but i have a problem with the poster image:

examplesite: https://www.clubseventeen.com/video.php?slug=all_inside_the_family_ep5_morning_breakfast_ends_up_with_pussy_eating

my code: twitterBG = detailsPageElements.xpath('//div[@class="ratio-16-9 video-item static-item progressive-load loaded"]')[0].get('data-image')

what am I doing wrong ?

the complete code can be found here: https://github.com/ferengi82/PhoenixAdult.bundle/tree/clubseventeen

**Comment by kamuk90** [comment]
you looking JS generated div
this code will work fine
```
//div[@Class="ratio-16-9 video-item static-item progressive-load"]
```

**Comment by kamuk90** [comment]
Just disable javascript in you browser and look html code

**Comment by ferengi82** [comment]
looks good, thank you
