### ISSUE TITLE
NubilesNET scene description

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#357]
I see that on https://nubiles.net/ there is a scene description present but the agent doesn't tag it can this be changed?

For example:
https://nubiles.net/video/watch/81637/dripping-wet has a description.

**Comment by insickin** [comment]
@claygoldfinch Does this also work on all of the other Nubiles websites? Like for example: https://anilos.com have scene descriptions available.

**Comment by claygoldfinch** [comment]
Yep, should work with all [Nubiles-Porn](https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/sitelist.md#nubiles-porncom-network--matching-type-exact---sceneid) and [Nubiles Network](https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/sitelist.md#other-nubiles-sites--matching-type-exact---sceneid) sites!

**Comment by insickin** [comment]
Ok, thanks! Hopefully your Pull Request gets incorporated fast in the main release!

**Comment by claygoldfinch** [comment]
Just merged it in, give it a shot!

**Comment by insickin** [comment]
As far as I can test it works! Thanks!
