### ISSUE TITLE
SexArt Metadata not pulling...

### ISSUE THREAD

**Issue by allegedschool** [PAhelper/PhoenixAdult.bundle#361]
Hello! 
Metadata from SexArt is not pulling. I've tried many different naming conventions. Weird thing is that MetArt Metadata pulls just fine from download file title...
Some examples of naming conventions I tried....
- SexArt_mango_girls-love-sex
- sexart - 123farenheit
- SexArt Luna
- Draw-Me_SexArt

What am I doing wrong? Thank you!

**Comment by claygoldfinch** [comment]
Not doing anything wrong. Site updated and we haven't gotten around to fixing it just yet. Affecting VivThomas and MetArtX as well (see Issue #243).
