### ISSUE TITLE
Sweet Sinner/Sweetheart Video Broken

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#376]
I am trying to add a movie from Sweet Sinner but the agent keeps responding with: Nothing Found.

The movie is: "Different Wives, Different Lives"https://www.sweetsinner.com/en/dvd/Different-Wives-Different-Lives/76032

Looking in the log I am seeing the dreaded SSL: SSLV3_ALERT_HANDSHAKE_FAILURE error... Hopefully someone can fix this!

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3531406/com.plexapp.agents.phoenixadult.log)

**Comment by insickin** [comment]
Also Sweetheart Video DVD's/scene's are not found.

**Comment by pedrolara-boop** [comment]
It's a strange error. I was getting the same search error sweetheartvideo for a long time, now it's working. However, the search quality is really low since it pulls everything from milehighmedia.
The error returned but got fixed after a Plex restart.

**Comment by pedrolara-boop** [comment]
@insickin Are you still having issues?

**Comment by insickin** [comment]
Tested it, It seems that the agent finds (and tags) the scene's once more! I thought because it displayed the "SSL: SSLV3_ALERT_HANDSHAKE_FAILURE" error that it wasn't fixable, nice that its working now!
