### ISSUE TITLE
CreampieAngels not pulling actors correctly

### ISSUE THREAD

**Issue by dkmontague** [PAhelper/PhoenixAdult.bundle#377]
CreampieAngels site pulls the below "Royal-Cash.com" for the videos instead of actors

![image](https://user-images.githubusercontent.com/23252487/63549263-ed0ab400-c4e4-11e9-80b8-e7cb7dbda4b2.png)

**Comment by claygoldfinch** [comment]
All that info is being pulled from file metadata. Try manually matching.
