### ISSUE TITLE
newsensations question

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#385]
More a question than a issue, does this mean that newsensations is fixed? Because I still can't match file's from them. If nothing is fixed never mind this question!

https://github.com/PAhelper/PhoenixAdult.bundle/commit/f0fe9ddef9e4986eec320ab9f1de5b7e414564cb

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3556114/com.plexapp.agents.phoenixadult.log)

**Comment by aicha1566** [comment]
Sort of... Hi I'm the one who made that pull request. This might be more of a problem with the specific search you're using. I noticed that some older DVD's don't contain scenes on their site. In other words, for your search "Newsensations the Beautiful Solo 2" you'd want to match this: https://www.newsensations.com/tour_ns/dvds/TheBeautifulSolo2.html but the script is unable to find any scene details.

**Comment by chempke** [comment]
@aicha1566 what about individual scenes? I'm not sure how to handle it. The sidelist.md says Matching type: Exact - DirectURL

So, if i try this scene for example:
*https://www.newsensations.com/tour_ns/updates/Shaking-Harley-Jade-Juicy-Big-Booty.html*

Naming the file like:
`Site Name` `Direct URL` gives no results
NewSensations - Shaking-Harley-Jade-Juicy-Big-Booty.html or
NewSensations - Shaking-Harley-Jade-Juicy-Big-Booty 

`Site Name` `Actor` finds the scene
NewSensations - Harley Jade

`Site Name` `Date` `Actor` finds scene but date won't added

am I doing something wrong with my naming or is the sitedlist.md not up to date?

**Comment by insickin** [comment]
Thanks @aicha1566 that's working for me!

@chempke I tagged "NewSensations - Dee Has A Confession To Make" https://newsensations.com/tour_ns/updates/Big-Tit-MILF-Dee-Williams-Has-A-Confession-To-Make.html with the combo: NewSensations - Big-Tit-MILF-Dee-Williams-Has-A-Confession-To-Make (This is a single scene, I've not tried DVD's)
