### ISSUE TITLE
Girlsway Poster support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#39]
I am having trouble to get posters for some Girlsway scenes to be precise: 
Girlsway - Crush On Mommy 
Girlsway - The Pick-Up Artist
Girlsway - Last-Minute Christmas
Girlsway - Finally Home
Girlsway - Showcases: Alina Lopez - 2 Scenes in 1

**Comment by PAhelper** [comment]
Downloading what I can find, will test...

**Comment by PAhelper** [comment]
Oh yeah, I forgot. I couldn't find any good source of poster images for Girlsway. From the scene page (https://www.girlsway.com/en/video//Crush-On-Mommy-Scene-01/135099) There is basically no image to pull except for the one background image where the trailer video sits, and I am pulling that one as a background art. It's easy enough to also download that same image as poster art as well, but other than that single image, I couldn't find anything else to pull...

**Comment by insickin** [comment]
Oke thanks now I am getting a image for the posters (I don't like when I get black/grey no posters in my library, you know, every thing must be nicely tagged!) 

PS: Have you looked at this problem: https://github.com/PAhelper/PhoenixAdult.bundle/issues/28
