### ISSUE TITLE
[Feature Request] LAMBDA Support

### ISSUE THREAD

**Issue by PAQuestions** [PAhelper/PhoenixAdult.bundle#390]
Not sure if this is the right place to even ask this, but I was wondering if it's possible to have support for LAMBDA.

I've added LAMBDA to the PhoenixAdult agent, and I've gotten .nfo files to download. My problem is with files that are added and the .nfo that are associated with them.

My problem is that the .nfo isn't populated with the correct information. It seems like the information is taken before being fully downloaded.
Title would be => HE COULDN'T HOLD BACK AND CUMS INSIDE [ManyVids/LittleReislin]

If you refresh the metadata once everything is downloaded, everything works properly.

Is there anyway to fix this?

**Comment by SgtBatten** [comment]
Might help to explain or link to what LAMBDA is

**Comment by PAQuestions** [comment]
Sorry about that.

LAMBDA is a Plex agent that creates and uses local metadata.

Here is the Github. https://github.com/ZeroQI/Lambda.bundle
