### ISSUE TITLE
GangBangCreampie Not Working

### ISSUE THREAD

**Issue by dkmontague** [PAhelper/PhoenixAdult.bundle#392]
There are no matches when searching for gangbangcreampie.com scenes - it appears to not be working at all

**Comment by claygoldfinch** [comment]
Log?

**Comment by b0nensfw** [comment]
@dkmontague  could you provide the logs from com.plexapp.agents.phoenixadult.log after trying to match a video which is failing.

On my side the integration is working

To get the file in Windows :
%userprofile%\AppData\Local\Plex Media Server\Logs\PMS Plugin Logs

**Comment by dkmontague** [comment]
I think its actually a naming issue - i thought it would treat episode numbers as title.  Looks like have to use girls name. "gangbangcreampie - danica - 965" doesnt work but "gangbangcreampie - danica" works.

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3638245/com.plexapp.agents.phoenixadult.log)
