### ISSUE TITLE
Runtime Error R6034 when using this plugin on Windows 10

### ISSUE THREAD

**Issue by hdkiller** [PAhelper/PhoenixAdult.bundle#393]
Hello!

When this plugin activates by scraping metadata Plex sometimes throws the following error:

Runtime Error!
R6034
An application has made an attempt to load the C runtime library incorrectly. 

[![Screenshot from Gyazo](https://gyazo.com/58e7a82812eaab204f83cbf9fe8ef2d8/raw)](https://gyazo.com/58e7a82812eaab204f83cbf9fe8ef2d8)

I was trying to solve this problem, by removing python path from the environment settings, also by checking with process explorer if a wrong dll is loaded. But seems like my windows skills are not good enough to figure out this at my own.

Then you very much!

**Comment by claygoldfinch** [comment]
Not related to the agent, you should try repairing your Plex install.

**Comment by hdkiller** [comment]
Hello!

I was finally had time to dig deeper into the problem.

I had to install PIL-1.1.7.win-amd64-py2.7 then copy the PIL directory from c:\Python27\Lib\site-packages\PIL to Contents\Libraries\Shared\PIL
