### ISSUE TITLE
Karups support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#395]
I am trying to tag: "Karups Older Women - Convincing the Coach" https://www.karups.com/video/dee-williams-convincing-the-coach-50754.html but the agent finds no scene...

I've tried it with a few combinations like:
Karups Older Women - Convincing the Coach
Karups Older Women - Dee Williams
Karups - Dee williams

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3579812/com.plexapp.agents.phoenixadult.log)

**Comment by claygoldfinch** [comment]
Try `KarupsOW - Dee Williams`

**Comment by insickin** [comment]
Thanks, that did the trick!
