### ISSUE TITLE
Can somebody push the open Pull requests? / Give tips for adding site's?

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#397]
Like the title says: Can somebody push the open Pull requests? 

And is it me or has it become quiet here, maybe it's the summer vacation? The last month not to many updates or new site's added (not that it's mandatory to work on this project... And all probs for all the coders this far on the agent!) 

I wish that I could do maintenance/code new sites, if someone has tips on how/learn with codelanguage to do that please note them!)  But I dread to see this fine project go to waste!

**Comment by SgtBatten** [comment]
I had never used python 6 months ago. I just read the code and tried to play with a new site. Eventually I worked it out. Took a bit of time but it fairly straight forward once you know how it works. 

Provided the code was usable on a given site you could add a new site in 20-30 mins easy once you get the hang of it.

**Comment by insickin** [comment]
Thanks for the tips @SgtBatten much appreciated, I'm going to try to add a site, or do you know of a easy already added site to take a try at it, to get a hang off it?

**Comment by claygoldfinch** [comment]
Hoping to be a bit more active around here soon. Been busy with the start of classes and moving, plus suffered some data loss that pushed contributing to the backburner. 

Straplezz was a relatively easy site that I added. Check out the template file, as well.

**Comment by insickin** [comment]
@claygoldfinch Good to have you back! Hopefully you've got most of your data back, data loss seems like a nightmare! (Need to get working/thinking on a back-up plan...)

Next week I have a week of vacation, then I want to try to add a site. I will take a look at the Straplezz and the template file. I know that there is also info in the wiki, if I have any questions I will ask them here!

Thank you very much for this information!

**Comment by insickin** [comment]
Is the wiki still up to date? I see that there is some info/help on adding sites

**Comment by b0nensfw** [comment]
@claygoldfinch  Maybe close this issue 

You have the info to add site here : https://github.com/PAhelper/PhoenixAdult.bundle/wiki

And @claygoldfinch is pushing the open Pull Request
