### ISSUE TITLE
Hardcoding missing (and unchanging) data

### ISSUE THREAD

**Issue by PAhelper** [PAhelper/PhoenixAdult.bundle#4]
A few of the new sites I've added don't have genre or category lists to accompany their videos, so the genres have to be manually generated. A couple of mine are pretty sparse and can be improved. For example, count the number of "Actors" and add "1 on 1", "Threesome", "Foursome", etc. genres where appropriate...

**Comment by PAhelper** [comment]
This same concept can work with actors in some cases as well. For example, pretty sure the male talent on TrueAnal is always Mike Adriano. He's not credited on the scene page, only the female actresses are, but he could be manually added to all TrueAnal scenes in the code...

**Comment by PAhelper** [comment]
And apparently all the Xempire sites are directed by "Mason"? So that can be hardcoded...

**Comment by PAhelper** [comment]
Vixen/Blacked/Tushy all from directory "Greg Lansky"

**Comment by insickin** [comment]
Many or all of the Girlsway's site's (Girlsway/Mommy's Girl/Web Young/Girls Try Anal) are directed by "Stills By Alan"

**Comment by PAhelper** [comment]
I've added Mike Adriano to TrueAnal/Swallowed/Nympho, and added all these directors. Still need to get some of the genres before I can close this.

**Comment by PAhelper** [comment]
Alright, I went through and hardcoded genres where I could. Closing this issue.
