### ISSUE TITLE
Debugging/Testing During Development

### ISSUE THREAD

**Issue by degeneratesmut** [PAhelper/PhoenixAdult.bundle#401]
Feel free to close if this isn't the right place.

Can anyone tell me how they debug/test changes to the scraper? Currently I'm stuck just pressing "refresh metadata" and hoping the changes I made work.

I'd love for there to be a way to step through things to catch my errors and help me understand how things interact better.

Thanks.

**Comment by insickin** [comment]
You can use "unmatch" and then you can "re-"match your scene and can see if for example photo's now load.

**Comment by claygoldfinch** [comment]
Agent log files. Should tell you exactly which line of code failed and why.

**Comment by degeneratesmut** [comment]
Cool, I'll take a look. Also props to you and all the other contributors. Looks like this has improved significantly since I last updated it.
