### ISSUE TITLE
[Feature Request] Ignore Portions of File Name

### ISSUE THREAD

**Issue by degeneratesmut** [PAhelper/PhoenixAdult.bundle#407]
**Use Case** 
Sites require specific naming conventions for auto-match.
`FemdomEmpire - YYYY-MM-DD - SceneTitle` results in an auto-match
`FemdomEmpire - YYYY-MM-DD - SceneTitle - Star Name` does not result in a match
This would be helpful for exact match websites as well

I would like to keep Star Name in all my file names, but have it be ignored by the scraper so that I don't need to manually match everything

**Questions**
Is this possible to implement, and how complex might this be? 
I'm generally familiar with the process to add sites, but unclear about the rest of the scraper.

**Comment by SgtBatten** [comment]
Putting the name in brackets will ignore it i think
