### ISSUE TITLE
Issues need a good cleanup

### ISSUE THREAD

**Issue by b0nensfw** [PAhelper/PhoenixAdult.bundle#411]
@PAhelper @claygoldfinch 

Hi, I would really like to help update the code and fix some problems, but a lot of issues are duplicated, old issues that have been fixed. Could I get the right on the project to manage issues and try to clean it up.

Tks!

**Comment by claygoldfinch** [comment]
I agree, I think having someone who can focus on cleaning up open issues would be nice. That said, I'm not quite sure how permissions work for this project. I believe all collaborators that have been added are limited to closing issues and merging pull requests - so it'd be up to @PAHelper to add new collaborators. 

If it's possible, perhaps we should start looking into a way to vet new collaborators? First with permissions to close issues, and later with the ability to merge pull requests?
