### ISSUE TITLE
Evil Angel

### ISSUE THREAD

**Issue by yes12397** [PAhelper/PhoenixAdult.bundle#42]
1 -All titles after 2016 are working fine  because they name the files with different names.
all productions before 2016 works as follow:
xxxmovie, scene#1
xxxmovie, scene#2
xxxmovie, scene#3

so while searching results will show as:
xxxmovie [Evil Angel]
xxxmovie [Evil Angel]
xxxmovie [Evil Angel]

so u have to check manually  to see if the movie will pair with the scene # 

2- Some times results of BTS and Outlooks doesnt show.
3- special characters such as ( / : ) not recognized in the search while its there in the title name

**Comment by PAhelper** [comment]
I think this is basically the same request as #28. I'm planning to combine all of these sites together in a single file soon, so when I add support for movies and BTS and so forth on one site, it should work for them all...

**Comment by PAhelper** [comment]
Merging into #28
