### ISSUE TITLE
Post-processing Documentation

### ISSUE THREAD

**Issue by pedrolara-boop** [PAhelper/PhoenixAdult.bundle#432]
It looks like a quite cool feature hidden under the folders.

Where can I find more information about the post-processing? What does it do? How to setup? Is it only for windows?

The information is quite vague with "point sabnzbd to this file" and some example with folders that doesn't tell you how you should correctly do it. 

Thanks

**Comment by SgtBatten** [comment]
I'll push the post processing branch to master now. There's a readme in there

**Comment by pedrolara-boop** [comment]
Thanks, I will check out and try!
