### ISSUE TITLE
NewSensations missing Poster/Background image + missing release date

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#434]
Like the title say's when tagging NewSensations scene's I am missing Poster/Background image and missing a release date.

I've included a log:

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3702581/com.plexapp.agents.phoenixadult.log)

Or it picks the DVD cover for the poster off which the scene comes.

Log:

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3702661/com.plexapp.agents.phoenixadult.log)

**Comment by claygoldfinch** [comment]
- Missing a release date is normal - scenes are Date Add only. 
- Missing a background image isn't normal - just pushed an update to the agent.
- Using the DVD cover as the Plex poster image for scenes is normal. Can be changed, but IMO was a better fit than the background image.

**Comment by insickin** [comment]
From my memory the Poster was from the scene not the DVD cover but I can be wrong :stuck_out_tongue_winking_eye: , can't you make it so we can choose for our self?

**Comment by insickin** [comment]
Oke, testing this, now I'm getting a background but no poster

**Comment by insickin** [comment]
Oke, tested it, for some strange reason when I match a scene I don't get straight away a background, I must manually choose one (because the first doesn't load?) ( this is not with all scene's, some load the first time correctly)

And 1 scene "A Special Guest For Gabbie" doesn't load a poster.

**Comment by claygoldfinch** [comment]
Try unmatching, clearing bundles, and then rematching. "A Special Guest For Gabbie" doesn't load a poster because it doesn't have a related DVD. I can certainly add in some code to add the background as a possible poster!

**Comment by insickin** [comment]
I changed it (choose the second image) manual for the scenes that didn't load the background automatically so that's not really a problem anymore.

If you can add that code...
