### ISSUE TITLE
XEmpire is not working

### ISSUE THREAD

**Issue by WilliamsVM** [PAhelper/PhoenixAdult.bundle#438]
I think XEmpire broke their search. All the searches seem to be returning the same results. Appears to be the latest scenes? I did get the newest scenes (released in the past 3 months) I have from them to match but everything else returns only unrelated scenes.

**Comment by chempke** [comment]
Can you give an accurate example? 
Everything works as it should for me

**Comment by WilliamsVM** [comment]
This is the match result I get when trying to match "Darkx - Getting Over Her Fear of Heights - Piper Perri - 2015-10-23 - 78863"
![XEmpireNotMatching](https://user-images.githubusercontent.com/40531925/66694650-c31f7380-ec83-11e9-9f94-b20304c3810e.PNG)

**Comment by WilliamsVM** [comment]
I get similar results for all but the most recent scenes. I tried different naming schemes as described in the docs as well and none of them worked. If you have a naming scheme that is functional I'd love to get a sample

**Comment by claygoldfinch** [comment]
Title Search seems pretty iffy for this scene. Try a mix of Actor Search with Date Match.

`Darkx - 2015.10.23 - Perri Piper`

Date always needs to be before the title/actor.

**Comment by WilliamsVM** [comment]
Ok I've got myself sorted. I think I've been working on this a bit too much recently and my brain is a bit frazzled after grinding away on matching 3k+ files this week. It works fine when I get the syntax right
