### ISSUE TITLE
Teamskeet missing Poster/Background

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#439]
Like the title say's I am missing Poster/Background images when tagging TeamSkeet scene's

**Comment by claygoldfinch** [comment]
Have a log? Tried a few recent scenes and it seems to be working for me.

**Comment by insickin** [comment]
I think that my pi-hole (ad blocker) was blocking the image server off Teamskeet, now I have whitelisted it it gets the images!

**Comment by insickin** [comment]
I am back, when tagging: "Dyked - From Now On You Are My Bitch" https://www.teamskeet.com/t1/trailer/view/from_now_on_you_are_my_bitch/alexis_and_elsa?type=low_res&trailer=a
I only get a poster no background.

**Comment by claygoldfinch** [comment]
No issues scraping here. Based on your log, looks like your search term was "Teamskeet Network From Now on You Are My Bitch". Try changing to "Teamskeet From Now on You Are My Bitch" or "Dyked From Now on You Are My Bitch".
