### ISSUE TITLE
[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE]

### ISSUE THREAD

**Issue by mutluerol** [PAhelper/PhoenixAdult.bundle#44]
sitePornPros has error with ssl

**Comment by mutluerol** [comment]
in my PMS Plugin Logs, ifound ;
URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>

**Comment by PAhelper** [comment]
Duplicate of #13
