### ISSUE TITLE
Fallback to using directory names?

### ISSUE THREAD

**Issue by tritnaha** [PAhelper/PhoenixAdult.bundle#443]
It seems that many older scene-releases do not contain the site-name in the filename, like 1000Facials.13.01.07.Tanner.Cruz.XXX.1080p.MP4-KTR/ktr.1kf.13.01.07.tanner.cruz.mp4

I can manually match this correctly, but it´d be lovely if the script would fall-back to directory name/s if possible. I´ve seen this "issue" for around 30 or so different sites, regardless of release-group - here´s a small list of sites that have issues matching older releases

1000Facials
`1000Facials.13.01.14.Aria.Austin.XXX.1080p.MP4-KTR/ktr.1kf.13.01.14.aria.austin.mp4`

DigitalPlayground
`DigitalPlayground.18.10.08.Rharri.Rhound.Coaxing.A.Cuntfession.XXX.1080p.MP4-KTR/dpg.18.10.08.rharri.rhound.coaxing.a.cuntfession.mp4`

PublicAgent
`PublicAgent.18.09.27.Amina.Danger.XXX.1080p.MP4-KTR/pba.18.09.27.amina.danger.mp`4

SinfulXXX
`SinfulXXX.18.10.11.Sienna.Day.XXX.1080p.MP4-KTR/sinful.18.10.11.sienna.day.mp4`

I do know that the searchsites-function _should_ be able to match them regardless, but if the filenames are obfuscated it´ll fail without using dirname instead.

**Comment by claygoldfinch** [comment]
The agent actually already has a system in place for resolving this - it'll recognize scene "short names" and swap them for the full site name when searching.

Here's the list of all the short names the agent currently recognizes:
https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/Contents/Code/PAsearchSites.py#L900

If you're experiencing issues with specific scenes feel free to post logs so we can figure out what exactly went wrong.

**Comment by SgtBatten** [comment]
Might want to look at the postprocessing script too.
