### ISSUE TITLE
PervMoM dubble site's

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#444]
I have problems tagging some of my PervMoM scene's.

The problem is that some of their scene's are not listed on the site that the agent scrapes (www.pervmom.com) for this studio but these scene's are listed at https://mypervmom.com

At www.pervmom.com they list scene's that are stitched together (for example 3 scene's of a actress are stitched to 1 scene) and at https://mypervmom.com they are listed separate, can it be made so that the agent also scans https://mypervmom.com?

For example:
There is only 1 scene from Lily Lane on www.pervmom.com (https://www.pervmom.com/831/girl/lily-lane)
But on https://mypervmom.com there are 3 (https://mypervmom.com/tag/lily-lane/)

**Comment by insickin** [comment]
Is this the fix for this problem? https://github.com/PAhelper/PhoenixAdult.bundle/commit/73d94dbb2f0cf9d16a09294e493a8d5b0d14f599

**Comment by claygoldfinch** [comment]
Merged into Issue #1.
