### ISSUE TITLE
GammaNetwork - Error when using comma on search terms

### ISSUE THREAD

**Issue by pedrolara-boop** [PAhelper/PhoenixAdult.bundle#448]
Performing a search using a comma in any part of the search terms on GammaNetwork websites results in an error.

`Sweet Sinner` `Different Wives, Different Lives`

The error might not be in the code but on the website itself. You get a "Page Not Found" if you search for something with a comma. So far, I could only find this error for GammaNetwork sites. Tested on Windows and Linux.

It is probably quite rare to occur, but a safeguard might be needed to fix it.

**Comment by pedrolara-boop** [comment]
Might be the error that affected #376

**Comment by insickin** [comment]
When I see that there are comma's in titles I try to get rid of them (so for example `Sweet Sinner - Different Wives, Different Lives` becomes `Sweet Sinner - Different Wives Different Lives` or `Sweet - 76032`

> 
> 
> Might be the error that affected #376

I had a problem with all title's (not only the title's that contained comma's)
