### ISSUE TITLE
Evil Angel full DVD support 

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#451]
I see that we can tag scene's from Evil Angel but I can't get the agent to tag full DVD releases.

For example I'm trying to tag: "Evilangel - I Am Angela", non of the combo's given in #414 work, in the log I see that the agent searches via https://www.evilangel.com/en/video/ for full DVD releases their site uses  https://www.evilangel.com/en/movie/ so the difference is "/video/" "/movie/" 

[Log.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/3746980/Log.txt)

**Comment by insickin** [comment]
Any news on this one?

**Comment by dappleyard** [comment]
I'm struggling to match any Evil angel videos or movies. Is there any special naming convention, since the direct url from the site does not seem to work

**Comment by claygoldfinch** [comment]
> 
> 
> I'm struggling to match any Evil angel videos or movies. Is there any special naming convention, since the direct url from the site does not seem to work

Movies aren't currently supported, though individual scenes are. Can you give me an example of a scene you're trying to match?

**Comment by dappleyard** [comment]
Hi something like this https://www.evilangel.com/en/video/DP-3-Way-Split-Tongued-Leigh-Squirts/135138          I'm trying EvilAngel-DP-3-Way-Split-Tongued-Leigh-Squirts 135138 to respect Direct URL rules, but it doesn't seem to work

**Comment by ifbx** [comment]
> Hi something like this https://www.evilangel.com/en/video/DP-3-Way-Split-Tongued-Leigh-Squirts/135138 I'm trying EvilAngel-DP-3-Way-Split-Tongued-Leigh-Squirts 135138 to respect Direct URL rules, but it doesn't seem to work

After a lot of experimenting, I think I figured out the correct search terms for Evil Angel scenes. 

For the link above, try:
EvilAngel - DP-3-Way-Split-Tongued-Leigh-Squirts/135138

That method worked for me with this scene:
https://www.evilangel.com/en/video/Paige-Gaping-AnalRim-JobCum-Swallow/148960

When I searched for EvilAngel - Paige-Gaping-AnalRim-JobCum-Swallow/148960

**Comment by claygoldfinch** [comment]
Sorry, totally forgot to get back to you @ifbx. But yes, that is correct. See https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/manualsearch.md for more info.

**Comment by dappleyard** [comment]
Thanks for all your help.
