### ISSUE TITLE
Sweet Sinner/Sweetheart Video DVD Support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#454]
It looks like Sweet Sinner/Sweetheart Video had there site's updated so the agent can't find scene's/DVD releases anymore. Their new site looks like the Babes/Reality Kings site's.

**Comment by insickin** [comment]
I see that you've got scene's working in the fix, any word on whole DVD releases?

**Comment by claygoldfinch** [comment]
In the works! Scenes were essentially a copy/paste fix, thus the quick turnaround. Gonna have to spend a little more time on DVD releases.

**Comment by insickin** [comment]
Ah, thank man! Thanks for the quick solve!

**Comment by Elandril** [comment]
Could it be that this fix causes some issues with the site detection? After the change any unrecognized sites seem to return siteID 330.

**Comment by insickin** [comment]
Hi, how is this fix coming?

**Comment by insickin** [comment]
Hi, how is this fix (for full DVD releases) coming?

**Comment by insickin** [comment]
Hi, how is this fix (for full DVD releases) coming?

**Comment by claygoldfinch** [comment]
Merged into Issue #1
