### ISSUE TITLE
Pure Mature tag problem

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#468]
I'm trying to tag the 5 scene's from this page https://puremature.com/girls/ava-addams--6 but the agent finds non off them!

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3820960/com.plexapp.agents.phoenixadult.log)

**Comment by pedrolara-boop** [comment]
I tried a few, and they worked out for me, is there any specific one ?
Maybe restart your server and make sure you have the latest version.
Can you please paste just the log part that relates to the error, it makes the life of the developers easier.

**Comment by claygoldfinch** [comment]
All these are working fine for me. Are you still experiencing this issue?

**Comment by insickin** [comment]
No, now they are fine! Maybe a fluke?
