### ISSUE TITLE
How to add a site / help for adding a site

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#471]
Like the title say's: Who keeps the main code up to date? 

I'm asking because there are no update's for the main code for approx 2 weeks while there are 4 Pull requests open to integrate into the main code. 

Not to push people, all work on this project is voluntary and I thank all the contributors for their time and work that they put into this project! I would not want this fantastic project to be lost!

**Comment by claygoldfinch** [comment]
At this point it appears the only active contributors are myself and @SgtBatten. @PAhelper is the repo owner, but he hasn't been seen for a bit. 

I'd love to contribute more to the project but I've been incredibly busy. I've also recognized the need for more contributors (see https://github.com/PAhelper/PhoenixAdult.bundle/issues/411#issuecomment-541341637), but there's not much I can do about that - the only person who can add or remove contributors is @PAhelper.

I can take a look into the open PRs tonight. It isn't always a simple process, I need to test them out with multiple scenes and look through the code to make sure nothing has been broken. 

Unfortunately you may just need to temper your expectations - an update every week or two is far from dead for a community-run project.

**Comment by insickin** [comment]
Thanks for this info/update @claygoldfinch!

It's a shame that only @PAhelper can add / remove contributors...

I know that I can't have expectations about the project but after the sudden departure of Phoenix and PAhelper I was just a little worried ;) 

I thank all of you for building and maintaining this project and know that all of the work is done in your spare time!

**Comment by Tharic99** [comment]
@claygoldfinch have you considered pulling a fork off and updating things on your own? I personally would love to help out where I can, I just don't know a ton of coding.

**Comment by SgtBatten** [comment]
Now that at least a few of us have access we don't need to do that. Anyone can make pull requests and we can approve them. I won't lie. I have an interest in things that I use but not sites I don't download. I am happy to add code others come up with but I have historically only added new sites because I wanted them. 

In saying that.... I am happy to help people learn how to add more sites and debug sites. I had zero experience with GitHub or python or Plex plugins but it's not too hard to pick up in reality.

**Comment by insickin** [comment]
> 
> 
> Now that at least a few of us have access we don't need to do that. Anyone can make pull requests and we can approve them. I won't lie. I have an interest in things that I use but not sites I don't download. I am happy to add code others come up with but I have historically only added new sites because I wanted them.

I find that logical, you firstly write/support the site's YOU like/use of course! 

> 
> In saying that.... I am happy to help people learn how to add more sites and debug sites. I had zero experience with GitHub or python or Plex plugins but it's not too hard to pick up in reality.

Can't you write up a tutorial/course off some sorts?

**Comment by SgtBatten** [comment]
We can certainly try to put something together. If I get some time next week I'll get started on some basics

**Comment by josst10** [comment]
I'm not one to put anything on anyone else's plate (and I know nothing about the possibility of creating a GUI in Python) but I think something that would be helpful for testing purposes is a simple program that when fired up there is a text box, submit button, and a window to show whats returned and the log output for a query. Maybe a copy button to easily copy the code for the forum. To essentially simulate a Plex "match" or "fix match" process. 

Not sure about you guys but I need to log in to my server, open up Plex, log in to Plex, find the file, fix match, open the log, scroll down, etc. Sometimes I just want to test the best naming patterns for a collection or studio and this would be incredibly helpful. 

Either way, thanks for all you are doing!

**Comment by pedrolara-boop** [comment]
First thanks for everyone that contributes.

A command line that we could do a simple search and look at what are the search returns, or what elements of the page that is scrapping would make the whole process so much easier.
It would help troubleshoot and fix and add new sites way faster.

**Comment by insickin** [comment]
> 
> 
> We can certainly try to put something together. If I get some time next week I'll get started on some basics

Hi, have you had time to get a start on this? I really like to try to add/build support for: https://tour.purgatoryx.com/

**Comment by claygoldfinch** [comment]
@insickin what parts are you struggling with? I can get you started, at least:
1. Rename `siteTemplate.py` to `sitePurgatoryX.py`
2. Open `PAsearchSites.py`. Scroll to line 98. Add `import sitePurgatoryX` to the end of the import list. Increment the number after `searchSites = [None]` by one. Add the details of PurgatoryX to the end of the searchSites list. In this case it'd be:
`searchSites[795] = ["PurgatoryX","PurgatoryX","https://tour.purgatoryx.com/","https://tour.purgatoryx.com/search/"]`
3. Open `__init__.py`. Add site info under the `def search` and `def update` sections, at the end of each list. In this case:
```
            ###############
            ## PurgatoryX
            ###############
            if siteNum == 795:
                if searchSiteID == 9999 or searchSiteID == 795:
                    results = PAsearchSites.sitePurgatoryX.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)
```
```

        ##############################################################
        ##                                                          ##
        ##  PurgatoryX                                              ##
        ##                                                          ##
        ##############################################################
        if siteID == 795:
            metadata = PAsearchSites.sitePurgatoryX.update(metadata,siteID,movieGenres,movieActors)
```
4. Open `sitePurgatoryX.py`. Do a sample search on PurgatoryX.com, something that pulls multiple results. Like https://tour.purgatoryx.com/search/sexy. Right click on a scene and select "Inspect element". As you scroll over each line of code the relevant portion of the site should highlight. In this case, it appears as though each result is housed under an entry similar to `//div class = "content-item heaven"`. However, these names seems to change a bit - one result is `//div class = "content-item heaven heaven"`. Or, if you do another search for "Hell" scenes (such as "Indecent Attorney") the entries are labeled `//div class = "content-item hell"`. This means you can't reference these by name. Try to find a class that encompasses all these scenes, and has a unique name (it only appears once in the html). In this case, it's going to be `section class="contents-large contents-list"`. Then, start referencing the html below it until you get the the line you want. Here's the code I'd use: 
`    for searchResult in searchResults.xpath('//section[@class="contents-large contents-list"]/div[2]/div[2]/div'):`
For titleNoFormatting, CurID, etc, you'll just want to reference the lines of HTML within each entry. So titleNoFormatting would be:
`titleNoFormatting = searchResult.xpath('.//h3[@class="title"]/a')[0].text_content().strip()`
etc

If you're running into trouble open up the log file, it should tell you what line of code is failing and why.

**Comment by claygoldfinch** [comment]
Optimally you should fork this repo and make your changes there, so I can see where exactly things are going wrong for you.

**Comment by insickin** [comment]
I hadn't started it yet ;) I just need a helping hand to get a site added (I have very, very little coding experience), and I liked this site so I thought that it was a nice "project" for me to start!

You're explanation from above is just the kind of help I need, thanks!
