### ISSUE TITLE
Brazzers Vault - Matching isn't distinguishing between identical scene names

### ISSUE THREAD

**Issue by WilliamsVM** [PAhelper/PhoenixAdult.bundle#479]
Brazzers Vault has an irritating issue. Brazzers published 11 scenes all with different actors on the same day (03-12-2012) all titled "How To Handle Your Students: 101". I have 3 of them in my library. The Brazzers script only returns 4 scenes and my scenes aren't among them (it actually only returns 3 scenes and the middle 2 returns are always the same scene). Adding the actor names doesn't affect which scenes are returned.

Is there a way to increase the number of returns when matching Brazzers scenes?

**Comment by SgtBatten** [comment]
Ohh that sounds gross. Best solution might be to manually force the match for each of those scenes. If you can collect the title and url to each one and post it here that would be great

**Comment by WilliamsVM** [comment]
Brazzers Vault -  How To Handle Your Students: 101 - Angelica Heart
https://www.brazzers.com/scenes/view/id/7007/how-to-handle-your-students-101/

Brazzers Vault -  How To Handle Your Students: 101 - Jessica Bangkok
https://www.brazzers.com/scenes/view/id/7008/how-to-handle-your-students-101/

Brazzers Vault -  How To Handle Your Students: 101 - Britney Amber
https://www.brazzers.com/scenes/view/id/7015/how-to-handle-your-students-101/

Brazzers Vault -  How To Handle Your Students: 101 - Veronica Avluv
https://www.brazzers.com/scenes/view/id/7013/how-to-handle-your-students-101/

Brazzers Vault -  How To Handle Your Students: 101 - Rachel Roxx Sienna West
https://www.brazzers.com/scenes/view/id/7018/how-to-handle-your-students-101/

Brazzers Vault -  How To Handle Your Students: 101 - Katie Kox
https://www.brazzers.com/scenes/view/id/7014/how-to-handle-your-students-101/

Brazzers Vault -  How To Handle Your Students: 101 - Tanya Tate
https://www.brazzers.com/scenes/view/id/7012/how-to-handle-your-students-101/

Brazzers Vault -  How To Handle Your Students: 101 - Julia Ann
https://www.brazzers.com/scenes/view/id/7017/how-to-handle-your-students-101/

Brazzers Vault -  How To Handle Your Students: 101 - Morgan Ray
https://www.brazzers.com/scenes/view/id/7009/how-to-handle-your-students-101/

Brazzers Vault -  How To Handle Your Students: 101 - Kerry Louise
https://www.brazzers.com/scenes/view/id/7011/how-to-handle-your-students-101/

Brazzers Vault -  How To Handle Your Students: 101 - Sophie Dee
https://www.brazzers.com/scenes/view/id/7016/how-to-handle-your-students-101/

**Comment by SgtBatten** [comment]
Only done the first one on your list for testing purposes for now. can you try it please and post the log
#482

**Comment by SgtBatten** [comment]
added the rest now. let me know

**Comment by WilliamsVM** [comment]
It is matching the scenes now (granted you add the actress name to the end of the file name of course) but it isn't adding the posters from the brazzers website, which is mildly annoying.

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3903385/com.plexapp.agents.phoenixadult.log)

**Comment by SgtBatten** [comment]
The images 404 on that scene in your log
not much we can do i think

**Comment by WilliamsVM** [comment]
Understood regarding the posters.

Found another Brazzers series that behaves similarly. They are named "Don't Touch Her" with subsequent scenes in the series numbered 2-7. It appears that the number is being removed from the query at some point so it always returns the same 4 scenes in the results. This behavior is hinted at by the search term in the text box dropping the number after you search (see screenshot). 

Having someone manually add entries whenever Brazzers decides to make a series longer than 4 scenes seems like a less than optimal solution. The problem is when you click on the "View All" button to see more search results, it takes you to the URL "brazzers.com/videos-search/" which isn't very useful for our purposes. Still there must be a request that the page sends to the server to get the correct version of that page. I'm going to fire up Wireshark and try and grab the request its sending to get that expanded results. Hopefully we can use that request format to pull the expanded results and we'll have at least 12 results to work with instead of the 4 we're getting now. That will let this scale better.

Unfortunately when I started up Wireshark, I updated it which requires a restart. This box is nearly 7 years old and I need to do some maintenance on it, so a restart is going to be an all day thing and I've been a bit busy recently. Hopefully I'll get this done sometime this week.

**Comment by WilliamsVM** [comment]
![DontTouchHer](https://user-images.githubusercontent.com/40531925/69895847-e7ebab00-1304-11ea-85aa-07daf60b6853.PNG)

**Comment by SgtBatten** [comment]
Thanks. We might be able to look at a direct url match also as an option.

**Comment by SgtBatten** [comment]
Turns out sceneID matching is fairly simple to implement for brazzers. Have not tested any subsides yet. One more bug to fix before I do a pull request. 

Searching brazzers 7014 yeilds the correct result for example. 

Brazzers vault does not have its own siteID in this agent. I didn't actually check if it has its own website yet. Will have to continue tomorrow.

**Comment by SgtBatten** [comment]
Okay I've implemented sceneID matching now.

As Brazzers Vault is not actually a supported site you need to use Brazzers - 7014  or Brazzers 7014 etc.
You can keep the title after that but the first thing needs to be brazzers then hyphen or not then the sceneID

**Comment by SgtBatten** [comment]
@WilliamsVM

**Comment by WilliamsVM** [comment]
I'll check this a bit later, been a bit busy taking care of my parents the
past couple of days

**Comment by WilliamsVM** [comment]
Perfect! It found the scenes I needed with no problems. Thank you very much!
