### ISSUE TITLE
Babes/Black Is Better not matching

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#480]
I am trying to tag: "Babes - Addicted to Poon" https://www.babes.com/scene/3092631/addicted-to-poon but the agent can't find the scene. I've tried it with the scene's name, the actress and SceneID, nothing works... 

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3886962/com.plexapp.agents.phoenixadult.log)

**Comment by WilliamsVM** [comment]
This format works for me with Babes.com

Babes - 4358685 - Late Night Hotline
Black is Better - 3071631 - Always On My Mind

**Comment by claygoldfinch** [comment]
> This format works for me with Babes.com
> 
> Babes - 4358685 - Late Night Hotline
> Black is Better - 3071631 - Always On My Mind

Yep, that's how I do it as well. Looks like this agent is having some trouble scraping the date on this particular scene, however, making it error out.

**Comment by insickin** [comment]
Ok, tried it with "Babes - 3092631 - Addicted to Poon" but still I get back: No results...
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3892174/com.plexapp.agents.phoenixadult.log)

**Comment by insickin** [comment]
Ok, found another one that the agent doesn't find; "Babes - Swollen Scissor Sisters" https://www.babes.com/scene/3082831/swollen-scissor-sisters

**Comment by SgtBatten** [comment]
Fixed, try now.

**Comment by insickin** [comment]
Ok, the agent finds the scene now but it doesn't load the scene's description! Can you fix this?

**Comment by SgtBatten** [comment]
fixed now also

**Comment by insickin** [comment]
Thanks it works fully now!
