### ISSUE TITLE
Look At Her Now is it part of any Network?

### ISSUE THREAD

**Issue by pedrolara-boop** [PAhelper/PhoenixAdult.bundle#487]
https://www.lookathernow.com/

I stumble upon this site and was wondering if is not part of another website. It has a small amount of content. Does anyone know?

The site is exactly the same as Reality Kings, Twistys and other sites from MG Premium Ltd. That makes the addition relatively simple, even easier if is part of a network.

**Comment by mrwoofa** [comment]
It's part of the Mofos network, you can find the content on Mofos. 

You should be able to add the site to the Mofos scraper as an alias or new url

**Comment by pedrolara-boop** [comment]
Thanks. However, I was not able to find any scenes on MOFOS.
Do you know any particular scene that is there?
