### ISSUE TITLE
Trying to add new sites - AmateurCFNM and PureCFNM

### ISSUE THREAD

**Issue by jamesalexw** [PAhelper/PhoenixAdult.bundle#488]
I'm trying to add AmateurCFNM to start with and then copy the code once it works properly for PureCFNM.

They have scene listings but they only link to the trial. However, on the model pages you can find scene descriptions and images for each scene. So I've tried to implement a search based on the model name from the scene. Each model has a page in the format first-last.html.

I've managed to set up some code by borrowing from other working sites, to take a model name, replace the space with a hypen and append .html so the agent will bring back results for the scenes. 

However, currently it only brings back one scene from the listed scenes. I've also not managed to get it to retrieve any meta data and apply it to the file.

The current code is below, if anyone can help. I'm trying to use this as an opportunity to learn to code so if you can point out any changes along the way it would much appreciated.

There's a lot of # code where I've tried a different set from another site. Just needs cleaning up once everything is working.

[siteAmateurCFNM.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/3932951/siteAmateurCFNM.txt)

**Comment by claygoldfinch** [comment]
Create a branch on your fork with the code and I'll test it out

**Comment by jamesalexw** [comment]
Okay that's done - https://github.com/jamesalexw/PhoenixAdult.bundle/tree/amateurcfnm

**Comment by claygoldfinch** [comment]
Two things that are causing this issue:

1. You'll want to have "results.Append" in your for loop. If it's outside the for loop it's only going to add the last result to the results array.
2. It appears as though Plex filters out results that have the same curID. If you throw a Log("titleNoFormatting: " + titleNoFormatting) in your for loop, you'll see that you're getting all the results you want, they're just not being passed on to Plex. Doing something like setting the curID to equal titleNoFormatting will make it so all results are displayed in Plex.

```
def search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate,searchSiteID):
    if searchSiteID != 9999:
        siteNum = searchSiteID
    searchString = searchTitle .replace(" ","-").replace(",","").replace("'","").replace("?","").lower().strip() + ".html"
    Log("searchString " + searchString)
    searchResults = HTML.ElementFromURL(PAsearchSites.getSearchSearchURL(siteNum) + searchString)

    for searchResult in searchResults.xpath('.//div[@class="update_block"]'):
        titleNoFormatting = searchResult.xpath('.//span[@class="update_title"]')[0].text_content().strip()
        Log("titleNoFormatting: " + titleNoFormatting)
        curID = titleNoFormatting
        releaseDate = parse(searchResults.xpath('.//span[@class="update_date"]')[0].text_content().strip()).strftime('%Y-%m-%d')
        if searchDate:
            score = 80 - Util.LevenshteinDistance(searchDate, releaseDate)
        else:
            score = 70 - Util.LevenshteinDistance(searchTitle.lower(), titleNoFormatting.lower())
        results.Append(MetadataSearchResult(id = curID + "|" + str(siteNum), name = titleNoFormatting + " [" + PAsearchSites.getSearchSiteName(siteNum) + "] " + releaseDate, score = score, lang = lang))
    return results
```

**Comment by jamesalexw** [comment]
Okay I updated the branch with some changes. There's still an issue with it not pulling the date from the scene on the initial lookup. It seems to use the first date it finds.

The second issue is because the scene name doesn't refer to a scene page, I'm struggling to get the metadata section to go back to the model page and select the data.

I need to pass the actor name back for the URL from the original search and then manipulate that to the correct result, but I'm struggling to do so.

**Comment by claygoldfinch** [comment]
I'll look into the date issue, but here's some code that's working so far:

```
def search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate,searchSiteID):
    if searchSiteID != 9999:
        siteNum = searchSiteID
    searchString = searchTitle .replace(" ","-").replace(",","").replace("'","").replace("?","").lower().strip() + ".html"
    Log("searchString " + searchString)
    searchResults = HTML.ElementFromURL(PAsearchSites.getSearchSearchURL(siteNum) + searchString)
    for searchResult in searchResults.xpath('//div[@class="update_block"]'):
        titleNoFormatting = searchResult.xpath('.//span[@class="update_title"]')[0].text_content().strip()
        releaseDate = parse(searchResults.xpath('.//span[@class="update_date"]')[0].text_content().strip()).strftime('%Y-%m-%d')
        curID = titleNoFormatting
        realURL = (PAsearchSites.getSearchSearchURL(siteNum) + searchString).replace('/','_').replace('?','!')
        summary = searchResult.xpath('.//span[@class="latest_update_description"]')[0].text_content().strip()
        score = 100 - Util.LevenshteinDistance(searchDate, releaseDate)
        results.Append(MetadataSearchResult(id = curID + "|" + str(siteNum) + "|" + realURL + "|" + releaseDate + "|" + summary, name = titleNoFormatting + " [Studio Name] " + releaseDate, score = score, lang = lang))
    return results

def update(metadata,siteID,movieGenres,movieActors):
    Log('******UPDATE METADATA CALLED*******')
    url = str(metadata.id).split("|")[2].replace('_','/').replace('!','?')
    detailsPageElements = HTML.ElementFromURL(url)
    art = []
    metadata.collections.clear()
    movieGenres.clearGenres()
    movieActors.clearActors()

    # Studio
    metadata.studio = 'Studio Name'

    # Release Date
    try:
        date = str(metadata.id).split("|")[3]
        if len(date) > 0:
            date_object = parse(date)
            metadata.originally_available_at = date_object
            metadata.year = metadata.originally_available_at.year
            Log("Date from file")
    except:
        pass

    # Summary
    try:
        metadata.summary = str(metadata.id).split("|")[4]
    except:
        pass
```

Hopefully you get the idea - you gotta scrape all scene data during your search, add it to your results array, and then pull from that array in the update function (at least that's what I would do). curID is element 0 in the array, siteNum is element 1, realURL is element 2, release date is element 3, summary is element 4, etc.

**Comment by claygoldfinch** [comment]
Gonna close this as it hasn't been updated in a few weeks. Feel free to reopen if you run into more trouble.

**Comment by jamesalexw** [comment]
Apologies, I've been quite busy and not able to work on this. I've just pushed an update to my branch. I seem to have broken something and I cannot get the metadata section to process. It pulls the URL but then just doesn't process through the metadata section. Get a URL 200 in the logs and it pulls data back but then never seems to hand it off.

I've tried to create a new file using the code you linked above but nothing seems to work. If you look in the files you'll see a AmateurCNFMOLD with some code I had working that was much more complete. 

If you could take a look and let me know where I've gone wrong it would be much appreciated.

**Comment by claygoldfinch** [comment]
No worries! Sorry for the late response, been out of town. I'll take a look today or tomorrow.

**Comment by jamesalexw** [comment]
Hey, did you get chance to have a look at this? Think it's probably something really simple to get it running again. After that I can carry on with it.

**Comment by claygoldfinch** [comment]
```
import PAsearchSites
import PAgenres
import PAactors

def search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate,searchSiteID):
    if searchSiteID != 9999:
        siteNum = searchSiteID
    searchString = searchTitle .replace(" ","-").replace(",","").replace("'","").replace("?","").lower().strip() + ".html"
    Log("searchString " + searchString)
    url = PAsearchSites.getSearchSearchURL(siteNum) + searchString
    searchResults = HTML.ElementFromURL(url)
    for searchResult in searchResults.xpath('//div[@class="update_block"]'):
        # Info passed on to update fxn
        titleNoFormatting = searchResult.xpath('.//span[@class="update_title"]')[0].text_content().strip()
        Log(titleNoFormatting)
        summary = searchResult.xpath('.//span[@class="latest_update_description"]')[0].text_content().strip()
        Log(summary)
        releaseDate = parse(searchResults.xpath('.//span[@class="update_date"]')[0].text_content().strip()).strftime('%Y-%m-%d')
        Log(releaseDate)
        actorList = []
        actors = searchResult.xpath('.//span[@class="tour_update_models"]/a')
        for actorLink in actors:
            actorName = str(actorLink.text_content().strip())
            actorList.append(actorName)
        actors = ','.join(actorList)
        Log(actors)
        videoBG = searchResult.xpath('.//div[@class="update_image"]/a/img')[0].get('src')
        videoBG = videoBG.replace('/','_').replace('?','!')
        Log(videoBG)

        # Fake Unique CurID
        curID = titleNoFormatting

        if searchDate:
            score = 100 - Util.LevenshteinDistance(searchDate, releaseDate)
        else:
            score = 60
        results.Append(MetadataSearchResult(id = curID + "|" + str(siteNum) + "|" + titleNoFormatting + "|" + summary + "|" + releaseDate + "|" + actors + "|" + videoBG, name = titleNoFormatting + " [AmateurCFNM] " + releaseDate, score = score, lang = lang))
    return results

def update(metadata,siteID,movieGenres,movieActors):
    Log('******UPDATE METADATA CALLED*******')

    art = []
    metadata.collections.clear()
    movieGenres.clearGenres()
    movieActors.clearActors()

    # Studio
    metadata.studio = 'AmateurCFNM'

    # Title
    try:
        metadata.title = str(metadata.id).split("|")[2]
    except:
        pass

    # Summary
    try:
        metadata.summary = str(metadata.id).split("|")[3]
    except:
        pass

    # Tagline and Collection(s)
    tagline = PAsearchSites.getSearchSiteName(siteID).strip()
    metadata.tagline = tagline
    metadata.collections.add(tagline)

    # Genres
    movieGenres.addGenre("CFNM")

    # Release Date
    try:
        date = str(metadata.id).split("|")[4]
        if len(date) > 0:
            date_object = parse(date)
            metadata.originally_available_at = date_object
            metadata.year = metadata.originally_available_at.year
            Log("Date from file")
    except:
        pass

    # Actors
    try:
        actors = str(metadata.id).split("|")[5]
        actors = actors.split(",")
        for actorLink in actors:
            actorName = str(actorLink.strip())
            actorPhotoURL = ""
            movieActors.addActor(actorName,actorPhotoURL)
    except:
        pass

    ### Posters and artwork ###

    # Video trailer background image
    try:
        twitterBG = str(metadata.id).split("|")[6]
        twitterBG = PAsearchSites.getSearchBaseURL(siteID) + twitterBG.replace('_','/').replace('!','?')
        art.append(twitterBG)
    except:
        pass

    j = 1
    Log("Artwork found: " + str(len(art)))
    for posterUrl in art:
        if not PAsearchSites.posterAlreadyExists(posterUrl,metadata):
            metadata.posters[posterUrl] = Proxy.Preview(HTTP.Request(posterUrl, headers={'Referer': 'http://www.google.com'}).content, sort_order = j)
            metadata.art[posterUrl] = Proxy.Preview(HTTP.Request(posterUrl, headers={'Referer': 'http://www.google.com'}).content, sort_order = j)
            j = j + 1


    return metadata
```

**Comment by claygoldfinch** [comment]
Line 15 was causing the issue. If you're passing a URL from the search fxn to the update fxn you need to remove/replace "!" and "/".

**Comment by jamesalexw** [comment]
Ah ok, I'll correct and see how far I can get. Thanks!

**Comment by jamesalexw** [comment]
Ok, so all working fine. Apart from any movie titles that include a ? are not updating metadata. You can try the page for Michelle Moist as an example

**Comment by claygoldfinch** [comment]
Same goes for any variable, if you want to pass it along from the search function to the update function it cannot contain a "?" or "/". 

You may need to check my xpaths, just did a quick dirty fix to get it up and running.

**Comment by jamesalexw** [comment]
Ok, I've managed to fix the issue with dates. release date was looking at searchresults.xpath instead of searchresult.xpath

I'll download the current build and merge my changes and then push it to the main branch.

**Comment by jamesalexw** [comment]
I've corrected the issue with special characters in the scene names and summary. Both sites are supported now but will begin work on making a network script to support the other sites listed.
