### ISSUE TITLE
New Sensations - scene URL path now listing metadata tags not scene title

### ISSUE THREAD

**Issue by dappleyard** [PAhelper/PhoenixAdult.bundle#490]
URL pathway for scenes has changed to list tagging metadata rather than scene name. Hence matching no longer works.

**Comment by claygoldfinch** [comment]
Log?

**Comment by dappleyard** [comment]
Sorry - my mistake, got these to match. Please close the issue.  I noticed you mentioned yesterday Club seventeen is now supported - which website is used to get the URL, since I can only see a join up screen without search functionality?
