### ISSUE TITLE
Nubile Films (nubilefilms.com) matching not working

### ISSUE THREAD

**Issue by justmultiplex** [PAhelper/PhoenixAdult.bundle#491]
I can not match, whatever I try: https://nubilefilms.com/video/watch/84549 (same page as https://nubilefilms.com/video/watch/84549/true-attraction-s33e15)

Nubile Films - 2019-10-09 - 84549
Nubile Films - 2019-10-09 - 84549/true-attraction-s33e15
Nubile Films - 84549
Nubile Films - 84549/true-attraction-s33e15
NubileFilms
Nubilefilms
etc.

Do I do something wrong?

**Comment by SgtBatten** [comment]
Please try Nubile Films - 84549 once again and upload the relevant section of the log file

**Comment by claygoldfinch** [comment]
Works if you don't include a space:
`NubileFilms - 84549`
