### ISSUE TITLE
Dorcelclub not allowing multiple queries

### ISSUE THREAD

**Issue by dsrtusr88** [PAhelper/PhoenixAdult.bundle#492]
I've noticed with dorcelclub, if you do maybe 5-6 matches in a row, the search just starts timing out.  Is there a way to skip the search and manually pull the scene direct from the url?

**Comment by claygoldfinch** [comment]
Can you post a log so we can see what's going on?

**Comment by dsrtusr88** [comment]
`Dec 14, 2019 09:13:16.576 [0x7f2fd3159700] DEBUG - Request: [127.0.0.1:44436 (Loopback)] GET /library/metadata/31057/tree (13 live) GZIP Signed-in Token (equ1nt1s)
Dec 14, 2019 09:13:16.577 [0x7f30416e4700] DEBUG - Completed: [127.0.0.1:44436] 200 GET /library/metadata/31057/tree (13 live) GZIP 1ms 1025 bytes
Dec 14, 2019 09:13:16.593 [0x7f3030725700] DEBUG - HTTP 200 response from GET http://127.0.0.1:36261/:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1CjMxMDU3czIKaWRzMjQKRG9yY2VsY2x1YiBMdXN0ZWQgV2FyZGVuczQKbmFtZW5zNAp5ZWFycjAK
Dec 14, 2019 09:13:16.593 [0x7f3030725700] DEBUG - [com.plexapp.agents.phoenixadult] HTTP reply status 200, with 320 bytes of content.
Dec 14, 2019 09:13:16.593 [0x7f30416e4700] DEBUG - Completed: [127.0.0.1:44432] 200 GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1CjMxMDU3czIKaWRzMjQKRG9yY2VsY2x1YiBMdXN0ZWQgV2FyZGVuczQKbmFtZW5zNAp5ZWFycjAK (13 live) GZIP 20ms 6394 bytes
Dec 14, 2019 09:13:16.594 [0x7f3040e1a700] DEBUG - HTTP 200 response from GET http://127.0.0.1:46729/system/agents/search?mediaType=1&id=31057&identifier=com.plexapp.agents.phoenixadult&lang=en&name=Dorcelclub%20Lusted%20Warden&year=&manual=1
Dec 14, 2019 09:13:16.595 [0x7f3040e1a700] DEBUG - [com.plexapp.system] HTTP reply status 200, with 130 bytes of content.
Dec 14, 2019 09:13:16.595 [0x7f2fd22b3700] DEBUG - HTTP 200 response from GET http://127.0.0.1:32400/system/agents/search?mediaType=1&id=31057&identifier=com.plexapp.agents.phoenixadult&lang=en&name=Dorcelclub%20Lusted%20Warden&year=&manual=1
Dec 14, 2019 09:13:16.595 [0x7f30416e4700] DEBUG - Completed: [127.0.0.1:44426] 200 GET /system/agents/search?mediaType=1&id=31057&identifier=com.plexapp.agents.phoenixadult&lang=en&name=Dorcelclub%20Lusted%20Warden&year=&manual=1 (13 live) GZIP 77ms 408 bytes
Dec 14, 2019 09:13:16.595 [0x7f2fd22b3700] WARN - No matches for search.
Dec 14, 2019 09:13:16.595 [0x7f30416e4700] DEBUG - Completed: [10.0.0.246:52763] 200 GET /library/metadata/31057/matches?manual=1&title=Dorcelclub%20Lusted%20Warden&agent=com.plexapp.agents.phoenixadult&year=&language=en (13 live) TLS GZIP 79ms 562 bytes (pipelined: 3)`

Interestingly enough, I visited the site when this was happening and validated a captcha and then normal scrapping resumed.  It would then stop again and if I repeated the same captcha, it would start again.  It's like they have a security that is specifically noticing automated activity.

**Comment by claygoldfinch** [comment]
Doesn't surprise me. A few questions:

1. Are you using a VPN? Disabling it might help.
2. Does the site ask you to complete a captcha to access any page, or just the search page? If it's just the search page, we could certainly look into adding in Direct URL matching as an alternative solution.

**Comment by dsrtusr88** [comment]
@claygoldfinch 
1. No, it is on my QNAP NAS.  I installed a browser there and have navigated to the website to use the log in and it doesn't seem to matter if I'm using my PC or remoting through the NAS, once I perform the reCaptcha it starts scraping again.
2. The specific warning I get is that "my actions look robotic" and to either log back in or do a download/search (some kind of site input), I have to perform the captcha.

I'm having trouble reproducing the error, I'll need to do a large batch of files do run through the agent again to reproduce.
