### ISSUE TITLE
Actress Corrections for Lovita Fate

### ISSUE THREAD

**Issue by chempke** [PAhelper/PhoenixAdult.bundle#493]
Can You add [Lovita Fate](https://www.indexxx.com/m/lovita-fate) to PAactors.py? 
At Mile High Media Network she is named as [Barbie Sins](https://www.doghousedigital.com/model/60800/barbie-sins)

**Comment by claygoldfinch** [comment]
This is a weird one. I think Doghouse Digital just screwed up when creating actress profiles. 

"Barbie Sinn" [profile](https://www.doghousedigital.com/model/60800/barbie-sins) (actually Lovita Fate)
"Barbie Sins" [profile](https://www.doghousedigital.com/model/65266/barbie-sins) (the real Barbie Sins)
[Scene](https://www.doghousedigital.com/scene/4402785/mom-dad-are-fucking-my-friends-22-scene-2) where both Barbie Sins and Lovita Fate star, both are tagged "Barbie Sins".

**Comment by chempke** [comment]
Annoying that you can't change something like this yourself in plex. An idea how I could solve this case differently?
Since this is a problem with the website and not with the actress name, I close the case

**Comment by claygoldfinch** [comment]
Give PR #518 a shot.
