### ISSUE TITLE
Enhanced search not working !

### ISSUE THREAD

**Issue by mukalaaa** [PAhelper/PhoenixAdult.bundle#495]
I tried both Naughty America & GirlsWay using Enhanced Search as instructed by you 
Nothing is found... I used all naming structure as instructed by you 
SN - Date - Scene ID 
SN - Scene Name 
etc 

Any help will be appreciated?

**Comment by claygoldfinch** [comment]
Girlway is currently broken (#486), a fix is currently in the works (#489). Naughty America is working fine. I personally recommend:

`NaughtyAmerica - Date - Title`

If you're still running into issues post a log.
