### ISSUE TITLE
Fake Taxi/Fake Hub not returning results

### ISSUE THREAD

**Issue by ddragon3** [PAhelper/PhoenixAdult.bundle#498]
Site: Fake Taxi/Faketaxi.com
File Name: ftx_hazel_jack_s2_RU122314_1080p_6000
Search Term: Fake Taxi 4076331
Logs: attached

This was working as of two or three days ago, now it's not returning anything. In the logs it looks like Fake Taxi is being shortened to ake taxi, but I'm not sure if that's the same as when it was working. I think the relevant bits of the log are only through 126 or so, stuff after that was just me confirming other sites worked and trying a few things. No luck.
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/3974571/com.plexapp.agents.phoenixadult.log)

**Comment by mukalaaa** [comment]
Same thing here, None of my naming structure works 
I tried 

1. FakeHub - 4395219 - Hot mature massive tits Milf fucked
2. FakeHub - 4395219
3. FakeHub - Date - 4395219 - Hot mature massive tits Milf fucked

No results at all, I noticed that the website uses same layout as Twistys !! if that helps guide us toward a solution or a fix

**Comment by HWatBobby** [comment]
I've got the fixes available for FakeHub, SexyHub, Twistys, and Property Sex in the latest PR #508 

Make the changes in the respective files and let me know how they are working for you. If you make changes to Twistys start with the upper commit.
