### ISSUE TITLE
DadCrush SceneID?

### ISSUE THREAD

**Issue by chempke** [PAhelper/PhoenixAdult.bundle#499]
I can't find the SceneID on dadcrush.com.
Is this a site change or something, because the URL doesn´t contain a SceneID www.dadcrush.com/movies/invading-her-privacy

**Comment by SgtBatten** [comment]
Well... That url you posted gives a 404 error. 

The scene is https://www.dadcrush.com/791/invading-her-privacy/harley-jade which does have a sceneID.

**Comment by chempke** [comment]
Now your link gives me a 404 error... hmm

But how did you get there? 
I got to Models and search for the girl with the scene i want to match

**Comment by claygoldfinch** [comment]
All the scenes on the main page have had their URLs changed, too. Might have to update the site to DirectURL only.

**Comment by claygoldfinch** [comment]
Turns out it's actually a full site redesign.
