### ISSUE TITLE
Girlfriends Films support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#50]
I see that you've added/crossed Girlfriends Films, so I tried a few scenes/DVD releases but no dice! The agent only comes back with: No matches found.

For example: Conjoined (for a whole DVD test)
[https://www.girlfriendsfilms.com/en/dvd/Conjoined/29303](url)
I've tried it with:
Girlfriendsfilms - Conjoined
Girlfriends films - Conjoined
Girlfriendsfilms - 29303

And Women Seeking Women 153 scene 1 (for a scene test)
[https://www.girlfriendsfilms.com/en/video/Women-Seeking-Women-153/134666](url)
Girlfriendsfilms - Women Seeking Women 153
Girlfriendsfilms - Jade Nile Olive Glass
Girlfriendsfilms - 134666
(Could you show how to format the titles of individual scenes because on their website all scenes are named (of in this case) Women Seeking Women 153 with the change of the actresses names on the scene's page itself.

What am I doing wrong?

**Comment by insickin** [comment]
How far are you on this problem?

**Comment by insickin** [comment]
@PAhelper have you downloaded any other scenes?

**Comment by PAhelper** [comment]
Merging into #28
