### ISSUE TITLE
Cherry Pimps support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#506]
I'm trying to tag https://cherrypimps.com/trailers/17051-angelawhite.html but I can't get the agent to tag it!

I've tried it with the combo's:
cherrypimps - Angela White Gets Put On Santas Naughty List 
cherrypimps - Angela White

**Comment by claygoldfinch** [comment]
Same issue as #500, resolved in my latest PR.

**Comment by insickin** [comment]
Thanks @claygoldfinch it works now!
