### ISSUE TITLE
Tonights Girlfriend Support

### ISSUE THREAD

**Issue by Duglim** [PAhelper/PhoenixAdult.bundle#51]
Hi, great work here. Thx a lot so far.

Could you possibly also add support for https://www.tonightsgirlfriend.com site? Within the Naughty America Site is only a selection called "Tonights Girlfriend Classic", which only covers older releases. 

Thx.

**Comment by PAhelper** [comment]
I looked into this briefly and there doesn't appear to be much metadata for us to use. I'll check again before closing the issue though...
