### ISSUE TITLE
Agent won't load in Plex

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#53]
I can not see the agent anymore, it wont load. Restarted my server a couple of times.

In the server settings/agents all the rest of my agents show up except the PhoenixAdult.

FYI: I've installed a second install on my windows machine and I do not see it there either.

**Comment by PAhelper** [comment]
My fault fellas. Should be fixed now. Sorry for the scare.

**Comment by insickin** [comment]
No worries, beta right? 😉

**Comment by PAhelper** [comment]
I downloaded some videos from there, but I'm not even sure if they are scenes or full movies. It is on my radar though...

**Comment by insickin** [comment]
I was asking because you've crossed it 😉
