### ISSUE TITLE
Tugpass Support

### ISSUE THREAD

**Issue by jamesalexw** [PAhelper/PhoenixAdult.bundle#554]
This site https://www.tugpass.com/ has a search function but it doesn't return to a URL like other sites. It lists scenes for 11 sub sites, many of which don't have a search of their own. 

Is there a way to pull a search function from this site?

**Comment by DirtyRacer1337** [comment]
Search on `tugpass.com` works for sub sites, and what you mean doesn't return url? You mean it's doesn't look like `tugpass.com/search?q=your search query`?

**Comment by jamesalexw** [comment]
> You mean it's doesn't look like tugpass.com/search?q=your search query?

Yes, it pulls back results but you can't pass the site a search query like on other sites.

**Comment by DirtyRacer1337** [comment]
You need to do POST request, in code it's something like that
```python
params = {
    'contentSearch': encodedTitle
}
req = urllib.Request(PAsearchSites.getSearchSearchURL(siteNum), data=params)
data = urllib.urlopen(req).read()
searchResults = HTML.ElementFromString(data)
```

**Comment by jamesalexw** [comment]
Cool thanks. Will see what I can get done.
