### ISSUE TITLE
21sextreme support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#56]
I wanted to add my 21sextreme scenes but run into a problem with 2 of them namely:
21sextury - You rang M'lord – part 1 [https://www.21sextreme.com/en/video/You-rang-Mlord---part-1/92603](url)
and
21sextury - You rang M'lord – part 2 [https://www.21sextreme.com/en/video/You-rang-Mlord---part-2-Scene-01/92602](url)

I've tried all sorts of combinations (shortening the search, searching with the scene number) but didn't get the scenes to show up, can you take a look/crack at it?

**Comment by PAhelper** [comment]
21sextury and 21sextreme are two different networks as far as I could tell. Try "21sextreme you rang"

**Comment by insickin** [comment]
Ok, now I feel stupid 🤦🏻‍♂️🤣 I had the names of the studio mixed up, those 2 studio names are much too similar! 😂

I've changed the studio names but it still can't find the scenes, I have tried your sugestion but that also doesn't do the trick.

**Comment by PAhelper** [comment]
Nope, doesn't work for me. I'll troubleshoot.

**Comment by PAhelper** [comment]
I forgot to add the 21Sextreme network to the options in networkGammaEnt.py... latest commit should fix that. I tested 2 scenes I had and both worked.

**Comment by insickin** [comment]
Thanks, now the agent can find the scenes via the "21Sextreme - 92603" method.

**Comment by insickin** [comment]
After matching a few scenes I noticed that the background images were "grainy", is there any chance that you can get better images or are these the best that the site has to offer?
