### ISSUE TITLE
Clean up Darkx, Lesbianx, Eroticax files

### ISSUE THREAD

**Issue by PAhelper** [PAhelper/PhoenixAdult.bundle#6]
They are pretty much clones of the Hardx code I wrote, but there are subtle differences that break these clone sites.
- Remove Director
- Remove or replace Tagline
- Add photos from the free photos link below each video

**Comment by fritz276** [comment]
EroticaX not fully working, not getting all metadata (no posters, not background)
Maybe because of the error in the logs
siteEroticaX.py", line 65, in update date_object = datetime.strptime(date, '%Y-%m-%d')
ValueError: time data '07-25-2018' does not match format '%Y-%m-%d'

**Comment by PAhelper** [comment]
Confirmed metadata for Hardx, Darkx, Eroticax working (except for bg and poster images)
Closing this issue and opening a new one specific for posters/bg
