### ISSUE TITLE
DDFNetwork is now Pornworld.com

### ISSUE THREAD

**Issue by pedrolara-boop** [PAhelper/PhoenixAdult.bundle#604]
The site nows redirects to pornworld.com
The search and matching seem to be broken. 
I haven't checked but hopefully, the site is similar enough for a quick transition.

**Comment by DirtyRacer1337** [comment]
It's still working [Russian Beauty Spreads Her Pink](https://ddfnetwork.com/videos/russian+beauty+spreads+her+pink/17520)

**Comment by pedrolara-boop** [comment]
Cool, I'm going to use the link to avoid been redirected.
