### ISSUE TITLE
Blacked Genre/Actor not being pulled

### ISSUE THREAD

**Issue by niikNak** [PAhelper/PhoenixAdult.bundle#61]
I'm having trouble pulling metadata from Blacked.com. Studio, tagline, summary, original date, and title are pulled fine, but actors/actresses, genre tags, and image thumbnail/posters and backgrounds aren't. 

I've tried
Blacked - Hot Vacation Adventures.mp4
Blacked - How To Train a Housewife.mp4

both get matched, but not all information is pulled as previously discussed.  I'm not having this issue with any other site I've tried using your software. 
Thanks for your time, you're doing gods work.

**Comment by niikNak** [comment]
twas me just f'in up

**Comment by chempke** [comment]
What was the fault? Cause i don't get any meta for new added titels.

**Comment by PAhelper** [comment]
I've noticed that sometimes my searches pull from www.blacked.com, and sometimes I'm redirected to beta.blacked.com. I started writing code to function in the beta site, but I'm not sure I ever finished it, or their site Dom might have changed. Could be that?

**Comment by chempke** [comment]
I`m not sure. All I can say is, when I try open blacked.com i got redirected to the beta.blacked.com.

**Comment by niikNak** [comment]
For me I know that somehow my metadata got screwed up which was my problem. All I had to do was do a plex dance. Still new to plex so wasn't aware of such an issue.

I do notice that not all tags are being pulled from the site though

**Comment by nitschkecm** [comment]
Hi it seems like the that actors get not pulled again.
