### ISSUE TITLE
Issue finding a Digital Playground scene

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#616]
I am trying to get "digitalplayground - Kinky Nerd Wants It Rough" https://www.digitalplayground.com/scene/4178251/kinky-nerd-wants-it-rough-trailer tagged but whatever I do the agent gets back with: Nothing found! 

I tried searching for it with:
"digitalplayground - Kinky Nerd Wants It Rough"
"digitalplayground - 4178251"
"digitalplayground - Alex Chance"

I'm on the latest version of the agent.
What am I doing wrong?

**Comment by josst10** [comment]
It seems like a DP website issue. If you go to Alex Chance on the site, it lists only 1 video with her. 

https://www.digitalplayground.com/modelprofile/1673/alex-chance

I also reference this xml when I have a problem with a match and it's not showing there. Plus, it has trailer in the title. 

https://www.digitalplayground.com/scenes_sitemap1.xml

**Comment by insickin** [comment]
So its not possible to add this scene? It was possible in the past (maybe Digital Playground had the scene deleted from their search because its still on their site), because I had the scene tagged but it was missing a cast photo so I did a metadata refresh after that I got this problem.

**Comment by DirtyRacer1337** [comment]
It's a trailer, did you add it before or after #574? I can add trailers support, but they don't have images

**Comment by insickin** [comment]
The first time you mean? (when it was successful) That was before #574 If you can do that it will be great! I don't mind that I have to add images for those scene's which are only listed on Digital Playground as trailers, so long as I can add them (the rest of the metadata) I'm all for it!
