### ISSUE TITLE
Bangros search is broken

### ISSUE THREAD

**Issue by WilliamsVM** [PAhelper/PhoenixAdult.bundle#617]
Tried matching a new Bangbros scene and got no matches. several others gave no matches either. Checked logs and found a critical error in the search function

CRITICAL (core:574) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4151140/com.plexapp.agents.phoenixadult.log)

**Comment by WilliamsVM** [comment]
I updated to the newest build and still go the error. : (

**Comment by DirtyRacer1337** [comment]
It's known issue, just rename `Monsters of Cock` to `MonstersofCock`

**Comment by insickin** [comment]
@DirtyRacer1337 is this issue a issue that's been worked on? Otherwise you (or @claygoldfinch ) can post it in #218 post (Known Issues)

**Comment by DirtyRacer1337** [comment]
I'm trying to fix it in #546

**Comment by WilliamsVM** [comment]
Thanks that fix worked. 

A note for anyone else coming across this - Remove all spaces from website title and matching will work.

**Comment by Dbones202** [comment]
Confirmed. Removed all spacing from search and it seems to address the issue.

**Comment by WilliamsVM** [comment]
Also affects Amateur Allure. You have to mane files "AmateurAllure - " to avoid the error.
