### ISSUE TITLE
Big Butts Like it Big (Brazzers) not matching?

### ISSUE THREAD

**Issue by refractive2** [PAhelper/PhoenixAdult.bundle#62]
I have some scenes from Big Butts Like it Big that don't match successfully if I name them using the convention `Big Butts Like it Big - Scene Name.mp4` while other Brazzers scenes work fine with `Site Name - Scene Name.mp4` – is this a bug? (They work fine if I rename them to `Brazzers - Scene Name.mp4`).

**Comment by PAhelper** [comment]
I have 4 scenes from BBLIB, they all matched fine naming "Big Butts Like It Big Happy to Help", etc.

**Comment by refractive2** [comment]
The scenes in question are these:
https://www.brazzers.com/scenes/view/id/3122/fucking-the-crew/
https://www.brazzers.com/scenes/view/id/3544/diary-of-a-cockaholic/
https://www.brazzers.com/scenes/view/id/9360/dont-touch-her/
https://www.brazzers.com/scenes/view/id/3115/repo-bitch/

**Comment by PAhelper** [comment]
I searched for "big butts like it big - don't touch her" and it returned "Don't Touch Her [Brazzers/Big Butts Like It Big] 2016-01-26" and like 4 others from that series.

I searched for "big butts like it big - repo bitch" and it returned "Repo Bitch [Brazzers/Big Butts Like It Big] 2008-06-16" along with 3 other titles.

Seems to completely work for me searching for the site "Big Butts Like It Big"...

**Comment by PAhelper** [comment]
@refractive2 Are these still giving you trouble? Do you get any (wrong) results when you name the files `Big Butts Like it Big - Scene Name.mp4` Can you post the logs after a failed search?

**Comment by PAhelper** [comment]
It's been several weeks, I'm going to assume this got sorted out. Feel free to reopen if you're still having trouble.
