### ISSUE TITLE
Certain 21sextury scenes not matching

### ISSUE THREAD

**Issue by refractive2** [PAhelper/PhoenixAdult.bundle#63]
Trying to match to the scene https://www.21sextury.com/en/video/The-shopping-bag-trick/94088. I've tried doing `21Sextury - The Shopping Bag Trick.mp4` and `21Sextury - 2010-06-29 - Brooke Banner.mp4` and neither works. I eventually did `21Sextury - Brooke Banner.mp4` which loaded the wrong scene but which did have the right scene in the Fix Match… menu. What's happening here?

**Comment by insickin** [comment]
I had the same problem and indeed try searching via

> 
> 
> Try with the URL id `21Sextury - 94088` works with most of the gamma ent sites.


[https://github.com/PAhelper/PhoenixAdult.bundle/issues/56](url)

**Comment by PAhelper** [comment]
Yeah, basically the Gamma Entertainment sites' search engines are overly inclusive. If you search for "The Shopping Bag Trick", it will include any title with "The", any title with "Shopping", any title with "Bag" and any title with "Trick". Works the same with actresses. Any title with "Brooke", and any with "Banner". 

Basically, when searching 21Sextury (or many other GammaEnt sites), the less words, and more unique, the better.

**Comment by refractive2** [comment]
OK, thank you!
