### ISSUE TITLE
Naughty America Sites not working

### ISSUE THREAD

**Issue by nickeich1117** [PAhelper/PhoenixAdult.bundle#640]
Hi - Plugin is awesome - recently NA sites stopped searching for me.  Sometimes they automatically match correctly, but doing a manual search is returning 0 results.
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4264183/com.plexapp.agents.phoenixadult.log)

https://www.naughtyamerica.com/scene/asa-akira-fucking-in-the-backyard-with-her-tattoos-14535?nats=4.10025.8.8.1169.0.0.0.0

Filename: mdhg.12.06.29.asa.akira also searched with full site name - "MyDadsHotGirlFriend.12.06.29.asa.akira" - but manual search returns "No Matches Found"

Log Attached.

This is happening with every NA site to me.  They were working great until earlier this week when I migrated my library to a new instance of plex.

**Comment by mukalaaa** [comment]
Yeah I tried now...nothing is getting matched at all !!

**Comment by josst10** [comment]
No idea why but, "dirtywivesclub.17.06.06.ashley.adams" does not work but "dirtywivesclub.17.06.06.ashley" does. If that helps in figuring it out.

**Comment by mukalaaa** [comment]
it is working now but it is not getting any posters except for couple scenes out of 420 
it gets the naming right as well as the description of the scene but no posters!!
