### ISSUE TITLE
Enhanced site searches not working

### ISSUE THREAD

**Issue by liberteh** [PAhelper/PhoenixAdult.bundle#645]
Hi,

I have problem scraping from enhanced searches.
My filenames are in this format: 
` <Studio> - <ActressName(s)> <SceneName> (opt:<date>).<ext>`
Example: JaysPOV - Kimberly Brix Petite Redhead POV (2017-12-12).mp4 does not match

Only when I remove the actress name it will get a match. Isn't it suppose to match including actress names?

**Comment by DirtyRacer1337** [comment]
I tested your example and it's matched.
Anyway date should come first, otherwise it's doesn't work, like
`JaysPOV - 2017-12-12 - Kimberly Brix Petite Redhead POV.mp4`

**Comment by liberteh** [comment]
It's been a long time since I batch renamed my collection. It's about 10TB in size. Mostly obfuscated and not easily readable filenames have been fixed to an extend that includes the above. I don't see an easy way for fixing this in bulk.

Maybe my question should have been: is there a possibility that automatic matching is less strict on where a date located in the filename?

**Comment by DirtyRacer1337** [comment]
As I said it's working with your example. I will think about date parsing it's should be easy

**Comment by liberteh** [comment]
The postprocessing renamer script that comes with this plug-in has given me these filenames. I changed the script (I'm not a programmer, I can just read other people's work as a general IT guy ;)) so it would provide the right filenames.

pa_renamer_post.py old:
`    if shoot is not None:
        # filename should be: "Studio - Model Names.mp4" or "Studio - Title Words.mp4"
        # TODO: figure out if we should use titles or models
        
        # Capitalise the title (first letter of every word). Keep original studio in case we swap it out later.
        filename_new = shoot['studio'] + ' - ' + string.capwords(shoot['filename_title'] + ' (' + shoot['date'] + ').mp4')
        logger.debug(" Before overrides the name is : %s" % filename_new)
        
        #check if any overrides are set in siteOverrides.py
        overrideSettings = siteOverrides.getSiteMatch(shoot['studio'], dir)
        correctName = siteOverrides.getRename(shoot['studio'], "filleractor", shoot['filename_title'], shoot['date'])`

New:
`    if shoot is not None:
        # filename should be: "Studio - Model Names.mp4" or "Studio - Title Words.mp4"
        # TODO: figure out if we should use titles or models
        
        # Capitalise the title (first letter of every word). Keep original studio in case we swap it out later.
        filename_new = shoot['studio'] + ' - ' + shoot['date'] + ' - ' + string.capwords(shoot['filename_title'] + '.mp4')
        logger.debug(" Before overrides the name is : %s" % filename_new)
        
        #check if any overrides are set in siteOverrides.py
        overrideSettings = siteOverrides.getSiteMatch(shoot['studio'], dir)
        correctName = siteOverrides.getRename(shoot['studio'], shoot['date'], "filleractor", shoot['filename_title'])
`

**Comment by DirtyRacer1337** [comment]
I improve date search in #649, now it's doesn't matter where date located
