### ISSUE TITLE
JoyMii Limited Search not working correctly

### ISSUE THREAD

**Issue by liberteh** [PAhelper/PhoenixAdult.bundle#646]
Filename example: Joymii - Jessika In (2019-06-29).mp4 doesn't match.
Manual search for "joymii Jessika" with year 2019 results in multiple options, in which the right scene name is listed "In-Demand Lover (2019-06-29" which seems to include a Jessika. So this is the way to match this "limited" option

**Comment by DirtyRacer1337** [comment]
Also, you can find it by title, like this `Joymii - Demand Lover` and filtered it with date, before #649 it's should be first in filename like this `Joymii - 2019-06-29 - Demand Lover`
