### ISSUE TITLE
Nubiles-Porn.com network - Exact SceneID

### ISSUE THREAD

**Issue by liberteh** [PAhelper/PhoenixAdult.bundle#647]
The site doesn't allow for search (for non-members) or provide a sceneID on preview pages. 
Manual search for matching doesn't result anything when searching for Nubiles or in my case "Myfamilypies"

**Comment by DirtyRacer1337** [comment]
You can get sceneID from url, for example:
`https://nubiles-porn.com/video/watch/90854/watch-me-fuck-your-friend-s12e4`
sceneID = `90854`
