### ISSUE TITLE
analized.com not matching 

### ISSUE THREAD

**Issue by mukalaaa** [PAhelper/PhoenixAdult.bundle#650]
every format of naming i tried under enhanced search method is not working 

every file i have is being identified as abella danger movie 

is analized.com matching broken?

**Comment by mukalaaa** [comment]
any help guys regarding this will be highly appreciated!!

**Comment by liberteh** [comment]
Same here

**Comment by DirtyRacer1337** [comment]
Site have bad search:
https://analized.com/search.php?query=Phoenix+Marie+Is+Always+Down+To+Fuck
Try to use actor name:
https://analized.com/search.php?query=Phoenix+Marie

**Comment by mukalaaa** [comment]
@DirtyRacer1337 thank you for your help. But, I am really new to this so can you tell me if there is something i should do? 

I mean the changes you made, are they in the plugin now under a new version perhaps? 

Very sorry but I am really lost here :) yet I appreciate your help and efforts

**Comment by DirtyRacer1337** [comment]
@mukalaaa my PR#652 not in plugin right now, @claygoldfinch or someone else should merge it. For now, you can rename your files to that `Date - Actor Name` format or download plugin from my repository `FPN` branch
