### ISSUE TITLE
Legalporno not matching

### ISSUE THREAD

**Issue by azxcds141** [PAhelper/PhoenixAdult.bundle#654]
Plex correctly finds movies but Poster, Actors and genres not being pulled into Plex

**Comment by mukalaaa** [comment]
whats the naming format you are following... because the scenes names are so long!!!

**Comment by azxcds141** [comment]
I match the scenes by using a format such as “Legalporno - SZ2380”.  Plex finds the movie but does not pull in posters, actors or genres.  It does, however, pull in the release date, studio and tag line

**Comment by azxcds141** [comment]
Is anyone else having a problem with Plex matching Legalporno movies, especially with the actors, genres and posters?  Thanks in advance.

**Comment by mukalaaa** [comment]
I just tried it using the naming format you mentioned above...it is working fine... it gets the posters and actors too

**Comment by azxcds141** [comment]
Plex worked correctly on Legalporno movies until about 20 days ago.  I cannot get it to pull in actors, genres and posters.  I downloaded and installed the most recent version of the PhoenixAdult.bundle and still no success.  Again, Plex finds the movie, it just doesn't pull in all of the information.  The PhoenixAdult.bundle is working for other sites, it just isn't working completely for Legalporno movies.

**Comment by azxcds141** [comment]
I solved the problem by updating to the most recent version of Plex media server.  Now everything is being pulled into Plex correctly.
