### ISSUE TITLE
PureTaboo searches seem broken

### ISSUE THREAD

**Issue by PAHelper2** [PAhelper/PhoenixAdult.bundle#659]
Hi, trying to import a lot of PureTaboo videos, and many of them are having trouble.  

For example:
PureTaboo - 2018-05-10 - Trailer Park Taboo Part 3.mp4

Just comes up with a random list of PureTaboo scenes, all with a very high confidence level.

**Comment by edkradicalz** [comment]
I am also having the same issue.

**Comment by PAHelper2** [comment]
So I've tested this more.  I'm seeing a weird behavior, when doing a manual search, using the sceneID i get from the puretaboo website.

1. Use Manual Search like: PureTaboo - 825462
2. Wait a long time
3. (Usually) List of random scenes that don't match
4. Go to manual search again, and put in the same exact search.
5. Get back the scene!

Step 3 sometimes return the scene, but 90% of the time, doesn't.  But repeating the search 100% of the time finds the scene.

**Comment by mdashwood** [comment]
I am also getting some issues getting a Pure Taboo scene to index: Log entries are


020-04-14 11:12:22,239 (-4f100ba0) : INFO (__init__:44) - *******MEDIA TITLE****** Pure Taboo 144179 Immersion Therapy
--
#725 | 2020-04-14 11:12:22,240 (-4f100ba0) : INFO (__init__:51) - Getting Search Settings for: Pure Taboo 144179 Immersion Therapy
#726 | 2020-04-14 11:12:22,240 (-4f100ba0) : INFO (PAsearchSites:1026) - mediaTitle w/ possible abbreviation: Pure Taboo 144179 Immersion Therapy
#727 | 2020-04-14 11:12:22,326 (-4f100ba0) : INFO (PAsearchSites:1226) - mediaTitle w/ possible abbrieviation fixed: Pure Taboo 144179 Immersion Therapy
#728 | 2020-04-14 11:12:22,355 (-4f100ba0) : INFO (PAsearchSites:980) - Site found with method #3
#729 | 2020-04-14 11:12:22,357 (-4f100ba0) : INFO (PAsearchSites:1241) - ^^^^^^^ siteID: 281
#730 | 2020-04-14 11:12:22,357 (-4f100ba0) : INFO (PAsearchSites:1243) - ^^^^^^^ Shortening Title
#731 | 2020-04-14 11:12:22,362 (-4f100ba0) : INFO (PAsearchSites:1244) - pure taboo vs pure taboo
#732 | 2020-04-14 11:12:22,363 (-4f100ba0) : INFO (PAsearchSites:1248) - 1
#733 | 2020-04-14 11:12:22,368 (-4f100ba0) : INFO (PAsearchSites:1310) - 8
#734 | 2020-04-14 11:12:22,371 (-4f100ba0) : INFO (PAsearchSites:1310) - searchTitle (before date processing): 144179 Immersion Therapy
#735 | 2020-04-14 11:12:22,372 (-4f100ba0) : INFO (__init__:61) - Search Title: 144179 Immersion Therapy
#736 | 2020-04-14 11:12:22,372 (-4f100ba0) : INFO (__init__:70) - 144179%20Immersion%20Therapy
#737 | 2020-04-14 11:12:22,400 (-4f100ba0) : DEBUG (networking:143) - Requesting 'https://www.puretaboo.com/en/search/144179%20Immersion%20Therapy/scene'
#738 | 2020-04-14 11:12:22,877 (-4f100ba0) : ERROR (networking:196) - Error opening URL 'https://www.puretaboo.com/en/search/144179%20Immersion%20Therapy/scene'

**Comment by raenoll** [comment]
I got the same issue. No result with PureTaboo at all.
