### ISSUE TITLE
HandsOnHardcore / Ddfnetwork

### ISSUE THREAD

**Issue by Spanishu** [PAhelper/PhoenixAdult.bundle#661]
Seems like there was a rebranding of DDFNetwork to pornworld. If somebody could fix this would be great!

**Comment by pedrolara-boop** [comment]
I'm having trouble matching since they changed their name.
DDFBusty.Amber.Jayne.Big.Boobs.Bounce.On.Big.Black.Cock
Is now this scene
https://pornworld.com/watch/64222/british_milf_amber_jayne_bounces_her_big_tits_while_riding_a_big_black_cock_gp1260

**Comment by d2dyno** [comment]
Would like to see this updated as well

**Comment by WilliamsVM** [comment]
Search by scene title works halfway. It pulls a page with the correct information on it but the script isn't reading the page correctly and returns 'no matches found' in Plex.

**Comment by stevef9432203** [comment]
All of the DDF sites seem to Fail for Some REASON.,....

**Comment by pibi73** [comment]
let's hope to have a solution soon :)

**Comment by DirtyRacer1337** [comment]
Looks like subsites still working https://handsonhardcore.com/videos/babe+banged+in+the+steam+room/22986

**Comment by MrDemous** [comment]
> Looks like subsites still working https://handsonhardcore.com/videos/babe+banged+in+the+steam+room/22986

Is HandsOnHardcore still matching for you? It's not working for me no matter what name variation I try.

**Comment by DirtyRacer1337** [comment]
> > Looks like subsites still working https://handsonhardcore.com/videos/babe+banged+in+the+steam+room/22986
> 
> Is HandsOnHardcore still matching for you? It's not working for me no matter what name variation I try.

Fixed in 99000f37eb05e722ac3815beec7732cbc57226fd

**Comment by drraymond27** [comment]
Hello, I Tried with many variations with DDF sites and subsites and nothing, no match.

**Comment by MrDemous** [comment]
> Hello, I Tried with many variations with DDF sites and subsites and nothing, no match.

Handsonhardcore is working fine for me after @DirtyRacer1337 's fix

**Comment by drraymond27** [comment]
> > Hello, I Tried with many variations with DDF sites and subsites and nothing, no match.
> 
> Handsonhardcore is working fine for me after @DirtyRacer1337 's fix

Thanks, bro, also other subsites working too. only in Other DDFNetwork Sites list
