### ISSUE TITLE
Badoink VR - IndexError: list index out of range

### ISSUE THREAD

**Issue by pedrolara-boop** [PAhelper/PhoenixAdult.bundle#671]
I'm getting the following error for
https://badoinkvr.com/members/vrpornvideo/the_center_of_attention-324984/:

> 2020-03-22 18:11:25,367 (7fd2a7be1700) :  INFO (__init__:1209) - ******UPDATE CALLED*******
> 2020-03-22 18:11:25,368 (7fd2a7be1700) :  INFO (__init__:1212) - 469
> 2020-03-22 18:11:25,369 (7fd2a7be1700) :  DEBUG (networking:143) - Requesting 'https://www.badoinkvr.com/vrpornvideo/the_center_of_attention-324984/'
> 2020-03-22 18:11:26,246 (7fd2a7be1700) :  DEBUG (networking:143) - Requesting 'https://www.badoinkvr.com/vr-pornstar/siyajey/'
> 2020-03-22 18:11:26,912 (7fd2a7be1700) :  DEBUG (networking:143) - Requesting 'https://img.badoink.com/content/scenes/324984/the-center-of-attention-324984_1.jpg'
> 2020-03-22 18:11:27,259 (7fd2a7be1700) :  DEBUG (networking:175) - Not caching 'https://img.badoink.com/content/scenes/324984/the-center-of-attention-324984_1.jpg' (content type 'image/jpeg' not cacheable in Agent plug-ins)
> 2020-03-22 18:11:27,261 (7fd2a7be1700) :  DEBUG (networking:143) - Requesting 'https://img.badoink.com/content/scenes/324984/the-center-of-attention-324984_2.jpg'
> 2020-03-22 18:11:27,524 (7fd2a7be1700) :  DEBUG (networking:175) - Not caching 'https://img.badoink.com/content/scenes/324984/the-center-of-attention-324984_2.jpg' (content type 'image/jpeg' not cacheable in Agent plug-ins)
> 2020-03-22 18:11:27,527 (7fd2a7be1700) :  DEBUG (networking:143) - Requesting 'https://img.badoink.com/content/scenes/324984/the-center-of-attention-324984_3.jpg'
> 2020-03-22 18:11:27,780 (7fd2a7be1700) :  DEBUG (networking:175) - Not caching 'https://img.badoink.com/content/scenes/324984/the-center-of-attention-324984_3.jpg' (content type 'image/jpeg' not cacheable in Agent plug-ins)
> 2020-03-22 18:11:27,782 (7fd2a7be1700) :  DEBUG (networking:143) - Requesting 'https://img.badoink.com/content/scenes/324984/the-center-of-attention-324984_4.jpg'
> 2020-03-22 18:11:28,046 (7fd2a7be1700) :  DEBUG (networking:175) - Not caching 'https://img.badoink.com/content/scenes/324984/the-center-of-attention-324984_4.jpg' (content type 'image/jpeg' not cacheable in Agent plug-ins)
> 2020-03-22 18:11:28,051 (7fd2a7be1700) :  DEBUG (networking:143) - Requesting 'https://img.badoink.com/content/scenes/324984/the-center-of-attention-324984_5.jpg'
> 2020-03-22 18:11:28,312 (7fd2a7be1700) :  DEBUG (networking:175) - Not caching 'https://img.badoink.com/content/scenes/324984/the-center-of-attention-324984_5.jpg' (content type 'image/jpeg' not cacheable in Agent plug-ins)
> 2020-03-22 18:11:28,314 (7fd2a7be1700) :  CRITICAL (agentkit:1091) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://+vrpornvideo+the_center_of_attention-324984+|469?lang=en' (most recent call last):
>   File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-740d4c206/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1089, in _update
>     agent.update(obj, media, lang, **kwargs)
>   File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 1484, in update
>     metadata = PAsearchSites.networkBadoinkVR.update(metadata, siteID, movieGenres, movieActors)
>   File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkBadoinkVR.py", line 81, in update
>     backgroundURL = detailsPageElements.xpath('//img[@class="video-image"]')[0].get("src").split('?')
>   File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-740d4c206/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
>     _getitem_           = lambda x, y: x.__getitem__(y),
> IndexError: list index out of range

**Comment by DirtyRacer1337** [comment]
I tested it right now and it works, strange...

**Comment by pedrolara-boop** [comment]
Yeah. Don't know why it happen.
Sorry.
