### ISSUE TITLE
Tushy not matching

### ISSUE THREAD

**Issue by mercabilis** [PAhelper/PhoenixAdult.bundle#68]
Hello,
I've got a problem matching scenes from Tushy, I think it used to work before tho.
I've tried multiple naming convention and do not get any results even looking manually.
Here are examples of stuff I've tried.

Tushy - 2019-01-31- Gina Valentina Jane Wilde.mp4
Tushy - Being Riley Chapter 2.mp4
Tushy - 2015-06-15 - Aidra Fox.mp4
Tushy - 15-06-08 - Carter Cruise.mp4

I'm not 100% sure how to find or attach matching logs

**Comment by PAhelper** [comment]
I recently made a change to Tushy so i probably broke something. I thought I tested everything pretty thoroughly. I'll take a look...

**Comment by PAhelper** [comment]
Alright, I checked and I can't get it to mess up. I don't have these 4 scenes specifically, but I have 27 others and they all match just fine. I think we're going to need those logs. First find your Plex main folder:

Plex main folder location:

    * '%LOCALAPPDATA%\Plex Media Server\'                                        # Windows Vista/7/8
    * '%USERPROFILE%\Local Settings\Application Data\Plex Media Server\'         # Windows XP, 2003, Home Server
    * '$HOME/Library/Application Support/Plex Media Server/'                     # Mac OS
    * '$PLEX_HOME/Library/Application Support/Plex Media Server/',               # Linux
    * '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/', # Debian,Fedora,CentOS,Ubuntu
    * '/usr/local/plexdata/Plex Media Server/',                                  # FreeBSD
    * '/usr/pbi/plexmediaserver-amd64/plexdata/Plex Media Server/',              # FreeNAS
    * '${JAIL_ROOT}/var/db/plexdata/Plex Media Server/',                         # FreeNAS
    * '/c/.plex/Library/Application Support/Plex Media Server/',                 # ReadyNAS
    * '/share/MD0_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/',        # QNAP
    * '/volume1/Plex/Library/Application Support/Plex Media Server/',            # Synology, Asustor
    * '/raid0/data/module/Plex/sys/Plex Media Server/',                          # Thecus
    * '/raid0/data/PLEX_CONFIG/Plex Media Server/'                               # Thecus Plex community    

Then from there, go into the Logs/PMS Plugin Logs and grab com.plexapp.agents.phoenixadult.log, post the contents here.

**Comment by mercabilis** [comment]
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/2828235/com.plexapp.agents.phoenixadult.log)
 There might be some unrelated stuff I have other stuff in the same library

**Comment by mercabilis** [comment]
hmmm it might be a permission thing? I looked at the folder and it doesn't have the same permissions as the rest of the plugins, gonna try that

**Comment by PAhelper** [comment]
Logs show you are getting a HTTP 403: Forbidden error message when trying to access the site.

If you manually go to https://www.tushy.com/search?q=Tori%20Black%20Misha%20Cross does that load for you? It might also be a temporary ban on your IP if you scanned a whole boatload of Tushy files at once... like a throttling mechanism of their website.

**Comment by mercabilis** [comment]
It works locally, how would I try to load this page from my remote server through ssh? should I curl it? I'm not experienced much :(

**Comment by mercabilis** [comment]
![image](https://user-images.githubusercontent.com/40441023/52216814-091f6e80-288f-11e9-9822-99c4957fa61b.png)
This is what I'm getting, so I guess cloudflare is blocking me? I've never sent a lot of request at once to any of the greg lansky sites I'm pretty sure :/ I have like 6 videos from them tops

**Comment by PAhelper** [comment]
Yeah, looks like it :(
