### ISSUE TITLE
NA random results

### ISSUE THREAD

**Issue by dsrtusr88** [PAhelper/PhoenixAdult.bundle#688]
is there a way to do a direct scene url grab?  I have no reliable way of pulling scenes, where na "scene title" used to work flawlessly.  when I do that now, I get results, just a random assortment.  even when i hone in and use the sub-site, results are mixed on that.

**Comment by DirtyRacer1337** [comment]
You can use SceneID.
For example in `https://www.naughtyamerica.com/scene/kagney-linn-karter-gets-fucked-25907`
SceneID is `25907`

**Comment by dsrtusr88** [comment]
That worked!  For anyone else, I used naughtyamerica instead of the sub-studio in those cases.
