### ISSUE TITLE
Twistys only matching 6 scenes

### ISSUE THREAD

**Issue by bags1975** [PAhelper/PhoenixAdult.bundle#69]
Lot's of missing scenes from the Twistys search, but I have also noticed that only 6 scenes come up on an actor search. This is a limitation of the sites search functionality I believe.

**Comment by PAhelper** [comment]
I should be able to expand that if there is a page 2, 3, etc.

Which scenes can't you find by name?

**Comment by PAhelper** [comment]
Unfortunately the "See All" button just takes you to the "Join Now" page. Even going to the actor's page on the site still only lists the same 6 (most recent?) scenes. If you want to find anything further back than that you'll have to search by the scene name.

**Comment by bags1975** [comment]
Scene names don't work either for example Back To The Good Ol' Days comes up in the search, but redirects back to the Join Now page. So neither the scene title or the actress (Lexi Belle) return the right result. I think this is just a limitation of the Twistys site and not much can be done, but I thought I would give a heads up.
