### ISSUE TITLE
Brazzers scene tagging issue

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#696]
I am trying to tag https://www.brazzers.com/scenes/view/id/4016123/valentines-day-affair-unseen-moments/ the agent finds the scene but does not tag the cast info/photo's and the date is also missing.

The strange thing is that the "main" scene https://www.brazzers.com/scenes/view/id/3983751/brazzers-live-valentines-day-affair/ tags perfect! Nothing missing there!

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4439023/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
I think that's because scene has over 100 tags, that limit was increased in #689, are you updated?

**Comment by insickin** [comment]
Strange, I thought that I was on the latest update but after updating to the latest release it works!
