### ISSUE TITLE
JulesJordan improvements

### ISSUE THREAD

**Issue by PAhelper** [PAhelper/PhoenixAdult.bundle#70]
It seems like there is a lot more art assets available to JulesJordan than what's being grabbed by the current code. Grabbing all of the art assets would be overkill, but mathematically or randomly choosing from all available assets should be doable.

Also the video background isn't being pulled as a background art I don't think.

Also some (all?) of the scenes contain the name of the DVD they are from, and that can be added as another Collection.

There might have been a director on there too...

**Comment by chempke** [comment]
How about to add the JulesJordan subsites like manuelferrara.com, theassfactory.com and spermswallowers.com? 
There are some scenes that not include on the main page julesjordan.com.

**Comment by PAhelper** [comment]
I added support for the other sites this morning in fact.

Also should add full movie matching support.

**Comment by PAhelper** [comment]
Ok, additional sites added, bugfixes done and additional art assets done.

**Comment by yes12397** [comment]
thanks for all the effort
after testing Jules Jordan network I have some suggestions that would be helpful

some of the network sub channels dont have the exact content in other. example:
some videos in Manuel Ferrara site are not available in Jules Jordan or the opposite.

do you think if its better to make Jules Jordan as a network and to have the others as sub? 


searchSites[522] = ["Manuel Ferrara","Manuel Ferrara", "https://www.manuelferrara.com","https://www.manuelferrara.com/trial/search.php?query="]
searchSites[523] = ["The Ass Factory","The Ass Factory", "https://www.theassfactory.com","https://www.theassfactory.com/trial/search.php?query="]
searchSites[524] = ["Sperm Swallowers","Sperm Swallowers", "https://www.spermswallowers.com","https://www.spermswallowers.com/trial/search.php?query="]

 ###############
            ## Manuel Ferrara
            ###############
            if siteNum == 522:
                if searchSiteID == 9999 or searchSiteID == 522:
                    results = PAsearchSites.siteJulesJordan.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)

            ###############
            ## The Ass Factory
            ###############
            if siteNum == 523:
                if searchSiteID == 9999 or searchSiteID == 523:
                    results = PAsearchSites.siteJulesJordan.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)

            ###############
            ## Sperm Swallowers
            ###############
            if siteNum == 524:
                if searchSiteID == 9999 or searchSiteID == 524:
                    results = PAsearchSites.siteJulesJordan.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)

we should change the PAsearch.siteJulesJordan ... 

hope my comments are useful as I mentioned before I don't have a coding back ground but am a fast Learner so i can support in this work.

**Comment by woodbridgesub** [comment]
Thanks for your work on improving the pulled metadata for JuelsJordan. Would it be also possible to limit the collection tags for JulesJordan scenes to just "JulesJordan" - right now, each scene pulls "JulesJordan" but also whatever the individual scene is titled. 
For instance, julesjordan.18.01.16.jill.kassidy.mp4 pulls gets added to the JulesJordan collection, but also creates a new collection named "Jill Kassidy's First Interracial!"

I think it's a bit overkill to have each scene create 2 collections, especially since it's a collection of just one item....as a request, can we get this changed?

**Comment by PAhelper** [comment]
I think the second collection is the movie that scene came from, with the idea being that you can then put the movie cover on that collection and treat it as a complete movie. I'll double check that though.

**Comment by woodbridgesub** [comment]
Actually, you're right, that makes complete sense! I retract my previous request.
On the subject of whole JulesJordan movies, I keep running into an issue where a movie search will not find the movie title, but does find the individual scenes for that movie.
For example, JulesJordan.18.11.12.Manuels.Fucking.POV.10.mp4 will find the scenes within that movie, each with a specific artist, but not the entire movie itself. Is there any way to add whole movies, or is that not possible with this agent?

**Comment by PAhelper** [comment]
It's possible, and on my to-do list. Probably this week.

**Comment by blackibanez** [comment]
Hello,

PhoenixAdult.bundle it’s videos agent, not movies agent. This is why, JulesJordan search results show only scenes, and not movies. If you need an agent for movies,  you can use AdultDVDEmpire.bundle. 
I think, include movies into JulesJordan it’s not a really good idea, but it’s just my point of view, ;-)

**Comment by claygoldfinch** [comment]
Sitelist has been updated to reflect JJ status (scenes supported, full movies not supported). Just scanned the JJ code and tested a scene, it appears to be scraping a background image, video screencaps, and several photos. Movie name is also scraped. Going to close this as it's a dead thread.
