### ISSUE TITLE
devilsfilm not matching certain scenes!!

### ISSUE THREAD

**Issue by mukalaaa** [PAhelper/PhoenixAdult.bundle#701]
hi guys 

so i tried matching three scenes from a movie called menage a trans #02 
the first one was matched easily  devilsfilm.18.06.04.riley.nixon
the third was matched easily devilsfilm.18.06.10.ember.snow

but the second, i cannot find it or match it at all devilsfilm.18.06.08.summer.day

is there something wrong with the naming format or is it some issue with the website itself ?  

Also, I noticed that none of the devilsfilm scenes are matched automatically! I have to to manually match them and the option that appears which is the right one says 75% others show higher numbers or lower numbers. any ideas?

**Comment by yes12397** [comment]
Personal Recommendation which I do : Use Scene ID for search with the Following structure will make it clean and clear
>Folder name  : "the Video name "
                   > File name : DevilsFilm - XXXXX
Example For you Case

>Folder (Menage A Trans #02 - Scene 2)                   
                 > File (DevilsFilm - 132999)

hope this is helpful
