### ISSUE TITLE
Feature request: save metadata along media files

### ISSUE THREAD

**Issue by mukalaaa** [PAhelper/PhoenixAdult.bundle#702]
PhoenixAdult plugin is an amazing work of art. somehow, our libraries are well organized and pretty to look at thank to the outstanding work from you guys. I wish there is a way for us to donate and help grow this plugin "maybe there is, but I don't know about it" please point me to it and I will gladly contribute to help keep this plugin alive and growing. 

Now, I don't know if this is the right place to request and suggest such a feature so please forgive me if this is not the right place. 

Now, that we organized hundreds and thousands of scenes. an issue came up when I was setting up a new server or move my files for an reason. But, that means we lose all the metadata that we spent months downloading and fixing matches...etc 

it would be the best feature ever if we could download posters, actors and metadata in the folder of each scene. This way, we can move our files if we need to or at least saves us days of work when we setup a new server. 
 
there is a plugin in GitHub called LAMBDA, it is a Plex agent that creates and uses local metadata but somehow it doesn't appear under PhoenixAdult.bundle agent in Plex. so I cannot use it with your amazing plugin. 

any thoughts? or a hint if this can be implemented or not?

**Comment by mukalaaa** [comment]
@DirtyRacer1337, thanks for your help... unfortunately, after I tried replacing line #35 as you suggested, which totally worked by the way in terms of showing Lambda under PhoenixAdult agent, I found out that Lambda only exports metadata of IMDB, TVDB movies and shows only!!

are there any plans on implementing such a feature within our beloved PhoenixAdult.bundle? 
any suggestion or work around to export metadata downloaded via PhoenixAdult?

**Comment by DirtyRacer1337** [comment]
It's working on my tests, I think better ask developer of lambda about this, also I found out that actors missing in nfo files

**Comment by mukalaaa** [comment]
Ok, You are right...it is working... I think I needed to relaunch plex before i test it 

Thanks a lot man 

Also, I have been in contact with the developer of Lambda because it needs more improvements to accommodate PhoenixAdult.bundle. for example, it doesnt show all genres or actors yet

but thanks a lot, i hope your fix will be implemented in the master code permanently
