### ISSUE TITLE
PAactors.py name replacements not happening after first newActor

### ISSUE THREAD

**Issue by PAhelper** [PAhelper/PhoenixAdult.bundle#71]
So a lot of the Joymii actresses have different names in the rest of the industry. Some are even pretty common, like "Valentina N." is obviously Valentina Nappi. I have added several of them to PAactors to be replaced, but noticed that only the first actor passed to PAactors actually gets replaced for some reason. I troubleshot for quite a while and couldn't figure it out. Needs more research.

**Comment by insickin** [comment]
Another "problem" with the Joymii actresses is that the wrong photo's are coupled with the actresses names.
For example; the actress Ariel [https://joymii.com/search?query=ariel](url) (a redhead) doesn't look like the actress in the photo provided from the agent.

**Comment by PAhelper** [comment]
Joymii is bad about using their own alias for the actresses, when they have another name they use in the industry. The resolution to your problem will be to find out what Ariel goes by on every other site, and we can get her added to PAactors with her more common name. Then it should pull better a better picture for her. The same is true for almost all Joymii actress listings...

**Comment by GGuy35** [comment]
I added as many aliases to PAactors as I could find today for Joymii using indexxx as reference. Also the first line had used "is" instead of an "=". Hopefully that will help with identifying actresses and fix this bug.

**Comment by PAhelper** [comment]
I just tested the one I was having trouble with, and it worked at intended. Good catch and thanks for the assist!
