### ISSUE TITLE
Girlfriends Films Genres

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#714]
I am tagging my Girlfriends Films collection but when looking at the tagged genres I'm finding that not all genres are being tagged!

For example:

Lesbian PsychoDramas #18 the movies version (.com site) tags only "Brunette" and the DVD version (.net site) only tags "all sex" "Popular with Women"

On the respective sites the tags/categories are stated as: 
movie version: 
69 Big tits Blonde Brunette Feet Fingering Kissing Lingerie Masturbation Natural Tits
DVD version:
All Girl / Lesbian, All Sex, Popular with Women

You see that there are a lot more tags/categories on the site's than the agent tags!

**Comment by dappleyard** [comment]
Is this actually matching the scene correctly.  I am trying to match only on the scene ID and the match is always wrong and the correct scene doesn't appear in the list for a manual match.

**Comment by insickin** [comment]
In my case I'm tagging whole DVD releases and the agent/I'm using the title of the DVD in some rare cases I'd needed to use the scene ID. I have some separate scene's but I haven't got around to them so I can't help you with that...

**Comment by DirtyRacer1337** [comment]
@insickin Something with API on this scene, it has only one `Brunette` tag.
@dappleyard Girlfriends Films doesn't have searching by id.

**Comment by insickin** [comment]
> 
> 
> @insickin Something with API on this scene, it has only one `Brunette` tag.
 The same ting happens when tagging "Lesbian PsychoDramas #27", only "Lesbian" and "Archive" are tagged but as you can see on the site there are much more categories! Where/how can I check the API of Girlfriends Films?

After a little bit more investigation it seems that the problem occurs with all (in any case) DVD/Movie tags!

**Comment by insickin** [comment]
@DirtyRacer1337 can you have a look at this?

**Comment by DirtyRacer1337** [comment]
This is not a problem, movie tags are not filled, I can add the ability to take tags from the corresponding scenes later.

**Comment by insickin** [comment]
Thanks now the agent tags a lot more tags!
