### ISSUE TITLE
Legalporno no longer downloading movie details

### ISSUE THREAD

**Issue by acelrod** [PAhelper/PhoenixAdult.bundle#725]
I noticed that I am now unable to pull movie information and actor information from the Legalporno sites now... I started seeing this last night. Is this a temporary issue?

**Comment by a18project** [comment]
Works fine for me right now. Mind posting a log?

**Comment by acelrod** [comment]
Oh! I just downloaded and installed the current release, and all is working as expected again. 👍🏼
