### ISSUE TITLE
problem matching some scenes from ddfbusty

### ISSUE THREAD

**Issue by mukalaaa** [PAhelper/PhoenixAdult.bundle#733]
Hello guys,
so I have a collection of hundreds of ddfbusty scenes. 
most of them are matched flawlessly but some cannot be matched no matter the several naming formats that I have tried.

Here is couple examples:
ddfbusty 18 12 05 angela white
ddfbusty 15 02 06 tigerr benson

I tried including the scene name and I even tried the scene ID but still, I could not get them to match!!

Any ideas?

**Comment by pedrolara-boop** [comment]
Do you have the link for the scenes?

**Comment by mukalaaa** [comment]
@pedrolara-boop 
sorry for the late reply 

here is the link for the first scene 
https://ddfbusty.com/videos/untitled/22120
which I named : ddfbusty 18 12 05 angela white

here is the link for the second scene
https://ddfbusty.com/videos/dream+and+cream+baby/19603
which I named: ddfbusty 15 02 06 tigerr benson

Thanks a lot

**Comment by mukalaaa** [comment]
@pedrolara-boop 
Did you look into the links i posted earlier? any update?

I am thankful for your help and assistance

**Comment by DirtyRacer1337** [comment]
@mukalaaa Try to search it by `SceneID` with #775
