### ISSUE TITLE
Problems with Agent and Folder structure

### ISSUE THREAD

**Issue by RazerGT** [PAhelper/PhoenixAdult.bundle#738]
I'm sorry for my bad english. I have the following problem. The agent creates a collection, but without the matching cover and without information. What should the folder structure look like? Here is an example of how I use it: Evil Angel \ Anal - Acrobats - 08 \ EvilAngel - 2013-10-22 - 60166

The media library is set up as follows:
Media library type = film
Collection: Hide items if in a collection
Scanner: Plex Video Files Scanner
Agent: PhoenixAdult
PhoenixAdult settings = empty

What are the best settings in general?

Thanks for the help, greetings

**Comment by DirtyRacer1337** [comment]
Only filename important, if something doesn't work, send logs

**Comment by RazerGT** [comment]
Hi thanks for the quick answer, what do you mean by just filenames? How should I build the folder structure? Can you give me an example, please?
Which log do you need? Plex Media Scanner Analysis, Plex Media Scanner? ... What exact logs do you need?

**Comment by DirtyRacer1337** [comment]
Read [README](https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/README.md#file-naming) and #218

**Comment by RazerGT** [comment]
Okay, thank you for the quick answer. Here is the log.
A little addition to my problem.
Example: Under Collection I see Anal Acrobats, 4 films. In the collection, under elements, Anal Acrobats # 07; Anal Acrobats # 08 listed. However, I would like to see the corresponding collections with covers and information directly under Collection.
I hope you can help me. thank you

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4559184/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Plugin only gives data to Plex, not working with UI. Or I don't get what you mean.
Your log without error, just plugin started.

**Comment by RazerGT** [comment]
Okay, I'll try to describe it again.
All films, for example (EvilAngel) Anal Acrobats, are grouped together in a collection. But there are several episodes of Anal Acrobats # 01-10. I want to see each episode individually under Collection. How do I adjust the settings accordingly?
I hope it is more understandable now.
Thank you!

Sorry, I am from Germany because of my bad English.
