### ISSUE TITLE
No Date info for TeamSkeet

### ISSUE THREAD

**Issue by boivinx7** [PAhelper/PhoenixAdult.bundle#756]
I don't get any Date info from Teamskeet in Plex.
Is the logs somewhere else then the plex dir

**Comment by DirtyRacer1337** [comment]
Read carefully.
[TeamSkeet Network](https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/sitelist.md#teamskeet-network)
[manualsearch doc](https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/manualsearch.md#notes)

**Comment by boivinx7** [comment]
AAAAAA Good to know, Thanks
I was just looking at anything that I can migrate easy.
Thanks
