### ISSUE TITLE
Brazzers Exxxtra Matching Issue

### ISSUE THREAD

**Issue by MajesticMaerlyn** [PAhelper/PhoenixAdult.bundle#758]
Hi,

I have been unable to get a match on the following:

Brazzers Exxxtra - 10414 - Don't Touch Her 3
Brazzers Exxxtra - 10503 - Don't Touch Her 4

I have tried file name variants and URL pointing. These were working in a previous revision of PA.
The search only returns results for Don't Touch Her 2 / 5 / 6 / 7. All other files in the series, with the same naming scheme, work correctly.

I noticed on using Brazzers search they appear, but only if "View All" is selected. Not sure if that helps?

Cheers

**Comment by DirtyRacer1337** [comment]
Brazzers E**xx**tra not Brazzers E**xxx**tra, that's why you can't find it by sceneID

**Comment by MajesticMaerlyn** [comment]
Omg I must have had a huge brainfart - please accept my apologies for
missing something so stupid :)
