### ISSUE TITLE
SexyHub not matching

### ISSUE THREAD

**Issue by Poke999** [PAhelper/PhoenixAdult.bundle#76]
Hi,
Thanks again for your add-ons , very much appreciated.
I have tested the new SexyHub but I have not managed to get it to work. I am using the latest version of your PhoenixAdult.bundle
Tried the following : 'SexyHub - Hot Fuck for Squirting Colombian' and it did not work.
I hope you will be able to help
The Log showed some error messages log attached
/Pete
[SexyHub 20190211 Log.txt](https://github.com/PAhelper/PhoenixAdult.bundle/files/2850832/SexyHub.20190211.Log.txt)

**Comment by PAhelper** [comment]
I just pushed a bugfix that should straighten this out. I think I broke it when I started adding FakeHub sites... Give the new code a test and let me know if you have more trouble, or feel free to close this Issue if it's working.

**Comment by Poke999** [comment]
Hi
I have now tested 4 entries on SexyHub and they all work, so I assume everything is ok
Thanks for your help
Closing issue
/Pete

**Comment by bags1975** [comment]
Sexyhub is not matching for me still. Plex on Windows
