### ISSUE TITLE
Find Adulttime API key

### ISSUE THREAD

**Issue by pedrolara-boop** [PAhelper/PhoenixAdult.bundle#761]
Sites like girlway and all girl massage now offer its members the website Adulttime (www.adulttime.com), it has many sites (list below), on a single website. The previous implementation of girlsway, the non-API one, was able to find the videos using the ID.
The search on adulttime is blocked to non-memebers, however, I could provide the information needed. The current API implementation for girlsway and many others is already quite robust, but there are a few missing sites. 

21 Bonus (2944)
21 Naturals (975)
21 Sextreme (4483)
21 Sextury (10427)
Adam and Eve Pictures (36)
Adult Time Films (64)
Adult Time Originals (138)
Alt Erotic (40)
Amateur Allure (1)
Analized (61)
Anatomik Media (32)
Animeshin Club (3)
Archangel Video (35)
Bare Maidens (30)
Black Label Mag (25)
Burning Angel (1524)
Club Seventeen (32)
Deeper (3)
Devil's Film (7162)
Evil Angel Films (5)
Exxxtra Small (17)
Fame Digital (10392)
Fantasy Massage (2155)
Femjoy (59)
Filthy Pov (57)
Fister Twister (25)
Fit18 (12)
Girls Out West (26)
Girls Rimming (29)
Girlsway (1799)
Grooby (11)
HitzeFrei (35)
Holly Randall (65)
Holly Randall Productions (6)
Hot Guys Fuck (26)
Is This Real (5)
Jacquie et Michel (11)
Javhub (10)
Jay Rock Films (129)
JoyBear (35)
Joymii (55)
Korina Kova (12)
Lightsouthern Cinema (11)
Love Her Feet (26)
MMP Network (21)
MixedX (25)
My Pervy Family (55)
Naked News (6)
New Sensations (8)
Pegas Productions (45)
PervCity (54)
Pink Eiga (3)
Pretty Dirty (206)
Pure Taboo (252)
RealSensual (43)
Rocco Siffredi (2150)
SINematica (1)
Scarlett Revell (7)
Sinful XXX (53)
Spizoo (124)
Super Horny Fun Time (31)
Tushy (4)
Vivid (7050)
Vixen (5)
Wasteland (59)
Wolf Wagner (25)
XConfessions (23)

A more simple workaround is to bring back the non-API implementation of Girlsway that finds the videos using the ID.

https://tsmkfa364q-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(3.35.1)%3B%20Browser%20(lite)%3B%20react%20(16.13.1)%3B%20react-instantsearch%20(5.7.0)%3B%20JS%20Helper%202.26.0&x-algolia-application-id=TSMKFA364Q&x-algolia-api-key=NGM2MDVlOTJjNDI5ZWU1NDlkMGRhOTZmMmVmMzQ3YWU3NDAxZWE2YmU1MjIwN2I5MWM4YjUxNGU0ZTYzZmQ3YXZhbGlkVW50aWw9MTU4OTUwMjE5NCZyZXN0cmljdEluZGljZXM9YWxsJTJBJmZpbHRlcnM9c2VnbWVudCUzQWFkdWx0dGltZSZ1c2VyVG9rZW49NDIxYTZjNmJiN2I2Zjg0NDkwNTE3MWQ0ZTFkMjcxZjEzMWUxMmQxOWFhYTRlNjgxYWUyYjczZjU3N2Q1OTQyZQ%3D%3D

**Comment by DirtyRacer1337** [comment]
Send logs, id searching should be working.
And yes through the adulttime I can access more sites.

**Comment by pedrolara-boop** [comment]
The ID on the new API implementation is working for girlsway  :)
However, on the old implementation, I was able to match all adulttime content via the girlsway script using the ID. I would search "girlsway + ID of the adulttime video". It would incorrectly label as Girlsway but all the rest was correct.

Here is an ID 171221 of an adulttime video.

https://github.com/PAhelper/PhoenixAdult.bundle/blob/495c0a7060fce578062a30fee1d0e0477ed89cf2/Contents/Code/siteGirlsWay.py

I was wondering if it wouldn't be possible to bring it back to provide support for the missing ones.

**Comment by DirtyRacer1337** [comment]
Try to add site, like this
```python
searchSites[877] = ["Adult Time","Adult Time","https://freetour.adulttime.com","https://tsmkfa364q-dsn.algolia.net/1/indexes/*/queries"]
```
that should work with all Adult Time network
