### ISSUE TITLE
Testing 21sextury

### ISSUE THREAD

**Issue by yes12397** [PAhelper/PhoenixAdult.bundle#77]
following channels are working fine:
AnalTeenAngels
DeepthroatFrenzy
DPFanatics
FootsieBabes
Gapeland
LezCuties
PixandVideo

following channels need to be added:
Aletta Ocean Empire (legacy - last update: 6 years ago production)
Anal Queen Alysa (legacy - last update: 7 years ago production)
Asshole Fever (up to date) <--------  must be added 
Blue Angel Live (legacy - last update: 7 years ago production)
Butt Plays (last update: 1 year ago)
Cheating Whore Wives (legacy - last update: 7 years ago production)
Club Sandy (last update: 11 months ago)
Cuties Galore (legacy - last update: 5 years ago production)
Hot Milf Club (legacy - last update: 11 years ago production)
Lets Play Lez (legacy - last update: 8 years ago production)
Nude Fight Club (legacy - last update: 6 years ago production)
Only Swallows (legacy - last update: 13 years ago production)
Sex With Kathia Nobili (legacy - last update: 5 years ago production)
Sweet Sophie Moone (legacy - last update: 7 years ago production)

while testing i tried 21sextury - (title) result doesnt show
testing with scene ID  results were ok with poster and actors 
 but the studio showing high mile network and tag line 21sextury

hope my testing is fine with you and its your choice if you want to add legacy metadata

**Comment by PAhelper** [comment]
Asshole Fever is already included.

It looks like some of these legacy sites can be added while others can't. I will add what I can (basically the ones with a site search)

All of my 21Sextury matches properly show the Studio as "21Sextury" and the Tagline as "DP Fanatics" or "Asshole Fever", etc. Which scenes are tagging them as Studio "Mile High Network" and Tagline "21Sextury"? Better yet, can you Fix Match one of the scenes giving you trouble, then post your log file?

**Comment by yes12397** [comment]
an example try this title:
21sextury - dew me baby
result is showing
dew me baby [mile high network / 21sextury] 2017 -04 -11]

sorry if it might be a stupid question but how to pull the logs  of the agent so i can forward it to u

**Comment by PAhelper** [comment]
I'm downloading that scene to test.

To locate the log file, find your Plex installation directory:
* '%LOCALAPPDATA%\Plex Media Server\'                                        # Windows Vista/7/8
* '%USERPROFILE%\Local Settings\Application Data\Plex Media Server\'         # Windows XP, 2003, Home Server
* '$HOME/Library/Application Support/Plex Media Server/'                     # Mac OS
* '$PLEX_HOME/Library/Application Support/Plex Media Server/',               # Linux
* '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/', # Debian,Fedora,CentOS,Ubuntu
* '/usr/local/plexdata/Plex Media Server/',                                  # FreeBSD
* '/usr/pbi/plexmediaserver-amd64/plexdata/Plex Media Server/',              # FreeNAS
* '${JAIL_ROOT}/var/db/plexdata/Plex Media Server/',                         # FreeNAS
* '/c/.plex/Library/Application Support/Plex Media Server/',                 # ReadyNAS
* '/share/MD0_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/',        # QNAP
* '/volume1/Plex/Library/Application Support/Plex Media Server/',            # Synology, Asustor
* '/raid0/data/module/Plex/sys/Plex Media Server/',                          # Thecus
* '/raid0/data/PLEX_CONFIG/Plex Media Server/'                               # Thecus Plex community    

From there go into /Logs/PMS Plugin/ and then locate the file named com.plexapp.agents.phoenixadult.log. You can either copy/paste the text here, or attach the whole file to the post.

**Comment by PAhelper** [comment]
I downloaded Dew Me Baby and I'm seeing the same behavior you are. I should have this bug squashed pretty quickly now...

**Comment by PAhelper** [comment]
I have solved this mostly. If you search for "21Sextury - Dew Me Baby" it will now list in search as "Dew Me Baby [21Sextury] 2017-04-11". If you match it, it will properly identify that scene was from "Butt Plays" and mark the Tagline and Collection from "Butt Plays".

The same should be true for all the other legacy channels you mentioned.

I also fixed the bug with Mile High Media showing up. That was just bad numbering on my part.

The only thing that doesn't work currently is searching for "Butt Plays - Dew Me Baby" will not work. You have to search the scene as "21sextury - scene name" and it will find the proper channel label when it pulls the metadata.

**Comment by PAhelper** [comment]
I think I've done all I can here. If I tried to add every sub-channel that 21Sextury has ever had (like Butt Plays in the example above), the list would be immense, and I have all the sub-channels they currently advertise included. You can always match the scene to 21Sextury and it will adopt the correct sub-channel.

Closing issue.
