### ISSUE TITLE
Dorcelclub blurry matches

### ISSUE THREAD

**Issue by dsrtusr88** [PAhelper/PhoenixAdult.bundle#770]
I have a paid account on dorcelclub and I noticed unlike other paid sites, they use the same url string if you're logged in or out.  That got me thinking that there should be a way to pull preview images for matches even if you're logged out.  

For https://www.dorcelclub.com/en/scene/759/Hardcore_orgy_and_fetish_games_for_Sophia_Bella
Logged out image: https://public16-content.dorcelclub.com/pics/scene/07/59/759_1_scenedefault_1_966_543_fb-b31_a21e52f9.jpg
Logged in image: https://public16-content.dorcelclub.com/pics/scene/07/59/759_1_scenedefault_1__433_rs_1a5178c1.jpg

Is there a way to use that API workaround to pull the public facing image that isn't blurry on search results?

**Comment by DirtyRacer1337** [comment]
Url can be shorted to `https://public16-content.dorcelclub.com/pics/scene/07/59/759_1_scenedefault.jpg`

**Comment by dsrtusr88** [comment]
can that be easily coded in the agent?
