### ISSUE TITLE
Tag videos matched with Adulttime with the correct studio

### ISSUE THREAD

**Issue by pedrolara-boop** [PAhelper/PhoenixAdult.bundle#776]
The implementation of the adulttime is great however it always matches the video as adulttime as the studio. Looking at the information provided via API the right studio name seems to be present.
Would it be possible to use the studio value instead of always matching as Adulttime?

It would still be searchable as "adulttime - video title" to avoid any conflicts.

**Comment by DirtyRacer1337** [comment]
Show examples, for me everything is correct, it's called as `studio_name` in API
```python
# Studio
metadata.studio = detailsPageElements['studio_name']
```

**Comment by pedrolara-boop** [comment]
You are right. It is actually confusing since some studios like Girlsway will show, however, JaysPOV shows as "Adult Time". These are examples to try to understand how it names things.

Catching My Stepmom Alexis
network_name: "Jay Rock Films"
sitename_pretty: "Jayspov"
studio_name: "Adult Time"

Catching the Babysitter Kenzie Reeves with A Guy in our Bed!
sitename_pretty: "Filthypov"
network_name: "Filthy Pov"
studio_name: "Adult Time"

I'm not so sure what is best to do.
