### ISSUE TITLE
Improvements to networkDogfart

### ISSUE THREAD

**Issue by PAhelper** [PAhelper/PhoenixAdult.bundle#79]
Matched a Dogfart video and noticed the search result names sucked.

Also noticed there is no release date, but I'm not sure there's anything we can do about that.

The Summary was truncated with "... read more"

The first 15 or so pictures are pulled, but there are usually a hundred or so to choose from. Rewrite to randomly choose 9 with each reload.

**Comment by blackibanez** [comment]
Hi,

There is not release date in dogfart network.
For description, we should concatenate 2 texts content from <div class="description shorten"> and <span class="more-desc hide">

We can improve search section by ignoring « behind the scene » videos

**Comment by PAhelper** [comment]
I hadn't considered that. I suppose even if somebody had some BTS videos, they would just name then according to [Plex Extras] (https://support.plex.tv/articles/200220677-local-media-assets-movies/#toc-3)

**Comment by d2dyno** [comment]
Any updates on this?

Also, should remove other site entries when searching by site. For example, searching a scene from 'Blacksonblondes' searches the entire network and brings results back from irrelevant sites.

**Comment by claygoldfinch** [comment]
Improved substantially in PR #235. Read PR notes for more info. 

Instances where actresses have performed for the same site multiple times are still going to cause some issues with matching. Unfortunately it doesn't seem as there's any way we can improve this, as Dogfart names every scene "Actress", doesn't include publish dates, and sceneIDs are essentially garbage.

@d2dyno

**Comment by claygoldfinch** [comment]
PR merged, closing issue.
