### ISSUE TITLE
Nympho not fetching scene date

### ISSUE THREAD

**Issue by whadup93** [PAhelper/PhoenixAdult.bundle#803]
Nympho does not fetch the scene date. 

I figured out that the date information is actually not existing in the scenes HTML. 

In the other two SteppedUpMedia network pages (Swallowed & TrueAnal) the info is present inside the HTML and fetching works fine too.

I have no elegant solution on how to fetch the scene date elsewhere.

**Comment by DirtyRacer1337** [comment]
Add a date to your filename
https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/manualsearch.md#notes

**Comment by whadup93** [comment]
Thanks for the help. The 'date add' info is missing here:
https://github.com/PAhelper/PhoenixAdult.bundle/blob/master/docs/sitelist.md#swallowed--trueanal--nymphos--allanal--matching-type-exact---direct-url
