### ISSUE TITLE
Porndoe Premium Network subsites no matching

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#810]
Hello, I can't match videos from "Tu Venganza", "Her Big Ass" and "Carne Del Mercado", I tried with many options and nothing, the search matched to others subsites.

Help, please

**Comment by DirtyRacer1337** [comment]
Read #218

**Comment by drraymond27** [comment]
OK, I read, I updated the bundle, and nothing, no match. Please help!
