### ISSUE TITLE
Issues in JulesJordan

### ISSUE THREAD

**Issue by woodbridgesub** [PAhelper/PhoenixAdult.bundle#83]
I'm on the latest revision of this plugin (as of 02.13.19). Prior to this, most of my JulesJordan scenes were not working. Today, most are working with a few exceptions.

For instance, the following titles properly pulled metadata:
JulesJordan - Riley Reid Rides 2 Cocks At Once, DP'd By The DP Masters [720p].mp4
JulesJordan.16.05.13.Keisha.Grey.XXX.1080p.MP4-KTR.mp4
julesjordan.18.09.22.kissa.sins.interracial.creampie.mp4

But the following did NOT:
JulesJordan.18.08.22.Kissa.Sins.IR.Anal.XXX.1080p.MP4-KTR.mp4
JulesJordan.18.10.28.Keisha.Grey.Natural.Busty.Teen.Milks.Manuels.Cock.XXX.1080p.MP4-KTR.mp4
JulesJordan.16.05.31.Casey.Calvert.Goldie.Rush.Jojo.Kiss.Katrina.Jade.And.Keisha.Grey.XXX.1080p.MP4-KTR.mp4

As an example, the 18.09.22 title above worked, while the very similarly named 18.08.22 title did not pull metadata. A manual search with some editing of the title will eventually find the correct match, but I think there might be minor issues in the latest release.

Thanks for your work on this project!

**Comment by PAhelper** [comment]
The 18.08.22 scene is not named "IR Anal", so it would not match with that name. The 18.09.22 scene IS named "Interracial Creampie" so it matched automatically. If you want the other scene to match automatically, try renaming it "JulesJordan.18.08.22.Kissa.Sins.Ass.is.Open.For.BBC.Business.mp4", or even just "JulesJordan.18.08.22.Kissa.Sins.mp4" should do it...

I'll check on the others, but I'll bet they're just a naming issue too. Or like you said, just manually search and match them. Once they're matched properly you get all the same info.

**Comment by woodbridgesub** [comment]
Appreciate the reply!

So I took your advice and renamed the file as you suggested in your post - and it works perfectly now.

In the end, it seems that what you've put together works in a very solid fashion. To other users reading this, one of the main reasons you may be having issues pulling metadata probably relates to the proper naming of files (check the scene date, spelling of actor names, scene name, etc). On occasion, the media site itself may be updated (such as beta.blacked.com) which may cause issues.

Once again, thank you for your work!

Please feel free to close this issue once you've read it.
