### ISSUE TITLE
Cast Stop Working on Most VR Site not sure if more

### ISSUE THREAD

**Issue by boivinx7** [PAhelper/PhoenixAdult.bundle#845]
VRBangers, badoink network, Naughtyamerica,wankz and more.
Cast disappears on refresh
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4873112/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Match scene again

**Comment by boivinx7** [comment]
Works for Badoink Network and wankz, but not Naughty America,VRBangers

**Comment by DirtyRacer1337** [comment]
VRBangers fixed in 6d81b9fc8a635a0270beb81ee41e529c01c2482a
