### ISSUE TITLE
Manuel Ferrara bug

### ISSUE THREAD

**Issue by yes12397** [PAhelper/PhoenixAdult.bundle#85]
thanks for all the effort
after testing Jules Jordan network I have some suggestions that would be helpful

some of the network sub channels dont have the exact content in other. example:
some videos in Manuel Ferrara site are not available in Jules Jordan or the opposite.

do you think if its better to make Jules Jordan as a network and to have the others as sub?

searchSites[522] = ["Manuel Ferrara","Manuel Ferrara", "https://www.manuelferrara.com","https://www.manuelferrara.com/trial/search.php?query="]
searchSites[523] = ["The Ass Factory","The Ass Factory", "https://www.theassfactory.com","https://www.theassfactory.com/trial/search.php?query="]
searchSites[524] = ["Sperm Swallowers","Sperm Swallowers", "https://www.spermswallowers.com","https://www.spermswallowers.com/trial/search.php?query="]

###############
###############
if siteNum == 522:
if searchSiteID == 9999 or searchSiteID == 522:
results = PAsearchSites.siteJulesJordan.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)

```
        ###############
        ## The Ass Factory
        ###############
        if siteNum == 523:
            if searchSiteID == 9999 or searchSiteID == 523:
                results = PAsearchSites.siteJulesJordan.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)

        ###############
        ## Sperm Swallowers
        ###############
        if siteNum == 524:
            if searchSiteID == 9999 or searchSiteID == 524:
                results = PAsearchSites.siteJulesJordan.search(results,encodedTitle,title,searchTitle,siteNum,lang,searchByDateActor,searchDate, searchSiteID)
```
we should change the PAsearch.siteJulesJordan ...

hope my comments are useful as I mentioned before I don't have a coding back ground but am a fast Learner so i can support in this work.

**Comment by PAhelper** [comment]
I don't think I understand your question. When I think of a "network", I think of Brazzers or Mofos. Brazzers has lots of sub channels (as you called them) under it like Real Wife Club, Big Tits at School, BrazzersXxtra and so forth.

Similarly, I think of Jules Jordan as a network that includes JulesJordan.com, ManuelFerrara.com, TheAssFactory.com and SpermSwallowers.com, and I treat it exactly the same as Brazzers in that way. In the Metadata, I set "JulesJordan" as the Studio, then I make the Tagline be the individual sub channel of JulesJordan/ManuelFerrara/TheAssFactory/SpermSwallowers.

If you are asking why each site is broken out separately in the code you snipped, that is for efficiency. With Brazzers, there is a single search field on brazzers.com that encompasses all their sub channels. The search on JulesJordan.com doesn't have all the results from ManuelFerrara or SpermSwallowers (like you said), so we have to do individual searches against each site.

**Comment by PAhelper** [comment]
Merging into #70
