### ISSUE TITLE
network1service - 'Logic' Issue

### ISSUE THREAD

**Issue by PowerModder** [PAhelper/PhoenixAdult.bundle#850]
I was trying to match Twistys scenes using this agent and by using a title pattern like this:
Twistys - SceneID - Actor - SubSite
However, i had some mis-matches which is strange when SceneID is being used which should be 1 scene-related ( 1 searchResult found),100% match. I saw the logs and the agent was finding many results for one scene. According to my knowledge a scene at those networks have a unique ID, the sceneID so no more than 1 scene has it.

Reviewing the network1service.py I noticed that at line 35 this code:
if sceneID and not searchTitle: 

Because of my title pattern i have both fields filled sceneID and searchTitle. This and 'gate' caused to me troubles for right matching. I replaced it with:
if sceneID

And the matching problems were solved. 100% Matching.

**Comment by DirtyRacer1337** [comment]
Use it like `Twistys - SceneID` without anything else or `Twistys - Scene Name`

**Comment by PowerModder** [comment]
Yes I did that and saw it was ok that way but... Because I am a 'freak' :D I want to be able to use OS' File Explorer and use Actor Name to find the scenes of that actor without using Plex. I know that by having actor information and by using Plex I can just click on that particular actor and all the Scenes will be displayed from that library. However, I like to be able to have that ability above. Anyway, It wasn't and "issue" just a sidenote for everyone else that will have the same 'issue' at the future. Also, it was a simple 'fix' regarding what I 'prefer' to use as media Title.
