### ISSUE TITLE
[Feature/Idea - Implemented] - Media Title "Ignore" after specific character 

### ISSUE THREAD

**Issue by PowerModder** [PAhelper/PhoenixAdult.bundle#851]
Hello again :D I hope i am writing at the right 'place' to suggest or better show you an example of a feature that I implement to 'help' my file name system. Basically what I wanted and wrote to previous pull request was to be able to add Actor Names to Media Title. However, some specific sites wants you to enter as a filename a exact URL, the Title or only SceneID and if you add more than that then the agent fails to do the auto-match. You end up to do manual match which is PITA for big collections un-matched content. 
I had this idea to ignore the rest of the mediaTitle after a specific character appears. See it as comments to a programming language. like for example  or # for Python.
Of course, I needed to find a character that will never appear at a Scene Title, Actor etc. I chose ~ (tilde) so it can look as - at the File Explorer and it is an accepted character for File Name at Windows.

The implementation was very simple. Just mess the __init__ file at line 32
From this: `title = media.name `
To this: `title = media.name.split("~")[0]`

In Real Life Example:
VirtualRealPorn supports matching with Exact URL

Before my change:
A title of `VirtualRealPorn - AssBNB` is working BUT a title of `VirtualRealPorn - AssBNB - Baby Nicols` is not working. In fact a title of `VirtualRealPorn - AssBNB - ANYTHING` is not going to work.

After my change:
A title of `VirtualRealPorn - AssBNB` is working AND a title of `VirtualRealPorn - AssBNB ~ Baby Nicols` is ALSO working. In fact a title of `VirtualRealPorn - AssBNB ~ ANYTHING` is working!

So say bye to rename a file title EXACTLY as you should without extra information so the agent can work.
With this you can add whatever extra information after the special character and the agent will just cut the first half before the special character and do the comparison with that bit ignoring your "comments".

Tested it to other sites that are requiring specific Media Title Structure (example Joymii) and is working like a charm.

**Comment by DirtyRacer1337** [comment]
`~` probably not best choice it's home directory in linux, maybe `##`

**Comment by PowerModder** [comment]
@DirtyRacer1337 Any chance for this to become merged at the "official" version? Using ## of course as ~ is not the best choice as you said.

**Comment by DirtyRacer1337** [comment]
Check PhoenixAdult settings page, you can enable and choose symbol(s) for striping.
