### ISSUE TITLE
PornPros Sites only with the exact URL?

### ISSUE THREAD

**Issue by FLalfa1** [PAhelper/PhoenixAdult.bundle#86]
Is it possible to edit the "Other PornPros Sites" (Lubed, Holed, ...) so that they can be assigned in Plex? Or does that only work with the exact URL? Namely, no pictures and no data (studio, website, actors) are downloaded.

**Comment by insickin** [comment]
You'r server is a Linux one? Thanks check:

**Comment by FLalfa1** [comment]
My NAS is a DS 918+ from Synology. It would have to be Lynux.

**Comment by PAhelper** [comment]
So the story with "Exact URL match only":
Most sites have a search function to help you find what you're looking for. In most cases, this metadata agent will use the site's original search function, plug in the filename or your search terms (what you type into Plex), and return the results that the site's original search function would return as if you were typing them directly into the site.

PornPros (and the other sites related to that studio like Lubed, Holed, etc.) do NOT have a search function available to the public. I guess they have one inside their member's section, but that doesn't help. So without the search function, the only way to get this metadata agent to pull all the scene's information is to lead it directly the page yourself. So basically what it does for PornPros sites is go to www.pornpros.com/video/WHATEVER YOU TYPED INTO THE SEARCH BOX and hopefully it finds the page with all the scene's information. It's an unfortunate workaround, but it's better than just saying "Nope, sorry these sites just aren't supported".

In your case, there's another bug related to PornPros sites where all their sites are using a newer SSL certificate that doesn't play nice with Plex on linux (it reportedly works fine in Plex on Windows machines). That's the one insickin was referencing #64

**Comment by leesradler** [comment]
Pahelper, sorry if this seems to be a simplistic question, but I am still not understanding how to match a pornpros site video. I have the following video: https://passion-hd.com/video/hottie-rubdown

Where would I put in that exact video url to get  a match in Plex?

**Comment by SgtBatten** [comment]
title your video PassionHD - Hottie Rubdown

**Comment by PAhelper** [comment]
Seems to be an issue with Linux-based Plex installations and using an older version of Python. Merging into #64
