### ISSUE TITLE
PornDoe no matching

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#866]
[[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4916955/com.plexapp.agents.phoenixadult.log)]

https://porndoe.com

https://porndoe.com/video/867146/petite-blonde-beauties-piper-perri-elsa-jean-have-threesome-in-pov

No matching any videos, I tried with URL, VideoID, Actors Name

**Comment by DirtyRacer1337** [comment]
Read #218

**Comment by drraymond27** [comment]
OK
Site Name - Check
File Name - Check
Log File - Check

Is right now? Please correct me to making well, if you only say "Read" or "Logs", I don't know exactly what you want, I'm new.

**Comment by DirtyRacer1337** [comment]
This site not supported
