### ISSUE TITLE
Pornfidelity without actors cast

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#868]
https://www.pornfidelity.com/

https://tour-cdn.kellymadisonmedia.com/content/episode/mp4_1080p_video_file/143408160/711_amia_miley_trailer-hd_1080p.mp4

[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4923086/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Update again

**Comment by drraymond27** [comment]
Excellent! is working, thanks
