### ISSUE TITLE
Please Add TeenMegaWorld and Subsites

### ISSUE THREAD

**Issue by Duglim** [PAhelper/PhoenixAdult.bundle#87]
Hello, could you please add TeenMegaWorld and Subsites like CreampieAngels?
Thx.

**Comment by insickin** [comment]
> 
> 
> Hello, could you please add TeenMegaWorld and Subsites like CreampieAngels?
> Thx.

Could you post your request here https://github.com/PAhelper/PhoenixAdult.bundle/issues/1 ?

**Comment by PAhelper** [comment]
Merged into #1
