### ISSUE TITLE
Clips4Sale module failing with 'AttributeError: 'list' object has no attribute 'encode''

### ISSUE THREAD

**Issue by albyofdoom** [PAhelper/PhoenixAdult.bundle#878]
site: https://www.clips4sale.com/studio/35625/20638187/vina-sky-in-the-cuckquean-submissive-step-mom-hd-720p

log: [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/4943368/com.plexapp.agents.phoenixadult.log)

Search Term(s):  
clips4sale 2018-11-26 - 35625 - The Cuckquean Submissive Step Mom
Clips4Sale - 35625 - vina sky in the cuckquean submissive step mom hd 1080p

**Comment by DirtyRacer1337** [comment]
Fixed in 2bf03686d5776c6e653ba2e0a534b225a8703f0d

**Comment by albyofdoom** [comment]
> 
> 
> Fixed in [2bf0368](https://github.com/PAhelper/PhoenixAdult.bundle/commit/2bf03686d5776c6e653ba2e0a534b225a8703f0d)

Confirmed, no further issues. Thanks for the quick fix! :)
