### ISSUE TITLE
How to help add new sites

### ISSUE THREAD

**Issue by SgtBatten** [PAhelper/PhoenixAdult.bundle#88]
Hey PA,

I have no experience making plex plugins but am attempting to add the nubiles network. I know this is already on your list but I thought I would try anyway to both learn and maybe help.

Clearly each site has is own py file and I am looking at all the existing examples and think i've got my head around a fair portion of it already.

I have no idea how to test it though. Im using chropath to find the xpaths i need for various bits and pieces but is there any overall guidance you can provide to start testing things.

**Comment by insickin** [comment]
I'd like to help in adding sites but don't know how, can you make a guide or an example sheet of some sorts on how we all can add sites (py files) to be incorporated into the agent?

**Comment by PAhelper** [comment]
It looks like @b0nensfw beat us to it. I will try to create better documentation for adding new sites over in [the wiki](https://github.com/PAhelper/PhoenixAdult.bundle/wiki)

**Comment by SgtBatten** [comment]
Thanks to would be great. 

So what's the deal with all the other repos. If people get other sites working do you add them to this repo?

I have not tested it yet but front he description nubiles might only work via shoot ID.

I'll have a look today at it as I was trying to get it working based on title but some sub sites were not search friendly

**Comment by Sinjin69** [comment]
@SgtBatten can this be closed?

**Comment by claygoldfinch** [comment]
I think this issue is pretty much resolved. There's a good amount of info in the wiki, plus a "template" file in the repo.

**Comment by SgtBatten** [comment]
Plus I'm all over it now :)
