### ISSUE TITLE
Brazzers Scene ID update

### ISSUE THREAD

**Issue by pornportal** [PAhelper/PhoenixAdult.bundle#886]
Brazzers updated their site and with it, they updated all their IDs. They are now part of `network1service`, which is a good thing as in theory that means one less site to maintain here.
But this also means if you have a file `brazzers-9360-don't-touch-her.mp4` now the correct name is `brazzers-3794531-don't-touch-her.mp4`. This is quite unfortunate.

What I personally have done is:
- Download the metadata from `network1service` (which includes the new Ids and the old ones 'spartanId')
- Wrote a small script to rename all files
- Changed the brazzers logic to `network1service` in my fork

The problem is that the script and the files are not easily shareable/usable. We don't need to switch immediately, but the question is how long the "old" site will be available? How and when we make the switch? Do we somehow guide users to rename their files? Do we build an internal mapping of Ids (I can create and provide a mapping if we need one)?

**Comment by DirtyRacer1337** [comment]
API good thing, but ID on site not equal to API

**Comment by PowerModder** [comment]
I noticed that the ID is different from the "free" site to the "members area". For me the agent is still matching correctly my scenes. The only thing you need for now is to be careful to use the ID of the free site.

**Comment by matthid** [comment]
Yes this issue is to prepare/discuss the change. I'd assume they will eventually change their public site as well? And even if they don't it is quite confusing for newcomers...

**Comment by pornportal** [comment]
> API good thing, but ID on site not equal to API

> I noticed that the ID is different from the "free" site to the "members area". For me the agent is still matching correctly my scenes. The only thing you need for now is to be careful to use the ID of the free site.

Yes today everything still works. That is what I meant with "we don't need to switch immediately". But they might change this soon? In any case this is at the very least confusing...

**Comment by pornportal** [comment]
Looks like they now changed their site.

**Comment by DirtyRacer1337** [comment]
Already made PR #907

**Comment by pornportal** [comment]
@DirtyRacer1337 Yes, so we should at least mention in the release notes that users need to rename or redownload their files and we'll close this?

**Comment by DirtyRacer1337** [comment]
Site works bad, but looks like ids not changed

**Comment by pornportal** [comment]
> but looks like ids not changed

They did change, see my example in the opening post.
Interestingly, they still have a redirect: For example, if you access https://www.brazzers.com/scenes/view/id/9360/dont-touch-her you will be redirected to https://www.brazzers.com/video/3794531/dont-touch-her

**Comment by DirtyRacer1337** [comment]
Ok, that id exists in API by name `spartanId`, but no reason to support it, that id not part of the site, I just merge it.
