### ISSUE TITLE
DorcelClub matching but not pulling any information or pictures

### ISSUE THREAD

**Issue by MrDemous** [PAhelper/PhoenixAdult.bundle#887]
DorceClub can find and match scenes just fine but it doesn't pull any scene information, actors, pictures, or anything else.

**Comment by DirtyRacer1337** [comment]
Fixed in 7b0386316b904565c096c7bd9383cc159a24e379

**Comment by MrDemous** [comment]
Thanks for the quick fix. It now pulls everything but doesn't pull actors.

**Comment by DirtyRacer1337** [comment]
Fixed in fafc697c85e14ced9cd6126791046e70e72d6b46
