### ISSUE TITLE
Vixen, ShareMyBF and Public Agent not returning results

### ISSUE THREAD

**Issue by SgtBatten** [PAhelper/PhoenixAdult.bundle#89]
please let me know what log file you need to see or I should be looking at.

multiple videos tried. names match the sites search features if i do it manually.

**Comment by woodbridgesub** [comment]
Can you provide a sample filename for a Vixen scene that you have? I have all Vixen scenes, and all are working for me, so maybe I can assist. My guess is the naming convention you are using might be the issue.

**Comment by SgtBatten** [comment]
It seems I am having issues with my webserver setup.

Plex is accessed via sub.domain.com and i can get results.

If i try the exact same match through my dashboard (where plex is hosted in an iFrame using the same sub.domain.com url) I am getting failures on a bunch of the networks. some work so it must be network specific as to who is blocking their content from being served inside my Iframe

I have successfully matched my Vixen now.

For the purpose of sharing with others who might see this issue heres the difference in the two searching manually for Vixen - An American in Greece

Plex.domain.com inside and iFrame

`Feb 22, 2019 09:52:38.499 [14820] DEBUG - HTTP 200 response from GET http://127.0.0.1:52461/:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU3CnMxNgoyOWNhNWQxODQxYzE0ZmNkczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczIxCkFuIEFtZXJpY2FuIGluIEdyZWVjZXM0Cm5hbWVzNAoyMDE4czQKeWVhcnM5NQpQJTNBJTVDUGxleCU1Q1ZpZGVvcyU1Q1RyYXZpcyU1Q1Bvcm4lNUNWaXhlbiU1Q0FuJTIwQW1lcmljYW4lMjBpbiUyMEdyZWVjZSUyMCgyMDE4LTA4LTEyKSUyRW1wNHM4CmZpbGVuYW1lczQwCjM1ZGY2N2FlNTAwMWE3OWNlNTY2NTFkZWM5OGY5MWI1ODRlODNiODVzOApwbGV4SGFzaHM3CjEzMDIyMjhzOApkdXJhdGlvbnM1CjE3MDA2czIKaWRyMAo_
Feb 22, 2019 09:52:38.499 [14820] DEBUG - [com.plexapp.agents.phoenixadult] HTTP reply status 200, with 16 bytes of content.
Feb 22, 2019 09:52:38.500 [7296] DEBUG - Completed: [127.0.0.1:58089] 200 GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU3CnMxNgoyOWNhNWQxODQxYzE0ZmNkczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczIxCkFuIEFtZXJpY2FuIGluIEdyZWVjZXM0Cm5hbWVzNAoyMDE4czQKeWVhcnM5NQpQJTNBJTVDUGxleCU1Q1ZpZGVvcyU1Q1RyYXZpcyU1Q1Bvcm4lNUNWaXhlbiU1Q0FuJTIwQW1lcmljYW4lMjBpbiUyMEdyZWVjZSUyMCgyMDE4LTA4LTEyKSUyRW1wNHM4CmZpbGVuYW1lczQwCjM1ZGY2N2FlNTAwMWE3OWNlNTY2NTFkZWM5OGY5MWI1ODRlODNiODVzOApwbGV4SGFzaHM3CjEzMDIyMjhzOApkdXJhdGlvbnM1CjE3MDA2czIKaWRyMAo_ (19 live) GZIP 3664ms 2326 bytes
Feb 22, 2019 09:52:38.506 [13708] DEBUG - HTTP 404 response from GET http://127.0.0.1:52220/system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&duration=1302228&filename=P%253A%255CPlex%255CVideos%255CTravis%255CPorn%255CVixen%255CAn%2520American%2520in%2520Greece%2520(2018-08-12)%252Emp4&lang=en&openSubtitlesHash=29ca5d1841c14fcd&plexHash=35df67ae5001a79ce56651dec98f91b584e83b85&name=An%20American%20in%20Greece&year=2018&manual=1
Feb 22, 2019 09:52:38.506 [13708] DEBUG - [com.plexapp.system] HTTP reply status 404, with 0 bytes of content.
Feb 22, 2019 09:52:38.507 [8548] DEBUG - Completed: [127.0.0.1:58086] 404 GET /system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&duration=1302228&filename=P%253A%255CPlex%255CVideos%255CTravis%255CPorn%255CVixen%255CAn%2520American%2520in%2520Greece%2520(2018-08-12)%252Emp4&lang=en&openSubtitlesHash=29ca5d1841c14fcd&plexHash=35df67ae5001a79ce56651dec98f91b584e83b85&name=An%20American%20in%20Greece&year=2018&manual=1 (19 live) GZIP 3699ms 148 bytes
Feb 22, 2019 09:52:38.507 [10312] DEBUG - HTTP 404 response from GET http://127.0.0.1:32400/system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&duration=1302228&filename=P%253A%255CPlex%255CVideos%255CTravis%255CPorn%255CVixen%255CAn%2520American%2520in%2520Greece%2520(2018-08-12)%252Emp4&lang=en&openSubtitlesHash=29ca5d1841c14fcd&plexHash=35df67ae5001a79ce56651dec98f91b584e83b85&name=An%20American%20in%20Greece&year=2018&manual=1
Feb 22, 2019 09:52:38.507 [10312] ERROR - Error parsing content.
Feb 22, 2019 09:52:38.508 [10312] ERROR - Exception caught while attempting to match metadata on item 17006: Error parsing file
Feb 22, 2019 09:52:38.508 [10312] ERROR - XML was (0 bytes):
Feb 22, 2019 09:52:38.513 [7296] DEBUG - Completed: [192.168.1.106:64112] 200 GET /library/metadata/17006/matches?manual=1 (19 live) TLS GZIP 3714ms 555 bytes (pipelined: 7) `

plex.domain.com not inside an IFrame:

`Feb 22, 2019 09:52:44.272 [6740] DEBUG - Request: [192.168.1.106:64112 (Subnet)] GET /library/metadata/17006/matches?manual=1&title=vixen%20-%20An%20American%20in%20Greece&agent=com.plexapp.agents.phoenixadult&year=&language=en (18 live) TLS GZIP Signed-in Token (SgtBatten)
Feb 22, 2019 09:52:44.277 [6740] DEBUG - Issuing search query: http://127.0.0.1:32400/system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&lang=en&name=vixen%20-%20An%20American%20in%20Greece&year=&manual=1
Feb 22, 2019 09:52:44.277 [6740] DEBUG - HTTP requesting GET http://127.0.0.1:32400/system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&lang=en&name=vixen%20-%20An%20American%20in%20Greece&year=&manual=1
Feb 22, 2019 09:52:44.289 [14820] DEBUG - Request: [127.0.0.1:58096 (Loopback)] GET /system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&lang=en&name=vixen%20-%20An%20American%20in%20Greece&year=&manual=1 (19 live) GZIP Signed-in
Feb 22, 2019 09:52:44.290 [14820] DEBUG - [com.plexapp.system] Sending command over HTTP (GET): /system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&lang=en&name=vixen%20-%20An%20American%20in%20Greece&year=&manual=1
Feb 22, 2019 09:52:44.290 [14820] DEBUG - HTTP requesting GET http://127.0.0.1:52220/system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&lang=en&name=vixen%20-%20An%20American%20in%20Greece&year=&manual=1
Feb 22, 2019 09:52:44.310 [0204] DEBUG - Request: [127.0.0.1:58098 (Loopback)] GET /:/plugins (20 live) GZIP Signed-in Token (SgtBatten)
Feb 22, 2019 09:52:44.311 [8548] DEBUG - Completed: [127.0.0.1:58098] 200 GET /:/plugins (20 live) GZIP 2ms 664 bytes
Feb 22, 2019 09:52:44.320 [10312] DEBUG - Request: [127.0.0.1:58099 (Loopback)] GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1CjE3MDA2czIKaWRzMjkKdml4ZW4gLSBBbiBBbWVyaWNhbiBpbiBHcmVlY2VzNApuYW1lbnM0CnllYXJyMAo_ (20 live) GZIP Signed-in Token (SgtBatten)
Feb 22, 2019 09:52:44.321 [10312] DEBUG - [com.plexapp.agents.phoenixadult] Sending command over HTTP (GET): /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1CjE3MDA2czIKaWRzMjkKdml4ZW4gLSBBbiBBbWVyaWNhbiBpbiBHcmVlY2VzNApuYW1lbnM0CnllYXJyMAo_
Feb 22, 2019 09:52:44.321 [10312] DEBUG - HTTP requesting GET http://127.0.0.1:52461/:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1CjE3MDA2czIKaWRzMjkKdml4ZW4gLSBBbiBBbWVyaWNhbiBpbiBHcmVlY2VzNApuYW1lbnM0CnllYXJyMAo_
Feb 22, 2019 09:52:44.344 [13708] DEBUG - Request: [127.0.0.1:58101 (Loopback)] GET /library/metadata/17006/tree (21 live) GZIP Signed-in Token (SgtBatten)
Feb 22, 2019 09:52:44.348 [8548] DEBUG - Completed: [127.0.0.1:58101] 200 GET /library/metadata/17006/tree (21 live) GZIP 4ms 966 bytes
Feb 22, 2019 09:52:44.439 [10312] DEBUG - HTTP 200 response from GET http://127.0.0.1:52461/:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1CjE3MDA2czIKaWRzMjkKdml4ZW4gLSBBbiBBbWVyaWNhbiBpbiBHcmVlY2VzNApuYW1lbnM0CnllYXJyMAo_
Feb 22, 2019 09:52:44.439 [10312] DEBUG - [com.plexapp.agents.phoenixadult] HTTP reply status 200, with 2516 bytes of content.
Feb 22, 2019 09:52:44.440 [7296] DEBUG - Completed: [127.0.0.1:58099] 200 GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1CjE3MDA2czIKaWRzMjkKdml4ZW4gLSBBbiBBbWVyaWNhbiBpbiBHcmVlY2VzNApuYW1lbnM0CnllYXJyMAo_ (21 live) GZIP 119ms 3313 bytes
Feb 22, 2019 09:52:44.447 [14820] DEBUG - HTTP 200 response from GET http://127.0.0.1:52220/system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&lang=en&name=vixen%20-%20An%20American%20in%20Greece&year=&manual=1
Feb 22, 2019 09:52:44.447 [14820] DEBUG - [com.plexapp.system] HTTP reply status 200, with 1083 bytes of content.
Feb 22, 2019 09:52:44.447 [6740] DEBUG - HTTP 200 response from GET http://127.0.0.1:32400/system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&lang=en&name=vixen%20-%20An%20American%20in%20Greece&year=&manual=1
Feb 22, 2019 09:52:44.448 [8548] DEBUG - Completed: [127.0.0.1:58096] 200 GET /system/agents/search?mediaType=1&id=17006&identifier=com.plexapp.agents.phoenixadult&lang=en&name=vixen%20-%20An%20American%20in%20Greece&year=&manual=1 (21 live) GZIP 158ms 739 bytes
Feb 22, 2019 09:52:44.448 [6740] DEBUG - 100: An American in Greece [Vixen] 2018-08-12 ()  `

**Comment by SgtBatten** [comment]
It seems even without using the Iframe I still get 404 errors on some searches. 

For example:

Vixen - Sparring Partner is successful almost instantly.
Vixen - I waited for you searches for over a minute and returns nothing. 404 in log

**Comment by SgtBatten** [comment]
Okay i renamed all the files to add Vixen - in front and remove the (date) from the end. They all auto matched.

I was relying on manual testing to see if it was worth renaming each network site i have collected. It seems manual searches are still influenced by the file name.

about to test with public agent now

**Comment by SgtBatten** [comment]
seems the filename still plays a major role even when manually matching. Now i know i'm not having issues.
