### ISSUE TITLE
EvilAngel problem

### ISSUE THREAD

**Issue by fritz276** [PAhelper/PhoenixAdult.bundle#9]
File "/var/db/plexdata/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteEvilAngel.py", line 54, in update
    metadata.director = directedBy.strip()

**Comment by PAhelper** [comment]
This was a rare site that actually lists the director, so I tried to add it to the metadata, without success. I have commented that section of the code out, which should resolve this issue.
