### ISSUE TITLE
Brazzers Mismatch with ID after update - 'Quick Fix'

### ISSUE THREAD

**Issue by PowerModder** [PAhelper/PhoenixAdult.bundle#912]
I don't know if it is only mine problem but many of my files didn't match properly after the update to network1service.
I am using a Title of SiteName - ID - Actor Infos - SubSite (short)
Seeing the logs i found out that with sceneID and my filename combo (with more informations) it does a search query using the encoded title (line 29 of network1service.py) instead of just using the sceneID (line 27 of network1service.py)
I replaced
`if sceneID and not searchTitle ` (line 26 of network1service.py)
with
`if sceneID`
and that returned a perfect 1-1 match for all of my files
I didn't submit the change as 1st i don't know if i was the only one with the problem and 2nd it will affect other sites too.
@DirtyRacer1337 please see if my 'logic' is correct that way and if yes embed it to the network1service

**Comment by DirtyRacer1337** [comment]
Some scene titles starts with numbers, your fix makes it impossible to search them

**Comment by PowerModder** [comment]
I understand what are you saying because the agent will get the number as an ID if it starts with that. However, at line 29 we are using the encodedTitle to do the search and not searchTitle. Correct?
Also, having a 'logic' of 'sceneID and not searchTitle' will always be 'false' if you have SiteName - SceneID - Extra Infos because you have sceneID AND searchTitle combined.

**Comment by DirtyRacer1337** [comment]
Everything is correct, just use SceneID without any info

**Comment by PowerModder** [comment]
Ok. Thanks I will close it
