### ISSUE TITLE
VRBANGERS Seems broken again

### ISSUE THREAD

**Issue by boivinx7** [PAhelper/PhoenixAdult.bundle#928]
Its not finding anything
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5032034/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed in dafbe10df42b3d78ba450f4a7cff82db0c68a4e7
