### ISSUE TITLE
Some Spizoo videos without Actors

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#931]
**Describe the bug**
Some Spizoo videos don't show Actors, dates, poster.

**Include**
1. https://www.spizoo.com/updates/Gina-And-Sophia-Threesome.html
   https://www.spizoo.com/updates/Sarah-Jessie-Loves-Oil.html
2. Spizoo - Gina And Sophia Threesome.mp4
    Spizoo - Sarah Jessie Loves Oil.mp4
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5043504/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed in 6458a835dad627e28acb0039f984b2fef36345af
