### ISSUE TITLE
PassionHD poster improvements

### ISSUE THREAD

**Issue by SgtBatten** [PAhelper/PhoenixAdult.bundle#95]
PassionHDs website used to have 19 images per scene hidden in the XML. This is no longer the case.

I plan to attempt to use passionhdfan links to get more images for passionHD.

I will post updates on my progress here and seek advice until I can get something in a pull request.

**Comment by SgtBatten** [comment]
Made good progress on this today. Matching with the fan site is working based on a Google search query and then unchecking the results against the actor name.

Successfully pulling the summary from the fan site already.

Seems other pornpros sites also have a fan site so this might work for them all.

I can see the URLs of the 25 or so images I want to pull but for some reason my xpath query is returning an empty list.

**Comment by SgtBatten** [comment]
I'm struggling with one last element. Currently I am getting duplicate images because the <img> contains 4 different urls.

Ideally I only want the url at data-orig-file but in practice any of them will work. I have tried a hundred different things but always end up unable to filter one url per <img>

    posters = fanPageElements.xpath('//img[contains(@class, "lazy")]/@data-orig-file')
        for posterURL in posters:
            art.append(posterURL)

**Comment by PAhelper** [comment]
posters = fanPageElements.xpath('//img[contains(@class, "lazy")])
        for posterURL in posters:
            art.append(posterURL.get('data-orig-file'))

**Comment by SgtBatten** [comment]
@PAhelper Thanks mate. I have tried it like that too but checked again. Still pulls more than the one url.

I've also tried .get('src') and a couple others. None seem to actually filter correctly.

**Comment by SgtBatten** [comment]
Success....

Working on lubed and passion HD already. Will have to test other sites from this network tomorrow.

Noticed it's very slow though as I think the images are quite big. What do you think about grabbing a random 10 instead of 25+ images.

**Comment by PAhelper** [comment]
I've had 2 sites that exposed a large number of images to use as artwork. One I grabbed every 5th image so there was a nice spread from the whole set, and the other I grabbed 9 randomly. I think I like randomly better, because it you don't like what you got, you can just refresh and get 9 more. That does mean you have to process all the available images in the code, but only pass 9 or so to actually be downloaded.

sitePrivate and siteJulesJordan if you're looking for code examples...

**Comment by SgtBatten** [comment]
Found the random.sample built in to python to work well.

Pull request submitted.

Can be further improved I'm sure. More sites should be fairly easy to test and add as well

**Comment by SgtBatten** [comment]
merged #103
