### ISSUE TITLE
ScrewMeToo no shows Actors

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#961]
ScrewMeToo no shows Actors/Actress cast

**Include**
1. https://screwmetoo.com/fhg/asian-latina-chick-wild-date/
2. ScrewMeToo - Miyuki Asian Latina Mix Back For More Dick.mp4
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5105957/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed in de45bffd5707c8325bce6b0c70dcad272d75b84b
