### ISSUE TITLE
Hustler no shows metadata

### ISSUE THREAD

**Issue by drraymond27** [PAhelper/PhoenixAdult.bundle#975]
**Describe the bug**
Hustler matches, but no shows nothingof metadata
**Include**
1. https://hustler.com/trailers/my-stepmom-caught-me-jerking-off-nikki-delano-h.html?LFPID=568831
2. Hustler - My Stepmom Caught Me Jerking Off featuring Nikki Delano
3.  [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5143136/com.plexapp.agents.phoenixadult.log)

**Comment by DirtyRacer1337** [comment]
Fixed in 81dda37467c3fb1317e2a90c49024c2fb930bdb0
