### ISSUE TITLE
Question regarding scanning of files and parsing of title

### ISSUE THREAD

**Issue by monkTertman** [PAhelper/PhoenixAdult.bundle#984]
I was looking at the file name and Plex Video Files Scanner is messing stuff up.

So I have a file name `[DirtyMasseur] Anna Bell Peaks - Massumptions (14.09.2017) rq (1k).mp4`, this is totally unprocessed.
But even entering this into PhoenixAdult custom match gives me exactly the video I am looking for.

But my files are not being auto matched.
Plex Video Files Scanner is changing the title to `Anna Bell Peaks Massumptions 14 09` and then PhoenixAdult is unable to match it.

Is there a solution to this madness?

**Comment by DirtyRacer1337** [comment]
Date should be like 2017-09-14 and it's written in [File Naming](https://github.com/PAhelper/PhoenixAdult.bundle#file-naming)

**Comment by monkTertman** [comment]
Cool.
Ran a regex script to remove square brackets and fix names as much as I can.

**Comment by PowerModder** [comment]
@monkTertman Just a note if you want, you can use my Watchdog Scene Renamer (postprocessing2 at this repo) to rename your files faster and with your preferences. My Watchdog scans a given directory and sub-directories for media files and when found it sees at what folder the scene is in and then call for a match for that scene. Given your scene as an example, I have a Watcher folder (the root folder where the Watchdog is active) and inside i have a Brazzers sub-directory (sub-folder). I placed my .mp4 renamed as  `[DirtyMasseur] Anna Bell Peaks - Massumptions (14.09.2017) rq (1k).mp4` to the Brazzers sub-directory.
and got back those file names according to my preferences:
```
ID and stripSymbol
Brazzers - 2017-09-14 - 3898351 ~ Anna Bell Peaks & Keiran Lee - Dirty Masseur
```
Then the Watchdog is AUTO-renaming your file and move it to your Plex Directory or to any other directory you want.
