### ISSUE TITLE
Playboy Plus actor/cast tagging

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#985]
**Describe the bug**
I was tagging a Playboy Plus scene and saw that the agent doesn't tag the cast while cast information is available on the Playboy Plus site.

**Include**
1. Scene URL = https://www.playboyplus.com/gallery/classic-style
2. File Name = Playboy Plus - Classic Style
3. Log File = [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/5146898/com.plexapp.agents.phoenixadult.log)

**Comment by monkTertman** [comment]
Hey @insickin , 
PlayboyPlus does support cast tagging. Your video has multiple models and I dont think it supports tagging of multiple models.
