### ISSUE TITLE
FakeHub Support

### ISSUE THREAD

**Issue by insickin** [PAhelper/PhoenixAdult.bundle#99]
As I tag FakeHub scenes I get a pixelated/small background picture, I see that you can get a better version of the same picture off the site, for example:

Pixelated:
https://photo-ht.fakehubcontent.com/movies/33/3358649/fho_lindsey_cruz_ru010419_main.jpg

Not pixelated:
https://photo-ht.fakehubcontent.com/movies/33/3358649/fho_lindsey_cruz_ru010419_1021x574_1.jpg

Can you take a look at it?

**Comment by PAhelper** [comment]
Also found there was a second image for each scene at https://photo-ht.fakehubcontent.com/movies/33/3358649/fho_lindsey_cruz_ru010419_1021x574_2.jpg

Updated code for both FakeHub and SexyHub. If this is working for you, please feel free to close this issue.

**Comment by insickin** [comment]
I tested it and after a refresh still get the pixelated low res photo automatically as the background picture BUT can now select more images  manually among which a higher res photo!

**Comment by insickin** [comment]
Its working now, thanks!
